### ISSUE TITLE
Resuming a workflow from among multiple suspended workflows makes other workflows faulted.

### ISSUE THREAD

**Issue by AvtsVivek** [elsa-workflows/elsa-core#1003]
I have created a new sample asp.net mvc app(P255SuspendResume) to understand Suspend and Resume workflows. This sample is based on [Correlation Http Sample](https://github.com/elsa-workflows/elsa-core/tree/master/src/samples/aspnet/Elsa.Samples.CorrelationHttp)

I think found a bug.

I added this project to the Elsa source and changed the references from Version="2.0.0-rc2.73" to the source so that I can debug.

[P255SuspendResume.zip](https://github.com/elsa-workflows/elsa-core/files/6500445/P255SuspendResume.zip)

When I run the project it looks as follows. I can start workflows by clicking the Start Workflow link. I can get he workflow details by clicking the blue button. Currently as the app just started, it shows 0 workflows running. 

![image](https://user-images.githubusercontent.com/41255281/118625735-e3ac9980-b7e7-11eb-95ec-be09c73c0d1d.png)

Now I start two workflows by clicking the Start Workflow link twice. Then clicking the blue **Get Workflow Details** button gives the details. Both the workflows are in suspended state as expected. 

![image](https://user-images.githubusercontent.com/41255281/118626695-b8767a00-b7e8-11eb-9df0-fe225b864d6e.png)

Now I go to one of the tabs to resume the workflow. 

![image](https://user-images.githubusercontent.com/41255281/118627295-376bb280-b7e9-11eb-86fc-6962bb6dc06b.png)

Now it resumes and gets finished as well.

![image](https://user-images.githubusercontent.com/41255281/118627849-afd27380-b7e9-11eb-95a4-b18fa0420065.png)

Here is the problem. 

If I now get the details of the workflows, I get the state for one as Finished(as expected), but the other one as Faulted, while I expect that to be Suspended. 

![image](https://user-images.githubusercontent.com/41255281/118628326-21aabd00-b7ea-11eb-9591-8698843b155e.png)

I tried to dig into source. Searching for Fault, I placed a breakpoint as shown below in the workflow execution context file of Elsa Abstractions. Its at around line 176(pulled the latest a week back)

The string message that you see raveled the message to be "**Response has already started**"
 
![image](https://user-images.githubusercontent.com/41255281/118629985-bc57cb80-b7eb-11eb-844f-e44c659a35ee.png)

Searching for this string further and debugging led me to WriteHttpResponse.cs in Elsa.Activities.Http

![image](https://user-images.githubusercontent.com/41255281/118630835-8830da80-b7ec-11eb-9fbb-46269182fb19.png)

I could not get to the root of it, but call stack showed me the following. Here both the correlation id as well as the workflow id is null.  This is expected because I am not sending neither of them.

Looks like something is triggering the faulted workflow that is not intended.
![image](https://user-images.githubusercontent.com/41255281/118631535-363c8480-b7ed-11eb-8d22-bfe9ffbdaeca.png)

Also how can I trigger a workflow if I have the instance id?

The project in question is here.  [P255SuspendResume.zip](https://github.com/elsa-workflows/elsa-core/files/6500445/P255SuspendResume.zip)

**Comment by sfmskywalker** [comment]
First of all, compliments for the details step-by-step and fully-functioning sample project, that really helps.

What you are seeing is exactly what would be expected with the current setup: if you click the Start Workflow button twice, two workflow instances will be created and both will be blocked on the second HTTP Endpoint (/resume) activity. Since these workflow activities aren't correlated and you are not providing a workflow instance ID or correlation ID, Elsa will simply trigger any workflow that starts with or is blocked on HTTP Endpoint with the /trigger path.

To change this, we need to do two things:

1. Correlate the workflow instance with some value. In your case, we can either generate a random value such as a GUID, or perhaps use the workflow instance ID, which is also a random GUID. I will show you the former method.
2. When generating the /resume hyperlink, we need to include the correlation ID.

For step 1, update your workflow as follows:

```csharp
builder
      .HttpEndpoint(activity => activity.WithPath("/StartWorkflow").WithMethod(HttpMethods.Get))
      .Correlate(() => Guid.NewGuid().ToString()) // <-- Add this line to correlate your workflow with some unique value. 
```

If you wanted to use the workflow instance ID as the correlation ID, simply replace the `Correlate` activity with:

```csharp
.Correlate(context => context.WorkflowInstance.Id)
```

For step 2, apply the following update:

```csharp
return $"Thanks for starting the workflow. Now the workflow will be suspended.! Please <a href=\"/resume?correlation={context.CorrelationId}\">click here to resume the workflow</a>";
```

Notice the addition of the `correlation` querystring parameter - this will be recognized by the HTTP Endpoint Middleware component and trigger the correct workflow.

**Attention**

While I was writing the above steps and testing them out, I identified a bug in the HTTP Endpoint Middleware component where it fails to pass along the correlation ID. This is a bug I introduced very recently but will push a fix for right away.

**Comment by sfmskywalker** [comment]
[Build 2.0.0-rc2.106](https://ci.appveyor.com/project/sfmskywalker/elsa/builds/39218759) will contain the fix - which means you will have to reference the packages from the MyGet feed. Or wait until I publish Elsa 2.0 RC3 to NuGet later this week or early next week.
