### ISSUE TITLE
Composite Activity and Workflow Instance produces NullReferenceException.

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#1022]
Yes, again annoying me, reopening #1017 .
You closed it with comment "this was by design" and pushed change which resolved phantom "Done" output but not this.

So, I just wanted to make you didn't misunderstood me and I did not misunderstood you.
Because I kind of don't believe that NullReferenceException should be something by design.

Hence repeating the problem and lets see :).

I wrote composite activity, code is provided below.
Composite activity accepts http endpoint output as input through property (workflow attached in #1017).
When I execute it, it works as expected.

However when I open Workflow Instance viewer of the execution I get NullReferenceException on line return Request.Method == "GET";. Seems at that point Request is null (only when viewing instance, when executing all is ok!).

**Did I do something wrong? Should composite activity be written differently?**

    public class OutcomeNames : Elsa.OutcomeNames
    {
        public const string Pass = "Pass";
        public const string Failed = "Failed";
    }
    
    [Action(
      Category = "TESTING",
      DisplayName = "Test Composite Activity",
      Description = "Test Composite Activity",
      Outcomes = new[] { OutcomeNames.Pass, OutcomeNames.Failed }
    )]
    
    public class TestContainer : CompositeActivity
    {
        [ActivityProperty(
            Label = "HTTP Request",
            UIHint = ActivityPropertyUIHints.SingleLine,
            DefaultSyntax = SyntaxNames.JavaScript,
            SupportedSyntaxes = new[] { SyntaxNames.JavaScript }
        )]
        public HttpRequestModel Request
        {
            get => GetState<HttpRequestModel>(() => null);
            set => SetState(value);
        }
    
    
        public override void Build(ICompositeActivityBuilder builder)
        {
            builder
                .If(method =>
                {
                    return Request.Method == "GET";
                },
                @if =>
                {
                    @if
                        .When(If.True)
                        .Then<WriteHttpResponse>(resp => resp
                            .WithStatusCode(HttpStatusCode.BadRequest)
                            .WithContent("*** GET IS BAD REQUEST")
                            .WithContentType("text/plain"))
                        .Finish(OutcomeNames.Failed);
                    @if
                        .When(If.False)
                        .Then<WriteHttpResponse>(resp => resp
                            .WithStatusCode(HttpStatusCode.OK)
                            .WithContent("*** POST IS GOOD REQUEST")
                            .WithContentType("text/plain"))
                        .Finish(OutcomeNames.Pass);
                });
        }
    }

**Comment by sfmskywalker** [comment]
I indeed seem to have overlooked your concern there with the NRE, sorry about that.

The exception however is actually expected - when you open the workflow instance viewer, Elsa builds a workflow model and in doing so, evaluates all of the expressions - many of them potentially failing as you have seen. Now, although this generates noise, it does not cause an actual issue since these unhandled exceptions will be caught (they are expected to happen in this scenario).

In your example, when the `Request` property is set on your `TestContainer` activity, it uses the JS expression `input`. But when the workflow model is built for the workflow instance viewer, that input doesn't exists as it's a transient value.

That being said, I'm not super-happy about this either. On the one hand, I like that simple expressions are being evaluated in order to provide an accurate picture in the workflow instance viewer, but on the other hand this does mean that complex expressions / expressions relying on data and services no longer there will fail to evaluate.

I will do some more thinking about this situation and see if I can't come up with a more elegant approach. For example, taking the input as an example, we might consider storing it somewhere, perhaps in a separate table. This table could contain all sorts of runtime information about the workflow that can then be fetched later to replicate its state in full.

Since this is potentially big and complicated, I will consider this as a potential improvement for a future version.

**Comment by tomy2105** [comment]
OK, I see, keep it in mind and fix as you see fit :).
Just to make it obvious, this doesn't happen with `input` transient variable only.
It happened to me also when I set it to `Request.Output` where `Request` is the name of the endpoint block (and I think this output is stored in DB somewhere :)).

**Comment by sfmskywalker** [comment]
One idea I have is to store the computed values as part of the workflow instance, so that when you load the workflow instance in the viewer, it won't have to re-evaluate each property.

**Comment by tomy2105** [comment]
Yes, that would be a good idea.
However should be careful not to store too much data into database :).
And that database cleanup task after some period would be important :).

**Comment by sfmskywalker** [comment]
Fixed with #1060

Regarding the data size stored in the database, I think that could be handled together with #898.
Yes indeed, we also need database retention services to cleanup the database. Could be done with #412
