### ISSUE TITLE
ParallelForEach: wait for all items to finish

### ISSUE THREAD

**Issue by arst** [elsa-workflows/elsa-core#1025]
I have a workflow that has nested ParallelForEach:

   ```
    builder
                .HttpEndpoint("/hello-world")
                .ForEach(new String[] { "one", "two" }, i =>
                    i.
                        WriteLine("Next itter")
                        .ParallelForEach(
                            new String[] { "none", "ntwo" },
                            it =>
                                it
                                    .SetVariable("current", v => v.GetInput<string>())
                                    .WriteLine(p => p.GetVariable<string>("current"))
                                    .HttpEndpoint(e => $"/nested-{e.GetVariable<string>("current")}")
                                    .WriteLine("Nested Finished")))
                .WriteLine("All Finished");
```

What I expect from it:
1. /hello-world hit
2. "Next itter"
3. Workflow waits on both "none", "ntwo" to finish
4. When both  nested-none, nested-ntwo endpoints hit workflow proceeds to the next itteration
5.  "Next itter"
6.  Workflow waits on both "none", "ntwo" to finish
7. When both  nested-none, nested-ntwo endpoints hit workflow proceeds to the end of the workflow
8. "All Finished"

What actually happens:

1. /hello-world hit
2. "Next itter"
3. Workflow halts
4. When only nested-ntwo endpoint hit workflow proceeds to the next itteration
5.  "Next itter"
6.  Workflow halts
7. When only nested-ntwo endpoint hit workflow proceeds to the end of the workflow
8. "All Finished"

I'm wondering what is wrong with my current Setup? Or is it expected behavior for ParallelForEach?

**Comment by sfmskywalker** [comment]
I think your expectations and workflow are correct, but that there's a limitation with the way Elsa stores and handles blocking activities. 

What the ParallelForEach activity does is it iterates over each item immediately and so schedules multiple Iterate outcomes, which of course schedules each subsequent activity for execution.

If now a blocking activity is encountered, it gets stored as a blocking activity in the workflow by storing the activity ID and type.
And herein lies the rub: the blocking activities collection *is a hash set* - which means that every time the HTTP Endpoint activity gets registered here, it overwrites the previous one.

So this is something we should fix.

**Comment by sfmskywalker** [comment]
Another observation is that when one iterates over e.g. a list of string values `["apple", "pear", "mango"]` and sets a variable which is then used in e.g. `SignalReceived` to dynamically set the signal name, the bookmark indexing step fails to use the expected value.

This is because when bookmarks are being indexed, a separate activity execution context is created in order to re-evaluate the activity properties of the blocking activities.

So we need to somehow capture the scope of each iterate branch execution.
To be pondered further.

Until then, the parallel for each activity is useless when used in combination with blocking activities such as HTTP Endpoint and Signal Received 😞

**Comment by sfmskywalker** [comment]
To be fixed with #1059

**Comment by ChrisBertrand** [comment]
Is there a workaround for this?

**Comment by sfmskywalker** [comment]
Maybe, depending on your use case?

**Comment by ChrisBertrand** [comment]
I'd like to use parallel foreach where each contains a blocking activity. Is that now looking to be added in v3?

**Comment by sfmskywalker** [comment]
Yes, Elsa 3 has the right architecture in place in order for blocking activities to be used in the parallel for each activity. There, it can work because each activity execution happens in its own instance, which means it has its own scope and identifier, which can then be leveraged by code that resumes blocking activities. Elsa 2 doesn’t have these constructs unfortunately.

**Comment by sfmskywalker** [comment]
Done via https://github.com/elsa-workflows/elsa-core/pull/4306
