### ISSUE TITLE
Can't reach Http Endpoint

### ISSUE THREAD

**Issue by atorres16** [elsa-workflows/elsa-core#1029]
I added an HttpEndpoint, but when I try to call it, it just sends me back the dashboard home page and no workflow instance is created (I wasn't having issues with RC1)

![image](https://user-images.githubusercontent.com/19210281/119231625-73ec2680-bae7-11eb-9063-14f275eba378.png)

![image](https://user-images.githubusercontent.com/19210281/119231613-62a31a00-bae7-11eb-990f-a6169321c8db.png)

![image](https://user-images.githubusercontent.com/19210281/119231603-53bc6780-bae7-11eb-84dd-9d370493b1cc.png)

**Comment by sfmskywalker** [comment]
Is this a custom project you created yourself or are you running a sample project or docker image?

Reason I’m asking is because one or two samples have been updated to include a base path for the HTTP Endpoint, which is “/workflows”. Which means that the full path would be “/workflows/task”.

Regardless if this is the issue or not, I can imagine others running into this so I’ll see if I can show the base path in the UI.

**Comment by atorres16** [comment]
Yes, /workflows does it
(I'm running the monolith sample)

Thank you!
