### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by cando** [elsa-workflows/elsa-core#103]
First, thanks for your awesome work.

Do you any plans to introduce localization support? Ideas on how you would like it to be implemented?
I would like to have the possibility to translate the names and descriptions of the activities as well every single string in the elsa-dashboard: the localization of the GUI is a must for our needs and I'd like to see it implemented.
If you give me the direction I try to see if I have enough time implement something :)

**Comment by sfmskywalker** [comment]
Thanks :)

Localization is a great idea and something I’d like to see be supported.

Regarding the names and descriptions of the activities, I think we should leverage the .NET Standard APIs for that such as ILocalizedString. The activity classes are annotated with attributes that contain these names and descriptions, so first thing we should look at is see how we can employ localized resource strings.

Regarding the dashboard, I actually want to re-implement it using the Orchard Core Framework so that it becomes an modular, extensible dashboard taking advantage of things like authentication, user management, extensibility using modules and localization, to name just a few aspects.

There’s a separate issue for this.

If you want then maybe the localized activity attributes is a good place to start. Meanwhile, I’ll be focusing on refactoring the Dashboard into an Orchard Core theme and module with @giannik
