### ISSUE TITLE
Oracle persistence 

### ISSUE THREAD

**Issue by akghasemi** [elsa-workflows/elsa-core#1041]
Hi,
I there any chance to use Oracle as persistence database,I mean I am aware of IWorkflowDefinitionStore interface that you can impelemnt custom store but the thing that I want to use exsiting dbcontext and Elsa model definions and just like the postgres
I want to have Oracle EntityFrameworkCore provider.
currently I add postgres like this:
services.AddElsa(elsa => elsa.AddEntityFrameworkStores<PostgreSqlContext>())
I want to use
services.AddElsa(elsa => elsa.AddEntityFrameworkStores<OracleContext>())
I tried to create similar classes that exists for postgres:
PostgreSqlContext
PostgreSqlContextFactory
in oracle but instead of using UsePostgres ,I used UseOracle in configuration builder.
the Elsa designer starts but it doesn't save anything and wierd thing is that ,it is not throwing any errors as well !
what am I missing here

**Comment by sfmskywalker** [comment]
That should absolutely be possible. All you would have to do is:

1. Add the `Oracle.EntityFrameworkCore` package
2. `services.AddElsa(elsa => elsa.UseEntityFrameworkPersistence(ef => ef.UseOracle(@"User Id=blog;Password=<password>;Data Source=pdborcl;")))`
3. Create a new class that implements `IDesignTimeDbContextFactory<ElsaContext>` so that you can generate migrations.
4. Generate the migrations. [These docs](https://elsa-workflows.github.io/elsa-core/docs/next/installation/installing-persistence#running-migrations-manually) show how it's done for Sqlite, but works the same for other EF Core providers.

Regarding your issue where nothing gets saved, that's hard to tell without seeing your actual project.

**Comment by akghasemi** [comment]
thanks for the answer but is there anyway to see if an error happening inside Elas,becasue when I change it to postgres it works fine but when I change it back to Oracle still it works but nothing saved,how can I trace this?

**Comment by sfmskywalker** [comment]
Sure, just launch with the debugger attached and make sure it breaks on exceptions.

**Comment by akghasemi** [comment]
Are you sure with this approch Elsa dashboard works also because I am trying to create workflow there but they are not saved,it looks it is working with in memory database.by the way I am using ELSA 1.4.7.4 because my project is .net core 3.1

**Comment by sfmskywalker** [comment]
Yes, there shouldn't be any reason it doesn't also work with Elsa 1. If it works for SQL Server, it works for Oracle too since they have an EF Core provider. 

To troubleshoot this, what you might do is clone the project and check out the commit tagged with 1.4.7 (888aa0c86f28719c9f4e53a2408b5ad1e84ee5c5) and reference the necessary Elsa projects directly. Now you can follow the code execution with the debugger.

**Comment by akghasemi** [comment]
By the way I can't find the extension method UseEntityFrameworkPersistence anywhere

**Comment by sfmskywalker** [comment]
Sorry, I assumed you were using Elsa 2. For Elsa 1, it's `AddEntityFrameworkStores`. Here's [an example using SQL Server](https://github.com/elsa-workflows/elsa-core/blob/1.4.x/src/samples/Sample22/Program.cs#L68). Replace `SqlServerContext` with your own Oracle context and of course your own connection string.

**Comment by akghasemi** [comment]
sorry,this is my code insdie the ConfigureService in startup
 services.AddElsa(elsa => elsa.AddEntityFrameworkCoreProvider<Workflow.Oracle.OracleContext>(ef => ef.UseOracle(@"Data Source=192.168.1.1/xepdb;user id=admin;password=xxxxx;")))
            

            .AddElsaDashboard(options => options.Configure(x => x.ActivityDefinitions
                .Add<WriteLine>()
                .Add<ReadLine>()
                .Add<ReceiveHttpRequest>()
                .Add<SendHttpRequest>()
                .Add<WriteHttpResponse>()
                .Add<SetVariable>()
                .Add<ForEach>()
                .Add<While>()
                .Add<Fork>()
                .Add<Join>()
                .Add<IfElse>()
                .Add<Switch>()
                .Add<SendEmail>()
                .Add<CronEvent>()
                .Add<TimerEvent>()
                .Add<Correlate>()
                .Add<Finish>()
                .Add<Signaled>()
                .Add<Start>()
                .Add<TriggerSignal>()
                .Add<TriggerWorkflow>()
                .Add<RegisterApprovalActivity>()
                
            ));

and this is Oracle Context Class
 public class OracleContext: ElsaContext
    {
        public OracleContext(DbContextOptions<OracleContext> options) : base(options)
        {
        }
    }
but still it is not saving anything to database
