### ISSUE TITLE
Signal URL is generated with wrong base URL when the server is hosted as an application on IIS

### ISSUE THREAD

**Issue by tmammadov1** [elsa-workflows/elsa-core#1112]
Elsa 2.0

We're hosting Elsa server as an application on IIS (which hosts multiple other applications). When a signal URL is generated in a workflow, the base URL is incorrectly generated as 'localhost', such as `http://localhost:44311/signals/trigger/CfDJ8Ds7BSvoUwNLv5DvShdzpMcjtpT8yRKBQCMuznn7eiqYwPH6EJ1Pt9y9LAo1xN_VVOuawXGu6srW2btlGnJhEe8vdskABeXJaNPL5--LyvIGntqrWhMB28JTHzDIjER3uEU_-4jNNbeSK_FhxRVDZJQqYsLD4rMTTHUzwA0c2EFm8JJqm2V34w14nJxX1KC4t4PuCXu97EK2EWKRuKFb8C` which renders the URL invalid. Replacing the 'http://localhost:44311' with the actual Elsa base URL does not trigger the signal either.

Expected signal URL: `**actual_elsa_server_base_url**/signals/trigger/CfDJ8Ds7BSvoUwNLv5DvShdzpMcjtpT8yRKBQCMuznn7eiqYwPH6EJ1Pt9y9LAo1xN_VVOuawXGu6srW2btlGnJhEe8vdskABeXJaNPL5--LyvIGntqrWhMB28JTHzDIjER3uEU_-4jNNbeSK_FhxRVDZJQqYsLD4rMTTHUzwA0c2EFm8JJqm2V34w14nJxX1KC4t4PuCXu97EK2EWKRuKFb8C`

**Comment by tmammadov1** [comment]
@sfmskywalker this exact same issue was reported by another user a long time ago and just went stale because no one replied. Looks like this one is going in the same direction. Nobody is interested.

**Comment by sfmskywalker** [comment]
It’s not out of a lack of interest, but it all takes time. It’s good that you raise my awareness, because it helps me prioritize.

**Comment by mohdali** [comment]
Isn't the signal URL based on the Elsa.Http.BaseUrl config in the appsettings.json?

I believe that was the case for at least Elsa 1. Not sure if it changed in Elsa 2.

**Comment by sfmskywalker** [comment]
@mohdali You're right, but that is only used when generating absolute URLS from background tasks (where there's no HTTP context).

Thinking about it, perhaps we can simply update the `DefaultAbsoluteUrlProvider` to always use the configured base url. Because why not? You always need to configure it anyway for non-HTTP context code that needs to generate absolute URLS.

I'll go ahead and do just that.

@tmammadov1 if you're still having this issue after that change, please feel free to reopen.
