### ISSUE TITLE
Allow disabling of the HTTP Workflow Trigger APIs

### ISSUE THREAD

**Issue by datacore-kmcmurtrey** [elsa-workflows/elsa-core#1119]
This would allow a solution to restrict access of triggering workflows for security reasons.  The solution utilizing the Elsa NuGet package could disable the HTTP APIs and allow workflows to be triggered only by a non-HTTP route.

It requires a change in the HTTP Activities package to separate it from the extension method that registers various HTTP-related activities

**Comment by sfmskywalker** [comment]
After doing some research, a number of interesting options came up:

1. [Excluding the assembly carrying the controller from controller discovery](https://blog.dangl.me/archive/excluding-assemblies-in-aspnet-core-mvc-controller-discovery/).
2. [Using Feature Flags](https://docs.microsoft.com/en-us/azure/azure-app-configuration/manage-feature-flags).
3. [Using a custom action filter](https://stackoverflow.com/a/61332265/690374) (similar to using feature flags, but completely custom).
4. [Reimplement the API Endpoints as direct endpoints](https://khalidabuhakmeh.com/how-to-build-a-basic-http-api-with-aspnet-core).

Although I like the feature flags option a lot and perhaps option 4 even better, I'm not sure I'm ready to do it now because option 1 allows you to exclude controllers today without any changes necessary in Elsa. 

As it turns out, adding the following code to your Startup will do the trick:

```csharp
services.AddControllers().ConfigureApplicationPartManager(partManager =>
{
    var httpAssembly = partManager.ApplicationParts.First(x => x.Name == typeof(HttpEndpoint).Assembly.GetName().Name);
    partManager.ApplicationParts.Remove(httpAssembly);
});
```

The above code will effectively exclude the controllers found in the `Elsa.Activities.Http` assembly from controller discovery.

I'm closing this issue as resolved, but feel free to reopen if you run into any issues with the suggested approach.
