### ISSUE TITLE
Parallel For Each Control Flow Not Iterating Properly

### ISSUE THREAD

**Issue by Prabhat244** [elsa-workflows/elsa-core#1162]
I have Created a **Parallel For Each** Control flow after an HTTP Endpoint and have passed `[{"Email":"abc1@gmail.com"},{"Email":"abc2@gmail.com"},{"Email":"abc3@gmail.com"}]` as a Javascript input inside it and getting its output into the next activity, but when I run the workflow execution then **only first Email is iterating individually inside the Parallel For Each, not all 3 of them**. and getting the output of only the First Email 3 times into the next activity. It means that `Parallel For Each is not Iterating parallelly.`

The same Workflow scenario when I **Iterate using the For Each** instead of Parallel For Each, then it is **Iterating perfectly fine** means all of the 3 Email is iterating one by one along with the output of the next activity one by one.

<img width="950" alt="img1" src="https://user-images.githubusercontent.com/52523649/122968461-33631f80-d3a9-11eb-8c76-d3cd79fd1155.png">

<img width="949" alt="img2" src="https://user-images.githubusercontent.com/52523649/122968457-32ca8900-d3a9-11eb-993f-ae775fc30f1e.png">

<img width="943" alt="img3" src="https://user-images.githubusercontent.com/52523649/122968452-31995c00-d3a9-11eb-81a7-cb7efdffde4f.png">

**Comment by sfmskywalker** [comment]
I can't seem to reproduce this with the current version of Elsa (code on master branch). I attached the workflow I tried for comparison:

[workflow-definition-parallel-for-each-demo.zip](https://github.com/elsa-workflows/elsa-core/files/6725418/workflow-definition-parallel-for-each-demo.zip)

To execute the workflow, you can use the following API request (replace the workflow ID with your own):

```curl
curl --location --request POST 'https://localhost:11000/v1/workflows/53ff2cd4102349bdaebdafe3d647b775/execute' \
--header 'Content-Type: application/json' \
--data-raw '{}'
```

Or simply add a trigger to the workflow such as **HTTP Endpoint** or a **Timer**.

The result for me were 3 emails:

![image](https://user-images.githubusercontent.com/938393/123621189-3f1c6f00-d80b-11eb-9885-ce9bf1d1aa94.png)

I'm going to assume it has been fixed since the version you tried, but please reopen if you can reproduce the problem with the latest code.

Thanks!
