### ISSUE TITLE
Indexing bookmarks problem/optimization

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#1202]
Elsa 2 from NuGet....

It seems that when "Indexing bookmarks" operation is invoked that `DatabaseWorkflowProvider.TryMaterializeBlueprintAsync` is invoked for **every** workflow definition with **every** workflow version.
I have 10 (ish) workflows but each of them has 10+ versions (as I published and developed them) and this indexing starts to be "noticable" performance wise (especially since it is done often).

I really don't understand why would **all old** workflow definitions be needed for this.
Either I don't understand something about bookmark indexing (please explain :)), or there is a **big-ish** opportunity for optimization here :).

In addition I don't understand why **every** indexing operation is trying **again** and **again** to materialize workflow definitions when they haven't been changed in the meantime. Can you please comment on that?
Maybe this is another (maybe even more important) place for optimization here?

**Comment by tomy2105** [comment]
Moreover.... :( sorry I seem to be a pain in the ass today.....

For simple workflow containing just http endpoint and http response "Indexing bookmarks" operation seems to be invoked twice.
Once on the workflow start and second time on the workflow completed (actually workflow burst completed).
I understand, kind of, why you need to update on (burst completed). Because workflow might have executed http endpoint inside it, etc.....
However I don't understand the need for one on workflow start.
Mere workflow starting should be affecting bookmarks, and if they are in valid state before (which they should be if they are update at the end of previous workflow run as well as on workflow definition update).
Maybe that first could be optimized away :).

**Comment by sfmskywalker** [comment]
> It seems that when "Indexing bookmarks" operation is invoked that DatabaseWorkflowProvider.TryMaterializeBlueprintAsync is invoked for every workflow definition with every workflow version.
I have 10 (ish) workflows but each of them has 10+ versions (as I published and developed them) and this indexing starts to be "noticable" performance wise (especially since it is done often).

The `DatabaseWorkflowProvider.TryMaterializeBlueprintAsync` should not happen anymore with 2.1. The problem here was that the caching workflow registry was bypassing the cache containing workflow blueprints. This bug has been fixed.

> I really don't understand why would all old workflow definitions be needed for this.
Either I don't understand something about bookmark indexing (please explain :)), or there is a big-ish opportunity for optimization here :).

The reason ALL versions are indexed is because there may be existing workflow instances still relying on these older workflow definition versions. However, in Elsa 2.1, this should only happen for both published workflows as well as older workflow definitions **that have at least one unfinished workflow instance**.

This means that ultimately, as soon as there are no more unfinished workflow instances using an older workflow definition, only the published workflow definition should be indexed.

> Moreover.... :( sorry I seem to be a pain in the ass today.....

I'm loving that you are finding these issues 😄 Please keep'm coming!

> However I don't understand the need for one on workflow start.

This is necessary to build an in-memory registry of **workflow triggers**. For example, the **HTTP Endpoint** activity, when used as a starting point, uses the same bookmark provider to tell Elsa how to invoke this workflow. These triggers are then used by e.g. the HTTP Endpoint middleware to get all triggers (which are the same as bookmarks, but stored in-memory) to quickly select which workflow(s) to start.

That being said, indexing these triggers should only happen once during application startup and when you publish/unpublish/delete workflow definitions. Which should be the case with 2.1.

If you can, please give 2.1 preview a go to see if things are better or if you are still seeing some of these issues.

**Comment by tomy2105** [comment]
I've tried with Elsa 2.1 from code.
I can confirm that TryMaterializeBlueprintAsync isn't called either before workflow is executed or after which is good :).

I see it called on workflow publish which is expected, for the new workflow version.
However, I see it called on ALL workflow versions when new version is published, which is kind of suprissing.
However since this is not in run time, but development time, it is not important (or not nearly not important it occurring in run time).

**Comment by sfmskywalker** [comment]
Yeah it was just easier to re-index ALL blueprints instead of just the published / unpublished blueprint and it’s versions.

But it’s something that we can optimize further at some point when it becomes more of an issue.
