### ISSUE TITLE
Burst of workflow explanation

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#1204]
Elsa 2 from NuGet....

I thought that I understood what Burst of workflow, I used to think that it is part of workflow being executed until some suspended activity occurs (like Timer, Http Endpoint, .....) or untill the workflow ends.

If I have simple workflow (HTTP Endpoint -> HTTP Response) it looks (excerpt from log) ok:

	Starting activity HttpEndpoint b9609008-7f3a-4a57-9260-df6a83b70a73 for workflow 14d7a1e49d6b466780edcd7f97f50b95
	End activity HttpEndpoint b9609008-7f3a-4a57-9260-df6a83b70a73 for workflow 14d7a1e49d6b466780edcd7f97f50b95
	Starting activity WriteHttpResponse 680b7795-8996-4da9-b104-ae5779961d7c for workflow 14d7a1e49d6b466780edcd7f97f50b95
	End activity WriteHttpResponse 680b7795-8996-4da9-b104-ae5779961d7c for workflow 14d7a1e49d6b466780edcd7f97f50b95
	Burst of workflow execution completed for workflow 14d7a1e49d6b466780edcd7f97f50b95

We have one burst and it is what I expected.

However if I do 
HTTP Endpoint
For - iterate Break
      - done HTTP Response
then the log looks like:

	Starting activity HttpEndpoint b9609008-7f3a-4a57-9260-df6a83b70a73 for workflow aae941f781654460b4b8434297a7a3e1
	End activity HttpEndpoint b9609008-7f3a-4a57-9260-df6a83b70a73 for workflow aae941f781654460b4b8434297a7a3e1
	Starting activity For e828287b-abed-4eb8-9f17-6007c4cc1aef for workflow aae941f781654460b4b8434297a7a3e1
	End activity For e828287b-abed-4eb8-9f17-6007c4cc1aef for workflow aae941f781654460b4b8434297a7a3e1
	Starting activity Break 8bac099b-4dd8-4fd3-ab21-0c805d55f46d for workflow aae941f781654460b4b8434297a7a3e1
	End activity Break 8bac099b-4dd8-4fd3-ab21-0c805d55f46d for workflow aae941f781654460b4b8434297a7a3e1
	Burst of workflow execution completed for workflow aae941f781654460b4b8434297a7a3e1
	Starting activity For e828287b-abed-4eb8-9f17-6007c4cc1aef for workflow aae941f781654460b4b8434297a7a3e1
	End activity For e828287b-abed-4eb8-9f17-6007c4cc1aef for workflow aae941f781654460b4b8434297a7a3e1
	Starting activity WriteHttpResponse 680b7795-8996-4da9-b104-ae5779961d7c for workflow aae941f781654460b4b8434297a7a3e1
	End activity WriteHttpResponse 680b7795-8996-4da9-b104-ae5779961d7c for workflow aae941f781654460b4b8434297a7a3e1
	Burst of workflow execution completed for workflow aae941f781654460b4b8434297a7a3e1
 
As you can see, there are two bursts (seems like Break produces end of the burst and start of another one).
Is this intended? Why?

Moreover if I have CompositeActivity and I finish it with Finish activity then the finish also produces end of the burst.
Is this intended? Why?

This is especiall "painfull" in ligth of end of burst triggering bookmark indexing which itself might be expensive, see #1202 .

All in all could you please document and explain what burst is (when it ends) and if there is some optimization/bug I stumbled upon.... well you know what to do :)......

**Comment by sfmskywalker** [comment]
> As you can see, there are two bursts (seems like Break produces end of the burst and start of another one).
Is this intended? Why?

I actually had not anticipated that side effect when implementing the **Break** activity, but it makes sense it would act this way. What happens when **Break** executes is that it finds the first ancestor activity of type `For`, `ForEach` or `While`. All of these are **scope activities** - keep this in mind, it is important for the next part. When found, it applies a `"Break"` state to it.

Now, as soon as there are no more activities scheduled on the workflow runner's stack, it will **reschedule the current scope**, which usually is a **For**, **ForEach** or **While** activity (since the *Break** activity only really makes sense when used in combination with any of these).

These activities will check to see if their `"Break"` state is set to `true` to determine if they should continue with the next iteration or not.

The issue is that this "rescheduling of the current scope activity" is that this is done in response to the `WorkflowExecutionBurstCompleted` event. 

So when that event is fired, a new activity will be scheduled, continuing the workflow execution loop, ultimately raising yet another `WorkflowExecutionBurstCompleted` event.

I've suspected for a while now that implementing certain key aspects of the workflow runner using these events might not be the right way to go. Instead, a chain of command pattern seems more suitable. The events should be mere notifications to the application to allow for some additional, **optional** logic to execute that is application specific.

The issue you pointed out confirms this suspicion beautifully, so I will change that.

> Moreover if I have CompositeActivity and I finish it with Finish activity then the finish also produces end of the burst.
Is this intended? Why?

Same reason as the above: the `CompositeActivity` is also a **scope activity**, which is re-scheduled once there are no more scheduled activities.

> This is especiall "painfull" in ligth of end of burst triggering bookmark indexing which itself might be expensive, see #1202 .

Exactly. You figured out what I was planning to investigate after the 2.1 release. You saved me some trouble 😄 

> All in all could you please document and explain what burst is (when it ends) and if there is some optimization/bug I stumbled upon.... well you know what to do :)......

Yes, I will do both: document AND fix the bug :)

**Comment by sfmskywalker** [comment]
I created an issue for implementing workflow middleware here: #1222

**Comment by sfmskywalker** [comment]
Burst of Execution described here: https://elsa-workflows.github.io/elsa-core/docs/next/concepts/concepts-workflows#burst-of-execution
