### ISSUE TITLE
Signal execute HTTP endpoint doesn't send signal when specifying workflow instance ID.

### ISSUE THREAD

**Issue by VahidShir** [elsa-workflows/elsa-core#1208]
Steps to reproduce:
1. Create the workflow [signal receiver](https://elsa-workflows.github.io/elsa-core/docs/next/guides/guides-signaling-workflows#signal-receiver-workflow), with following activities respectively:
- Signal Received
  - Signal: signal-1
  - Scope: Instance
- HTTP Response
  - Content: Signal 1 received!
2. Get created workflow definition ID with the following HTTP endpoint:
https://localhost:5001/v1/workflow-definitions

3. Execute the workflow with the following HTTP endpoint:
https://localhost:5001/v1/workflow-definitions/{workflowDefinitionId}/execute
Now the workflow is running and it's in suspended state waiting to receive the signal.
4. Get running workflow instance ID:
https://localhost:5001/v1/workflow-instances/

5. Send signal with the following HTTP endpoint (POST):
https://localhost:5001/v1/signals/signal-1/execute
```
{
    "WorkflowInstanceId": "{workflowInstanceId}",
    "CorrelationId": null,
    "Input": null
}
```

But the signal isn't sent unless we set WorkflowInstanceId value a `null` value.

**Comment by VahidShir** [comment]
I assume (I haven't tested it yet) if we don't specify workflowInstanceId that API will send signal to all workflow instances that have that signal name.

**Comment by sfmskywalker** [comment]
Yes exactly. Or if you specify a correlation ID, only workflows blocked on the specified signal and the same correlation ID will be triggered.

**Comment by sfmskywalker** [comment]
I see now. There's a slight misunderstanding of the way **Signal Received** works.

If you follow your repro steps outlined above, **without step 3** , it will work fine.
The reason for this is that when invoking the `/v1/workflow-definitions/{workflowDefinitionId}/execute` API endpoint, you did not specify the necessary input for the Signal Received activity. Nor do you have to - this is taken care of by the `/v1/signals/signal-1/execute` endpoint.

I tried this with latest code from `master` successfully. I'll close this issue as solved, but feel free to reopen if you are still having issues with 2.1 preview / master. Thanks!

**Comment by sfmskywalker** [comment]
I forgot to discuss targeting a specific workflow instance with a signal. This works too, but not when you use the **Signal Received** as a starting activity (aka trigger). The reason for that is simple: at this point there's no actual workflow instance. I see now that you tried to create a workflow instance by executing the workflow manually using the `v1/workflow-definitions/{workflowDefinitionId}/execute` endpoint.

Signaling a workflow instance only really makes sense if you have an actual workflow instance. For example, if you had a second Signal Received activity blocking the workflow, you can target that specific workflow instance.

Having the **Signal Received** activity as a workflow trigger never requires a workflow instance because that doesn't make sense. At least, not in any of the use cases that I could think of, so do let me know if I missed something.
