### ISSUE TITLE
Custom switch activity

### ISSUE THREAD

**Issue by Juandavi1** [elsa-workflows/elsa-core#1240]
Hi guys, 

im trying to create a custom switch activity but the designer doesn't show the cases :( 

<img width="1084" alt="Captura de Pantalla 2021-07-10 a la(s) 8 27 30 p  m" src="https://user-images.githubusercontent.com/18731612/125180234-5836ff80-e1bd-11eb-9559-079bba0fefe0.png">
<img width="499" alt="Captura de Pantalla 2021-07-10 a la(s) 8 27 40 p  m" src="https://user-images.githubusercontent.com/18731612/125180236-5a995980-e1bd-11eb-8f64-c168bf5044a4.png">

**Comment by sfmskywalker** [comment]
Hi Juan,

The issue is that the designer's `switch-plugin` is only looking for **Switch** activities. This means that if you create a custom activity that uses a different activity name, such as **AnswerTree** in your case, the plugin won't recognize that it needs to interpret the `Cases` property.

I will make push a change that fixes is. Your use case is a valid one, since you're simply reusing the `Switch` UI hint, so it should be made to be supported by the designer for custom activities also.
