### ISSUE TITLE
DeclarativeCompositeActivitiesConsole sample throws exception

### ISSUE THREAD

**Issue by rzvdaniel** [elsa-workflows/elsa-core#1242]
Hi, all!

I noticed that **DeclarativeCompositeActivitiesConsole** sample triggers an error.

`InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Configuration.IConfiguration' while attempting to activate 'Elsa.Scripting.Liquid.Handlers.ConfigureLiquidEngine'.`

![image](https://user-images.githubusercontent.com/1128179/125192665-f6b87480-e240-11eb-8d1d-f02233053e37.png)

**Steps to reproduce:**
1. Open Elsa solution in Visual Studio
2. Make **DeclarativeCompositeActivitiesConsole** your startup project
3. Run sample project in **Debug** mode

**Expected result:**
Console messages are being displayed on the screen

**Actual result:**
The above exception is thrown.

P.S.
I'm using same pattern as in the sample to run workflows from code behind and I have the same issue.

**Comment by jdevillard** [comment]
Hello ,

seems that recent changes on the Startup loading  has break something on console app because DI for IConfiguration is not loaded for console app. (This is not visible when using Host because I think the HostBuilder load the configuration DI itself)

if you add the configuration ,it will work, but I think it must be include by default

```
 IConfiguration configuration = new Microsoft.Extensions.Configuration.ConfigurationBuilder()
              .AddJsonFile("appsettings.json", true, true)
              .Build();
            
            // Create a service container with Elsa services.
            var services = new ServiceCollection()

                .AddElsa(options => options
                .AddConsoleActivities())
                .AddSingleton<IConfiguration>(configuration)
                .BuildServiceProvider();

```

**Comment by rzvdaniel** [comment]
Hi, @jdevillard !

Thank you very much for your answer, let me give it a try!

I agree that it doesn't look natural to do perform such a configuration outside Elsa core, and I think the change should happen at a lower level.

Best!
Razvan

**Comment by sfmskywalker** [comment]
@jdevillard is right. The issue was introduced when the `ConfigureLiquidEngine` class was updated to receive `IConfiguration` as a service dependency. When using a console project, clearly this is an issue.

Not sure yet what the best way might be to fix this without requiring the Console app developer to register a configuration object themselves, but I will do some research.

**Comment by sfmskywalker** [comment]
I pushed an update that will register `IConfiguration` if this service is not already present such as in the case when creating console apps.

**Comment by rzvdaniel** [comment]
Thank you, Spike!

**DeclarativeCompositeActivitiesConsole** sample was broken, but also a desktop workflow runner I was playing with.

I'll give the sample and my work a try with latest changes.

Have a great day!
Razvan

**Comment by rzvdaniel** [comment]
The sample is working fine!

Thank you for the fix!

Best!
Razvan
