### ISSUE TITLE
Fork with loop causing stack overflow

### ISSUE THREAD

**Issue by hschreeck** [elsa-workflows/elsa-core#1301]
As described here #1300 there seems to be an issue with the fork activity when it is called as part of a "loop" within a workflow. Doing so leads to a stack overflow.
I encountered this issue with elsa version 2.0.0.159

**Comment by sfmskywalker** [comment]
It looks like that either this issue was resolved after the initial 2.0.0.159 release or I can't reproduce it somehow. When I try your workflow, it happily reports `"Timeout 1 done!" every 10 seconds when I start the workflow. I'm of course testing with the latest version of the source code in the master branch.

A couple of things:

1. Can you try with the latest prerelease version from MyGet? 
2. Alternatively, is it possible for you to send me a minimalist project that reproduces the issue so I can investigate?

**Comment by hschreeck** [comment]
Ok, that's strange. I upgraded to v2.1.1.463 to see if this solves my issue but instead I got another problem now :(
I cannot build my project because my WebApi Startup class collides with the namespace "Elsa.Services.Startup". The error code is CA1724.
I am a bit confused to be honest. Is there an easy way for me to fix this?

**Comment by sfmskywalker** [comment]
Great! I'm glad to hear you were able to resolve it.

I'll be closing this issue, but feel free to create a new one if you run into any other difficulties.
