### ISSUE TITLE
Extend the Data field of WorkflowExecutionLogRecord

### ISSUE THREAD

**Issue by Rafael94** [elsa-workflows/elsa-core#1367]
Hi,

it is possible to fill the `data` field in `WorkflowExecutionLogRecord` with own data.

For example, for my own activity I would like to store the user name that triggered the activity.

**Comment by sfmskywalker** [comment]
Not as things are right now, but we should change it so that you can do it. The reason you can't add custom data right now is because the activities themselves don't write to the execution log directly - it is handled by the `WriteWorkflowExecutionLog` notification handler.

I'm not sure yet what would be a good way to restructure this such that an activity gets to "enrich" the entry being written, so I am open to ideas.

**Comment by Rafael94** [comment]
I have not looked at it in detail. Could `IDictionary<string, object?> Data { get; set; }` be accessed? 

If not everything should be stored, the key could start with a specific character. For example `$User`.

**Comment by sfmskywalker** [comment]
Maybe, but I think it would be better if there's an official API to achieve this.

**Comment by sfmskywalker** [comment]
Displaying the activity data on the workflow journal should be in-scope.
