### ISSUE TITLE
How to check error detail in workflow designer?

### ISSUE THREAD

**Issue by rairafaqatali** [elsa-workflows/elsa-core#1423]
@sfmskywalker 
When I execute the workflow sometimes it throws exceptions with the below format:
{
    "errorMessage": "Workflow faulted at 2021-08-23T13:39:47Z with error: Unexpected end of expression.",
    "workflow": {
        "name": null,
        "version": 1,
        "instanceId": "4b546ed1702147e2907b950192ce31e7"
    }
}
Can you guide me, how can I check the error detail? Where it logs the complete error stack

**Comment by Andrei-NZ** [comment]
I also found that detailed error reporting in the designer is a major missing functionality. This is probably not that important for seasoned developers, but for anyone just starting with the workflows, this may become a major barrier when using the designer to explore Elsa's functionality. 

Maybe a simple article in documentation section on where to find error details (IDE console if running from an IDE, logs location on the Docker image) will cover this for a start, but a detailed error logging which can be investigated from the front-end would be the icing on the cake :)

**Comment by sfmskywalker** [comment]
>  a detailed error logging which can be investigated from the front-end would be the icing on the cake :)

That's actually brilliant :)
We should stream logs to the front end. Could even be correlated to specific workflow instances if the server associates logging statements with workflow instances in contexts. Even if we do that later, at the very least being able to review the logs from the front-end would be tremendously helpful.

One thing to be careful about maybe is to not build our own version of Kibana - perhaps there are existing components we might use. Because once you start seeing logs in the front-end, you might want to search through them.

**Comment by sfmskywalker** [comment]
I pushed a change that now displays the full inner-exception hierarchy, which I think closes this issue. I will create a separate issue to track the development of the front-end logging console feature.
