### ISSUE TITLE
when property type is enum ,conversion error

### ISSUE THREAD

**Issue by Nokecy** [elsa-workflows/elsa-core#1515]
https://github.com/elsa-workflows/elsa-core/blob/5050e26db0505447293e847dc42d29bc50ad98bf/src/core/Elsa.Abstractions/Services/Workflows/ActivityPropertyProviders.cs#L72

**Comment by sfmskywalker** [comment]
I just tried this with a custom activity and a property using an enum type, but this code works fine for me. Perhaps you can provide me with detailed repro steps and/or a project I can look at?

**Comment by Nokecy** [comment]
when call  GetActivityPropertyAsync  method   like 

`WorkflowExecutionContext.GetActivityPropertyAsync<SingleUserTask, ActorSelectionMode>(parentActivityId, x => x.ActorSelectionMode)!;`

@sfmskywalker

**Comment by Nokecy** [comment]
https://github.com/Nokecy/ElsaQuickstarts.ConsoleApp.HelloWorld  @sfmskywalker

**Comment by sfmskywalker** [comment]
I'm getting a 404 response when I try to access your link. Perhaps its a private repo? If so, maybe download it as a zip and send it to my email if you want to keep it private.

**Comment by Nokecy** [comment]
Sorry, my fault, now it is public @sfmskywalker

**Comment by sfmskywalker** [comment]
No worries, thanks for the repro 👍🏻 

I was able to see the issue and it is caused by the fact that when the workflow instance gets persisted in the DB, enum values get stored as an integer (Int64), which cannot be cast to the enum.

To fix this, I will push an update that instead of casting the value back to the target type. it will convert it.

**Comment by Nokecy** [comment]
thanks
