### ISSUE TITLE
Timer problems

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#1527]
I use Timer Activity with Elsa 2.0, Hangfire and hangfire data stored in Postgres.

Timer activity is set to continue execution after 5 seconds.

However on load test on some of the systems (not all) I see it executed after 10, 15 or even 20 seconds.

Could you please point in right direction what to investigate?
What configuration/properties have influence over timer execution?
One more question, is there a limit to how many workflow instances trigered to continue execution by timer can be simultaneously?

Thanks for the help and great project :).

**Comment by sfmskywalker** [comment]
I ran into the exact same issue. 

The issue is that Hangfire uses a polling interval of I believe 15 seconds by default. If you configure this to e.g. 1 seconds, you should start seeing improved results.

Example:

```csharp
services.AddHangfireServer((sp, options) =>
{
    options.SchedulePollingInterval = TimeSpan.FromSeconds(1);
    options.ConfigureForElsaDispatchers(sp);
})
```

See also this [SO post](https://stackoverflow.com/questions/63788069/what-is-the-minimum-time-for-hangfire-jobs).

**Comment by tomy2105** [comment]
Hm... will try.
Do you know if and what consequence does following property have?

      options.WorkerCount=3

In addition is `ConfigureForElsaDispatchers` done something behind the scene? I used Elsa 2.0 and used `AddHangfireTemporalActivities` only.

**Comment by sfmskywalker** [comment]
Sure, Setting the WorkerCount controls the number of workers that Hangfire will initialize to process work. Each worker runs on its own thread.

More information about this setting can be found [here](https://docs.hangfire.io/en/latest/background-processing/configuring-degree-of-parallelism.html).

The `ConfigureForElsaDispatchers` method is optional. When you use it, it configures Elsa to use Hangfire to publish messages instead of using Rebus. It is unrelated to timer activities.

**Comment by tomy2105** [comment]
Indeed, however the keyword here is "work".

So my question is, in Elsa case, what is "work" as far as Hangfire background processing thread is concerned?
Is it **resuming and completion execution of the workflow** from the Timer to next Timer (or Finish)?
Or is it **just signaling** "somebody" else (another thread, instance, ....) that workflow needs to be resumed?

In former case the `WorkerCount` will effectively determine how many simultaneous workflows (after Timer or other scheduling) instance can do while in latter the influence of this parameter will be much less noticeable (how many workflows can be simultaneously signaled to resume on another thread/instance).
So which is it? Or maybe there is a third option I've overlooked :)?

**Comment by sfmskywalker** [comment]
Excellent question.

Elsa has the following Hangfire jobs defined (a job is what gets done as work by a worker):

- `RunHangfireWorkflowDefinitionJob`: dispatches a `ExecuteWorkflowDefinitionRequest` (which is not the same as actually handling the `ExecuteWorkflowDefinitionRequest`). This job gets scheduled by the various timer activities.
- `RunHangfireWorkflowInstanceJob`: similar to the previous job, except that this one dispatches workflow instance execution requests.

The above two jobs are light-weight (they execute quickly) since all they do is dispatch some work. The "dispatching" is handled by an implementation of `IWorkflowInstanceDispatcher` and `IWorkflowDefinitionDispatcher`, both of which are abstractions that represent a service that can schedule work. There are 3 implementations of these two interfaces:

- `QueuingWorkflowDispatcher`: this is registered by default, and uses Rebus to simply enqueue the `ExecuteWorkflowInstanceRequest` and `ExecuteWorkflowDefinitionRequest` objects. These messages are then processed by a queue worker (`ExecuteWorkflowDefinitionRequestConsumer` and `ExecuteWorkflowInstanceRequestConsumer`).
- `HangfireWorkflowDispatcher`: this gets registered when you call `ConfigureForElsaDispatchers`. Instead of using Rebus, you now leverage Hangfire to process work, which is the act of running a workflow. See `WorkflowDefinitionJob` and `WorkflowInstanceJob`.
- `GrainWorkflowDispatcher`: this gets registered when you call `UseOrleansDispatchers`. This will then handle work from an Orleans grain. I haven't used this in practice really. It's more of an initial attempt to get Elsa to run in a multi-node cluster taking advantage of the Orleans programming model. Consider it experimental.

So that's what "work" means: it could be scheduling a workflow execution instruction (this is work scheduled by timer activities), and actually executing workflows.

**Comment by sfmskywalker** [comment]
> Is it resuming and completion execution of the workflow from the Timer to next Timer (or Finish)?
Or is it just signaling "somebody" else (another thread, instance, ....) that workflow needs to be resumed?

As I hopefully was able to clarify in my previous response, it is the latter: timer activities schedule work to execute in the future. This work then simply schedules real work to be done using the two dispatcher services. What "dispatch" means in practice depends on what implementation is registered. In the case of Hangfire dispatcher, it simply schedules a workflow execution instruction to start or resume a workflow in the form of a Hangfire job.

**Comment by sfmskywalker** [comment]
> In former case the WorkerCount will effectively determine how many simultaneous workflows (after Timer or other scheduling) instance can do while in latter the influence of this parameter will be much less noticeable (how many workflows can be simultaneously signaled to resume on another thread/instance).
So which is it? Or maybe there is a third option I've overlooked :)?

So it is the latter :)

WorkerCount allows you to specify how many jobs can run simultaneously. The higher the number, the more Hangfire jobs get processed at the same time, the more workflows execute at the same time, the higher workflow throughput. And if you scale out (adding more nodes to the cluster or sliding the nodes count on an Azure App Service resource), you increase throughput even further.
