### ISSUE TITLE
IActivityTypeProvider not found in assembly "Elsa.Abstractions" 

### ISSUE THREAD

**Issue by Alhammoud** [elsa-workflows/elsa-core#1592]
After updating all Elsa's nuget packages to version 2.3.0.0 I got this error when I started to build app.
![image](https://user-images.githubusercontent.com/45689826/135465834-1fb06bfc-1cc4-4ede-810f-5a375f3a59a6.png)
![image](https://user-images.githubusercontent.com/45689826/135467381-e3c3b7f6-d33d-49ca-9bc9-5ff6f6751869.png)
Please help..!

**Comment by sfmskywalker** [comment]
In 100% of the cases where I have seen that exact error, it was because of one of two things:

1. Not all Elsa packages were of the same version (across all projects).
2. The build output wasn't properly rebuilt (this seems to happen from time to time with .NET).

Double-check #1, and do a full clean of your build outputs (delete bin folders) and try again.

If you are absolutely sure all your packages are up-to-date (using the same version), then please feel free to send me a (stripped down) copy of your solution that demonstrates the issue and I will take a look.
