### ISSUE TITLE
Persist on every activity

### ISSUE THREAD

**Issue by terry-delph** [elsa-workflows/elsa-core#188]
Hi @sfmskywalker,

I am reviewing whether this library is suitable for our needs.
We have long running workflows but we would like to be able to persist every activity so that if a workflow was to stop abruptly it can resume where it last persisted automatically, which is what [Workflow-Core](https://github.com/danielgerlag/workflow-core) library does.

From my initial checks it only persists when it reaches a halted activity and Timer activities.
It then resumes using the TimersHostedService or a trigger on a workflow.

Is there any way to persist each activity as it reaches it or has this not been included in the design?

Many thanks.

**Comment by sfmskywalker** [comment]
Hi @terry-delph,

Your initial checks check out: if a workflow were to stop abruptly, it would need the same stimuli to trigger the workflow from the last blocking activity.

However, that doesn’t mean it’s excluded from the design vision.

I do think it should be an optional feature, because there are other users that execute workflows in large volumes and need to squeeze out maximum performance, and do not wish to persist state at every activity.

So I’m thinking about the following:

1. We add a workflow setting that allows the workflow developer to configure whether the workflow should persist at every step of the way.

2. We add a common activity setting to allow the workflow developer to configure wether to persist the workflow at critical sections of the workflow.

3. We add a “Persist” activity that the workflow developer can add to the workflow to control at which points the workflow needs to be persisted. This would be an alternative option to #2, and perhaps more in line with what WF does.

I don’t know what Workflow Core does in this regard, but I’ll check it out.

Let me know if you have alternative and or additional suggestions.

Speaking of Workflow Core, I’d be very interested in understanding what would be a key differentiator to chose Elsa vs Workflow Core (and vice versa).

**Comment by terry-delph** [comment]
Hi @sfmskywalker,

Thanks for the response.

This feature would make it an incredible addition to the engine.

Option 1 could be a global setting for the workflow so that it does not need to be defined in each activity.
Option 2 would seem a better option than 3 as it would be a more compact workflow rather than padded out with extra activities. But, if going with option 3, an activity could extend the "Persist" activity if that was an option.

Some activities are unlikely to support persistence, such as the ReceiveHttpRequest and WriteHttpRequest due to relying on a HttpContext.

Being able to persist what we need for different scenarios would be the perfect solution for speed and for those that require very specific persistence.

From my perspective and needs the differences are currently:

### ELSA

*Lists not exhaustive.

**Pros:**
- Has a very flexible way of defining Activities 
- Control Flow (IfElse, Switch, etc) are also activities, so it will be easy to create further controls, rather than having to wait for the core library to change (WF-Core con)
- Describing properties that are used for the designer is a huge benefit and naming of activities
- Defining variables is easy and the use of scripting engine (JavaScript) will allow business rules and more flexibility of advanced conditions for flow of logic
- Obtaining variables from named steps is a delight as it makes it much cleaner than having to store them in a master state class (WF-Core con)

**Cons:**
- Not able to persist at every activity
- Not able to resume from a halted activity automatically if workflow abruptly ended e.g. from server outage
- Not able to do Sagas, but likely this can be a new control flow that can be built in
- Distributed workflows with queuing and locking not available currently (in the pipeline for V2)

### WF-Core

*Lists not exhaustive.

**Pros:**
- Has Saga functionality
- Has basic Error handling so step can be retried or rolled back (Saga), or workflow termination
- Persists at every step
- Has distributed workflows and queuing providers

**Cons:**
- Not able to extend the control flow steps easily
- Clunky way of doing IfElse and Switch
- Workflow state must be defined in a master class rather than pull data out of each step as required
- No designer

**Comment by sfmskywalker** [comment]
That's very valuable input, thanks for that!

I'll put more thought into the exact details, but I will make this feature a roadmap item for 2.0. Automatic persistence & resumption is a must-have.

**Comment by terry-delph** [comment]
That sounds great!

Do you have any suggested workarounds in the mean time to persist each activity?

I was thinking of something along the lines of...
Create a base persisted activity type that adds a halt then derive new activities from that when I need it to persist.
Then implement something similar to TimersHostedService that I can trigger on a Activity that is of a persisted type to resume them all.

**Comment by sfmskywalker** [comment]
I think we can make it even simpler than that: since activity's return an `ActivityExecutionResult`, we could introduce a new derivative called `PersistResult`, which instructs the workflow runner to persist the workflow instance. There would also be a new `CombinedResult` so that activities can return multiple results, such as an `OutcomeResult` and a `PersistResult`.

That then allows you to at least cause the workflow instance to be persisted **after** an activity executes. But we'd probably also want the workflow instance to be persisted right after an activity is scheduled for execution. What I could do is publish a message called e.g. `ActivityScheduled`. Your application code could listen for that message and persist the workflow instance.

Similary, there could be `ActivityExecuting` and `ActivityExecuted` messages, in which case a `PersistResult` might not be necessary if you persist the workflow when handling these messages as well.

These things can be done before the start of the upcoming week.

**Comment by terry-delph** [comment]
Thanks @sfmskywalker.

Which mechanism would be used to resume the workflows that have abruptly stopped, that have been persisted along the way?

I think because there could be shared activity libraries from the community in nuget packages, and the core activities built into Elsa, the abstract ActivityBase class should have the "Persist" setting, so that when designing the workflow, it is up to the developer to either have a Global Persist option for the entire workflow which would take preference, or specific points in the workflow.
That way in the designer, you could tick a box for global, or for every activity that needs to be persisted.

**Comment by sfmskywalker** [comment]
I'm thinking of a `StartupTask` that queries all workflow instances that are in the `Executing` status, which would be an indication that they have not completed a run-cycle. If they did, the status would be `Halted` or `Finished` (that is, this would be the desired implementation - right now `Executing` means `Halted` - a bit confusing).

On second thought, your suggestion of the `Persist` setting makes more sense than my suggestion to return a `PersistResult`, because your suggestion gives control to the user designing the workflow, which seems preferable.

**Comment by terry-delph** [comment]
Hi @sfmskywalker,

Forward planning here, and wondering if there was any movement on this feature?

I am looking to start building workflows in the new year and need to determine what features will be available at that point and if I should make an attempt or assist with implementing missing features myself.

Thanks 👍

**Comment by sfmskywalker** [comment]
Hi @terry-delph , no movement beyond our discussion so far. However I'll move this functionality up the backlog, which is influenced by user's needs such as yours. I can't promise anything, but I expect this feature to land before the end of Q1 as part of 2.0. The develop branch will contain these bits probably sometime in January.

**Comment by sfmskywalker** [comment]
This feature is now part of `feature/elsa-2.0`, to be merged into develop sometime in Q1.

**Comment by terry-delph** [comment]
That is Awesome @sfmskywalker !

I had a read through the commits for the feature.
Is the persistence designed to be global per workflow only at this stage, or turn on/off per activity?

Thanks!

**Comment by sfmskywalker** [comment]
Hi @terry-delph, persistence is not yet configurable per activity at this point, which I consider an enhancement. But I'm glad you reminded me. I'll reopen this ticket. Thanks!
