### ISSUE TITLE
What is the means of DefinitionId in WorkflowDefinitionVersion?  

### ISSUE THREAD

**Issue by LeePepe** [elsa-workflows/elsa-core#189]
What is the means of DefinitionId in WorkflowDefinitionVersion?  And What is the different between Id and DefinitionId？

In my project, I want to get workflow by properties, like AppId. How can I do that?

**Comment by LeePepe** [comment]
Maybe add the 'Tags' properties into WorkflowDefinitionVersion. And others can filter WorkflowDefinitionVersion by Tags?

**Comment by SipkeSchoorstraRTL** [comment]
The `DefinitionId` represents a logical identity for a `WorkflowDefinition` - but because a WorkflowDefinition does not have any intrinsice values of its own other than an identifier, this model does not exist. Workflow definitions are versioned, which is why there is an actual `WorkflowDefinitionVersion` model. Its `Id` property represents the identity of a specific workflow definition **version**, and its `DefinitionId` represents the identity of the workflow definition itself (despite the fact that there's no physical record of the workflow definition).

So when new versions of a workflow definition are published, new `WorkflowDefinitionVersion` records are created, each of them having its own unique ID, but they will all share the same `DefinitionId`.

If at some point it turns out we do need to hold some non-versionable information about a workflow definition, we will introduce an actual `WorkflowDefinition` model. So far, there was no need for it.

**Comment by SipkeSchoorstraRTL** [comment]
Can you elaborate a bit on some of the use cases for a `Tag` property on `WorkflowDefinitionVersion`? I;d like to understand more about this.

**Comment by sfmskywalker** [comment]
The `DefinitionId` represents a logical identity for a `WorkflowDefinition` - but because a WorkflowDefinition does not have any intrinsice values of its own other than an identifier, this model does not exist. Workflow definitions are versioned, which is why there is an actual `WorkflowDefinitionVersion` model. Its `Id` property represents the identity of a specific workflow definition **version**, and its `DefinitionId` represents the identity of the workflow definition itself (despite the fact that there's no physical record of the workflow definition).

So when new versions of a workflow definition are published, new `WorkflowDefinitionVersion` records are created, each of them having its own unique ID, but they will all share the same `DefinitionId`.

If at some point it turns out we do need to hold some non-versionable information about a workflow definition, we will introduce an actual `WorkflowDefinition` model. So far, there was no need for it.

**Comment by sfmskywalker** [comment]
Can you elaborate a bit on some of the use cases for a `Tag` property on `WorkflowDefinitionVersion`? I'd like to understand more about this.

**Comment by LeePepe** [comment]
In my project, I need a property `AppId` to classify workflows for different purpose. And Maybe need add other information for other category. For example, some workflow is for A group and some for B. But maybe some workflow for email purpose and some for phone call. So for the first example, it can use `AppId`. And for the second example, maybe need the Tag of `email` and the Tag of `phone call`.

**Comment by LeePepe** [comment]
And some suggestion, I was using WF for my project. I use `AppId`, `Name`, `Version` to represents different workflow. And for DB design, I use a MD5 of three properties to check duplicate workflow.

That's my design. Hope it is helpful.

**Comment by sfmskywalker** [comment]
Thank you for the detailed explanation, that clarifies a lot. I think it indeed makes sense to add a `Tag` property to store application-specific values. Let's get it added. Meanwhile, I'll be thinking if there's an elegant way where one could easily extend a workflow with additional parts, similar to the way Orchard Core (in concept at least) works.
