### ISSUE TITLE
Add MySql support for EntityFrameworkCore

### ISSUE THREAD

**Issue by terry-delph** [elsa-workflows/elsa-core#222]
ELSA currently supports EntityFrameworkCore for the following databases:

- SqlServer
- Sqllite
- PostgreSql

I would like to use a MySql database for persistence.
This can use the Pomelo provider: [https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql)

I am able to begin working on this now.
I want to work with v2 as I intend to use the new features from it such as persistence at all stages.

@sfmskywalker 
Which starting branch would be best to branch from?
- Develop or v2?

What is your current policy for contributing?
- Fork and PR to your repo?

Many thanks!

**Comment by sfmskywalker** [comment]
Great!

Question: is Pomelo's implementation the same as [MySql.Data.EntityFrameworkCore](https://www.nuget.org/packages/MySql.Data.EntityFrameworkCore)? If not, would there be any reasons to use one instead of the other?

To start, I recommend starting with the `develop` branch. The v2 branch is very unstable at the moment and will soon contain many breaking changes. Once that happens, I'll merge develop into v2 and fix all the things. 

Fork + PR is the way to contribute.

Thanks!

**Comment by terry-delph** [comment]
From my research Pomelo is more widely used and updated faster, and apparently works better.
Pomelo is compatible with EFCore 3.1 at this moment in time where as MySql is only at 2.1.

List of providers and versions:
- https://docs.microsoft.com/en-us/ef/core/providers/?tabs=dotnet-core-cli

**Comment by sfmskywalker** [comment]
Pomelo it is then 👌🏻
