### ISSUE TITLE
[bug] Receiving a signal does not work unless SignalReceived is the first activity.

### ISSUE THREAD

**Issue by Invenisso** [elsa-workflows/elsa-core#2430]
**Steps to reproduce:**

1. Go to Elsa.Samples.SignalingConsole example.
2. Open SignalReceiverWorkflow.cs
3. Add some activity before SignalReceived, for example WriteLine:

![image](https://user-images.githubusercontent.com/57659054/139474285-8a3348e2-5ef5-4cef-a75b-efff2791f1f9.png)

4. Compile and run example - it doesn't work anymore.

**Comment by sfmskywalker** [comment]
It makes sense that it wouldn't work anymore, because the `SignalReceiverWorkflow` no longer has a trigger that waits for the signal. You would now first have to manually execute that workflow, after which it will become blocked on the `SignalReceived` activity. When it is blocked on that activity, it will resume execution once the signal is sent.

The key take away here is that workflows don't get triggered just by having a trigger anywhere in the workflow (like in your example, where the "Signal Received" activity is the second activity).

If that were the case, then imagine what would happen if you have a workflow containing all sorts of triggers at various places, like timers, signals and service bus messages - the workflow would now be triggered whenever any timer ticks, a signal is sent or a message bus is received, regardless of the current "position" of the workflow. It would be complete mayhem :)

I'm closing this issue as a non-issue, but feel free to continue the discussion as you like.

**Comment by Invenisso** [comment]
Thanks for the answer. I have analyzed the source code in more depth and I understand now how it works.
