### ISSUE TITLE
DashBoard  Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by ILAOHE** [elsa-workflows/elsa-core#2431]
![image](https://user-images.githubusercontent.com/20391853/139520401-77ab31b6-46a3-4ed7-8e40-ff9658eeb482.png)
![image](https://user-images.githubusercontent.com/20391853/139520419-c1ca9be5-3a1f-4f0a-b117-9399a40ac729.png)

**Comment by sfmskywalker** [comment]
Although it should work fine out of the box with Elsa 2.3.0, can you try with Elsa 2.4.0 prerelease packages (available from MyGet)?

If yes, then please send your solution of you can so I can investigate. When I try myself right now, I don't get this issue.

**Comment by harshad-azilen** [comment]
Hi @ILAOHE , just to know is this issue was resolved. I too facing same issue and not able to find solution. If its working for you then please advice.

For me scenario is, we are using Mongo/PostgreSQL persistence provider and workflow definition and workflow instances get stored into database. Once we click on Workflow Instance table then facing same issue.

I suspect there could be an issue with SetVailable method when we storing concrete type into variable. In below line of code i am trying to set order object to variable "OrderDetail". Once workflow initiated then its storing this data into JSON structure. Once Workflow API will try to get data then facing same issue.

**activityExecutionContext.SetVariable(WorkFlowVariables.OrderDetail, order)**

You can refer issue at https://github.com/elsa-workflows/elsa-core/issues/2552
