### ISSUE TITLE
 'DbContextOptionsBuilder' does not contain a definition for 'UseEntityFrameworkPersistence' 

### ISSUE THREAD

**Issue by cbcye** [elsa-workflows/elsa-core#2564]
When i build the sample, i got the following issue, any one could help?

Error | CS1929 | 'DbContextOptionsBuilder' does not contain a definition for 'UseEntityFrameworkPersistence' and the best extension method overload 'ServiceCollectionExtensions.UseEntityFrameworkPersistence(ElsaOptionsBuilder, Action<DbContextOptionsBuilder>, bool)' requires a receiver of type 'ElsaOptionsBuilder' | DocumentManagement.Workflows | D:\Projects\DocumentManagement\src\DocumentManagement.Workflows\Extensions\ServiceCollectionExtensions.cs | 23

**Comment by sfmskywalker** [comment]
Can you show us your code, including imported namespaces?

**Comment by sfmskywalker** [comment]
Wait, I see now that you are referring to a sample project. I will check.

**Comment by sfmskywalker** [comment]
I just tried to build that sample project, but I did not get any compilation issues.

I did notice however that the solution was referencing Elsa core library projects. Not sure if that causes the error you are seeing, but I pushed an update that you can maybe give a try.

**Comment by cbcye** [comment]
Thanks, I have downloaded your new code, it is running now.

**Comment by cbcye** [comment]
in your sample, i see there have the ELSA server link, but after I running the sample and try access localhost:7000 , it seems have not working ( have not this endpoint)
"Elsa": {
    "Server": {
      "BaseUrl": "http://localhost:7000",
      "BasePath": "/workflows"
    },

**Comment by sfmskywalker** [comment]
What URL is your application running on?

**Comment by cbcye** [comment]
my application url configure is : "applicationUrl": "https://localhost:6001;http://localhost:6000

**Comment by sfmskywalker** [comment]
Oh I see. No, that sample project only acts as an Elsa Workflow Server, but does not host the dashboard itself. You have a couple of options to use the dashboard:

1. Run it as a Docker container: `docker run -t -i -e ELSA__SERVER__BASEADDRESS='https://localhost:11000' -p 13000:80 elsaworkflows/elsa-dashboard:latest` (make sure to point to the correct server URL)
2. Create a separate ASP.NET application that hosts the dashboard
3. Update the sample project to host the dashboard on a sub-path (since it's already serving existing UI).

Option 1 is the easiest.
