### ISSUE TITLE
Strange journal duration times

### ISSUE THREAD

**Issue by omid-tansaz** [elsa-workflows/elsa-core#2568]
It seems that times printed in journal are not correct, in the example below, the REST call takes around 1.5 s (now printed as 5 ms), however, that amount is shown at write-line, where we expect few ms duration.

![Screenshot 2021-12-09 at 12 47 41](https://user-images.githubusercontent.com/28906715/145394289-28c29358-9b63-44a4-aa02-0ff97307cb5f.png)

**Comment by sfmskywalker** [comment]
As it turns out, the logic to calculate the delta time between two activities is incorrect.

Currently, the journal takes all **Executed** entries, takes their timestamps and uses it to show the delta between each pair.
What should be done, however, is take each pair of **Executing** and **Executed** entry for each activity, and display the delta between those two entries for a given activity.
