### ISSUE TITLE
Workflow Dashboard doesn't list workflows that is created by code where in memory store is used.

### ISSUE THREAD

**Issue by SherifRefaat** [elsa-workflows/elsa-core#258]
Here is my setup

```
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllersWithViews().AddNewtonsoftJson();

            services.AddActivity<SendCandidateMessage>();
            services.AddActivity<GenerateCandidateId>();
            services.AddActivity<ApproveCandidate>();

            services
                .AddElsa()
                .AddWorkflow<RecruitmentWorkflow>()
                .AddElsaDashboard();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }
            app.UseStaticFiles();

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");
            });
        }
```

```
    public class RecruitmentWorkflow : IWorkflow
    {
        public void Build(IWorkflowBuilder builder)
        {
            builder
                .StartWith<SendCandidateMessage>(s => 
                { 
                    s.WelcomeMessage = "Hello, wait further response."; 
                })

                .Then<GenerateCandidateId>()
                
                .Then<SendCandidateMessage>(s => {
                    s.WelcomeMessage = "Your Id is generated.";
                })
                
                .Then<ApproveCandidate>()
                .Then<ApproveCandidate>();
        }
    }
```

What is worth mentioning is that the custom activities that I created, can be found in the editor screen but not the workflow that I created.

Thanks.

**Comment by sfmskywalker** [comment]
Correct. The dashboard lists workflow definitions by reading them from the `IWorkflowDefinitionStore`, which does not include workflows defined in code.

We could change this such that the dashboard reads workflows not from the store, but from `IWorkflowRegistry`, which itself gets workflow definitions from both the ones defined in code as well as the store.

However, the dashboard would need to support the following:

* The workflow designer for coded workflows would have to be read-only, since it cannot update C# code.
* The workflow designer for coded workflows would need an auto-layout algorithm to know where to position individual activity nodes visually, since coded workflows do not carry any coordinates for each activity. Although we could add support for this, I don't think it makes sense to expect developers to enter x and y coordinates from C# coded workflows. The auto-layout feature on the other hand might make sense.
* The dashboard will have to be updated such that it "knows" what workflow definitions come from the store, and what definitions are defined by code. The UI should behave appropriately, e.g. it should not allow the user to change the name and description of the workflow definition, because it will not be able to update the C# workflow implementation.

I hope this gives you a reasonable explanation of why you do not (currently) see your coded workflow in the dashboard. However, I do recognize that we need to change this. One primary reason of course being that you should be able to monitor workflow instances of a given workflow defined in code. And with the auto-layout feature, we could even visually show the workflow.

My plan is to provide support for all of this as part of Elsa 2.0. Maybe not as part of the initial release, but e.g. Elsa 2.1.

**Comment by SherifRefaat** [comment]
Thank you for your response. I understand now.
