### ISSUE TITLE
Workflow definition variables are not handled as native json in java scripts and require parsing.

### ISSUE THREAD

**Issue by cristinamudura** [elsa-workflows/elsa-core#2668]
Workflow definition variables are not treated as json objects and to be able to use their values we need to parse.

This scenario can be reproduced with variables of array types. 

So, given the following example,
<img width="896" alt="Screenshot 2022-01-14 at 14 41 40" src="https://user-images.githubusercontent.com/80831066/149524665-dff0ff39-b94f-444e-a05e-4fe050bac064.png">

and trying to use the Demo variable

**Comment by sfmskywalker** [comment]
To add:

- The JSON string representing the workflow variables is deserialized into a Newtonsoft Json (one of `JObject/JArray/JToken`)
- Jint doesn't interpret Newtonsoft objects, which means they are not treated as JSON objects in Jint. Which means one cannot use standard JS functionality to handle these objects like you would normally be able to do with real JSON objects.
- Jint **does** interpret `ExpandoObject` as JSON objects. 
- This means that we should deserialize the Workflow Variables JSON string into an ExpandoObject, instead of a Newtonsoft JObject.
- To do so, one can take advantage of the `$type` field to specify the .NET type to deserialize into. If the user wants to treat the workflow variables as JavaScript JSON objects, they shiuld therefore specify `ExpandoObject` as the type.
- One idea is to somehow configure the JSON serializer to always deserialize WF variables into ExpandoObjects, but at the same time, some users might want to use other .NET types to deserialize specific variables into.

Technically, we don't have to do anything to allow the user to use WF variables as "true" JSON objects by specifying their types as `ExpandoObject`. However, the UX is not ideal. For example, the user would have to type the following:

```json
{
   "Demo": {
      "$type": "System.Object[], System.Private.CoreLib",
      "$values": [{
         "$type": "System.Dynamic.ExpandoObject, System.Linq.Expressions",
         "firstItem": 1
         },{
         "$type": "System.Dynamic.ExpandoObject, System.Linq.Expressions",
         "secondItem": 100
         }
      ]
   }
}
```

Which is quite horrific to have to type in.

What follows are some suggestions to consider & discuss:

**Idea 1. Different UI**

Ideally, the user doesn't have to type in any JSON in the first place, but can use a simple UI similar to the **Switch** activity's UI to add variables and select their types from a dropdown list. This list would then include a .NET type.

The tricky part will be allowing users to enter complex objects and arrays.

With complex objects, the user should still use simple JSON syntax as shown in @cristinamudura 's screenshot, but the system would now be able to deserialize each variable into the desired target type (again, which might be ExpandoObject or a custom type).

With arrays, the variable input editor would have to switch from a JSON code editor to again a simple UI that's basically a recursion of the main variable editor proposed here.

**Idea 2. Custom DSL**

A completely alternative solution might be to introduce a very simple DSL to declare workflow variables, also allowing the system to have complete control over how to deserialize the variables.

An example could be as follows:

```
// Declare a variable of type JSON, which means its value should be deserialized into ExpandoObject so that it can be used as JSON in Jint.
variable Demo: JSON = [{
   "firstItem": 1
}, {
   "secondItem: 100
}]

// Declare a variable of type Document, which is a user-defined type. In JINT space, the object would be an instance of `Document`, not a JSON object.
variable MyDocument: Document = {
   "documentId": "some-guid",
   "title": "Some title"
}
```

**Idea 3. JSON by default**

We could also leave the current UI as-is (a JSON editor) and implement a JSON converter that deserializes the JSON string into a list of variables, where each variable is typed `ExpandoObject` unless specified otherwise.

For example, the custom converter would be able to deserialize this:

```json
{
   "Demo": [{
      "firstItem": 1
   },{
      "secondItem": 100
   }]
}
```

into an ExpandoObject instead of a JObject.
And if you wanted to declare another WF variable, but of a custom .NET type such as `Document`, the JSON would look like this:

```json
{
   "Demo": [{
      "firstItem": 1
   },{
      "secondItem": 100
   }],
   "MyDocument": {
      "$type": "MyNamespace.Document, MyAsssembly"
      "DocumentId": "123-abc",
      "Title": "Some document title"
   }
}
```

Not the greatest UX still, but much better than the JSON one would have to type in currently and less effort than creating a UI to manage variables. On the other hand, it would greatly increase the UX.

**Comment by sfmskywalker** [comment]
Here's a sample JSON string that is deserialized into proper `ExpandoObject`s that then seamlessly operate as JSON objects in Jint:

```json
{
   "Messages": {
      "$type": "System.Object[], System.Private.CoreLib",
      "$values": [
         {
            "$type": "System.Dynamic.ExpandoObject, System.Linq.Expressions",
            "id": "2",
            "names": {
               "$type": "System.String[], System.Private.CoreLib",
               "$values": [
                  "Hello JSON!",
                  "Bye!"
               ]
            }
         }
      ]
   }
}
```

**Comment by sfmskywalker** [comment]
I forgot to mention that the above JSON code would only be correctly parsed if we change the ASP.NET Core serializer settings like this:

```csharp
.AddElsaApiEndpoints(options => options.SetupNewtonsoftJson = json =>
{
    json.SerializerSettings.TypeNameHandling = TypeNameHandling.Auto;
    json.SerializerSettings.TypeNameAssemblyFormatHandling = TypeNameAssemblyFormatHandling.Simple;
})
```
