### ISSUE TITLE
Having trouble setting Workflow Context Type in Workflow settings

### ISSUE THREAD

**Issue by harpsicord86** [elsa-workflows/elsa-core#2842]
Hi there,

I'm new to Elsa and I'm building an application using the ASP.NET Boilerplate framework with Elsa providing some automated workflows. I've been following the Working with Workflows guide https://elsa-workflows.github.io/elsa-core/docs/guides/guides-workflow-contexts without much success.

I can't seem to set the Context Type under the Workflow Context tab. When I click Save and then come back to it, it's gone!

Can anybody help??

**Comment by sfmskywalker** [comment]
Hi @harpsicord86,

When that happens it is almost always caused due to an incorrect type name. Please make sure you enter an assembly-qualified type name,

For example, if I have the following type in a project called `MyApp.Workflows`:

```csharp
namespace MyApp.Workflows.Contexts;

public class CustomerContext { }
```

Then the value to enter in the Workflow Context tab should be:

`MyApp.Workflows.Contexts.CustomerContext, MyApp.Workflows`

Also make sure that the this project is referenced by the application that hosts the Elsa API endpoints.
