### ISSUE TITLE
HTTP Response after Signal Received not working

### ISSUE THREAD

**Issue by RainerAtSpirit** [elsa-workflows/elsa-core#2851]
Steps to reproduce: 

```
 .\build-assets.ps1
cd .\src\samples\dashboard\aspnetcore\ElsaDashboard.Samples.AspNetCore.Monolith\
ElsaDashboard.Samples.AspNetCore.Monolith> dotnet run
```

Create two workflows like described in https://elsa-workflows.github.io/elsa-core/docs/next/guides/guides-signaling-workflows

[signal-http-response-issue.zip](https://github.com/elsa-workflows/elsa-core/files/8285778/signal-http-response-issue.zip)

![image](https://user-images.githubusercontent.com/581644/158809363-4cb4bb33-7351-4f51-97e1-8247639080d9.png)

![image](https://user-images.githubusercontent.com/581644/158809395-d1f0df3b-bd87-4562-9a68-f3a9c2134033.png)

Expected result: Accessing /workflows/send-signal returns a  valid http-response.
Actual result: No content, wrong response headers.

![image](https://user-images.githubusercontent.com/581644/158808936-8b2972c3-7866-4a97-b508-54becca3ca9a.png)

Another hello-world workflow works as expected, though.

![image](https://user-images.githubusercontent.com/581644/158809124-b2a4c826-5759-46a9-a79a-6f9723023838.png)

**Comment by matt4446** [comment]
Should this work? 

The first workflow starts in the middleware of a request
The second workflow starts as a separate trigger away from the original request.

The first workflow will complete before the second starts most likely as the signal is more fire and forget rather than waiting till everything completes. I would suggest trying RunWorkflow (with mode: blocking) but that suspends it allowing the middleware to continue so may have the same effect... I've not tried Request and Response with suspending workflows.

**Comment by sfmskywalker** [comment]
This bug was introduced with this change: 014fcf3ca4f08d6cb885a5b6083532b61a670d0e

The reason for that change was to "fix" a deadlock issue that occurs when one workflow sends a signal, another workflow handles this signal and sends a signal of its own.

This is something I need to look into some more, but we needed a solution quickly so changed from "synchronous" sending of the signal to "asynchronous" (sent via a queue and picked up in the background from some queue worker).

This has the side effect that any workflows listening to this signal are executed from a background worker and therefore no longer having access to the HTTP context from which the signal originated.

To offer a solution for now, I added an option that lets the user explicitly control whether they want to send the signal synchronously (which fixes the guide you're referring to) or asynchronously (the default, preventing the potential deadlock issue).

**Comment by NoorsTah** [comment]
isn't the issue fixed ?
using Elsa 2.14.1 on designer UI. @sfmskywalker
