### ISSUE TITLE
Parallelize activities

### ISSUE THREAD

**Issue by ButcherTux** [elsa-workflows/elsa-core#288]
Good morning,

I don't know if there is an another way to do what i'm going to describe.
I know that the **Fork** activity in the ControlFlow namespace can run branches one after one.
So it is possible to add a **Parallel** activity which run branches at the same time like Parallel tasks?
Or do you know a workaround to do it?

Thanks

**Comment by iyhammad** [comment]
I'm having the same thing and trying to figure it out.

**Comment by sfmskywalker** [comment]
@ButcherTux just to get a better understanding of the use case, can you please elaborate a bit on why it is important that each branch runs at the same time, instead of one branch after another in sequence?

**Comment by iyhammad** [comment]
For me, It's the same as mentioned here https://github.com/elsa-workflows/elsa-core/issues/291#issuecomment-613506859

**Comment by sfmskywalker** [comment]
@iyhammad So you need a ParallelForEach activity, right? Because the Fork will already execute each branch regardless of any one branch getting blocked, but Fork has a predefined set of branches. The ForEach activity allows you to iterate over any collection, however each iteration executed sequentially, which means that as soon as one iteration blocks, the entire loop is blocked. A ParalleForEach activity will solve that.

So for your scenario, there’s no need to parallelize Fork, correct?

**Comment by iyhammad** [comment]
@sfmskywalker For my scenario, ParallelForEach will solve it, yes. And no need to parallelize Fork.

**Comment by sfmskywalker** [comment]
Thanks for confirming @iyhammad

**Comment by johnwc** [comment]
@sfmskywalker I have a scenario where a `ParallelFork` is needed. We have a very large data set that is broken into several different data files per table. To simplify things, we broken out each file processing into its respected table into separate workflows. We have a main workflow that checks to see if a "batch marker" file exists. If it does, the next activity is a fork that has 6 defined paths that start each separate workflow for file processing. Then after all of the workflows are done processing their file, we have a join. After the join we have a activity that does required table maintenance and clean up, this cannot run until all of the tables have completed importing.

We need each path of the fork to run independently in parallel.
