### ISSUE TITLE
New Feature: Add ParallelForEach like Activity

### ISSUE THREAD

**Issue by iyhammad** [elsa-workflows/elsa-core#291]
ParallelForEach is an activity similar to ForEach. The difference between them is ForEach waits for the Iteration to complete then starts the new iteration. While ParallelForEach, start the iteration and if it goes idle (halt), the new iteration can start.
This should enable developers to create workflows like having dynamic list of tasks assigned to people in parallel and waiting for their approval.  
This is more description for how it looks like in Workflow Foundation. https://docs.microsoft.com/en-us/dotnet/framework/windows-workflow-foundation/control-flow-activities-in-wf

**Comment by RingoKam** [comment]
Can't we use FORK to create multiple branches and then a JOIN at the end? The JOIN will wait for all branches to be resolved before moving on.

**Comment by iyhammad** [comment]
I tried fork but there are 2 problems:
1. The fork needs a list of string while we need to have a dynamic list like something that comes from a database.
2. To use Fork, we need to use "When" which needs a specific number of branches and a predefined list of outcomes which also not the case.
The idea is, we don't know the number of branches in design time. Think of it as the number of approvers that come from the database.

**Comment by aboudaty** [comment]
Has this had any updates, please? It's important for a piece of work I'm hoping to start. @sfmskywalker

**Comment by sfmskywalker** [comment]
No updates unfortunately. But I'm gonna try and see what it would take to implement this in Elsa 2. If I'm not mistaken, it would be a simple matter of simply scheduling a new activity connected to the `Iterate` outcome using the current value as an input. If that works, I'll try and backport it to Elsa 1.

**Comment by sfmskywalker** [comment]
I was able to implement a parallel foreach activity using the Elsa 2 code base: https://github.com/elsa-workflows/elsa-core/blob/feature/elsa-2.0/src/core/Elsa.Core/Activities/ControlFlow/ParallelForEach/ParallelForEach.cs

The principle is simple: all I had to do was schedule whatever next activity is connected to the `Iterate` branch (using the `OutcomeResult`). Scheduled activities are always executed, even if for each iteration a blocking activity enters the schedule.

I will now try and see if I can apply the same principle on Elsa 1.

**Comment by sfmskywalker** [comment]
I'm afraid it won't be feasible to take the same approach in Elsa 1 without adding support for scheduling activities + associated *input*. Although I can schedule the `Iterate` branch repeatedly like I did in Elsa 2, I can't supply the current value of the iteration as part of the scheduled branch, which is important. Otherwise you wouldn't have any context in a given iteration.

I am open to receiving a PR however that adds the same capabilities as done in Elsa 2 (being able to provide an input value when scheduling an activity).

**Comment by sfmskywalker** [comment]
This is now part of Elsa 2.

**Comment by aboudaty** [comment]
Thank you so much for taking action on this, @sfmskywalker!

**Comment by ricksearcy** [comment]
@iyhammad did you ever figure out a solution to this? I am trying to accomplish something similar to your issue and can't figure out how to get it to work. If we were to use the DocumentApprovalWorkflow example where "Jack" and "Lucy" were hardcoded I need those to be dynamic and unknown at design time. 

@sfmskywalker do you have an example of the ParrellForEach that can take an unknown list and create the Forks dynamically? Using this as an example: https://github.com/elsa-workflows/elsa-core/blob/master/src/samples/aspnet/Elsa.Samples.DocumentApproval/DocumentApprovalWorkflow.cs

But instead of having hard coded names we start with them as a list of values and then build the Forks dynamically.  
public void Build(IWorkflowBuilder builder)
        {
            string[] names = { "Jack", "Lucy"};

**Comment by sfmskywalker** [comment]
Sure, take a look at the [CallRinGroup](https://github.com/elsa-workflows/elsa-core/blob/master/src/activities/Elsa.Activities.Telnyx/Activities/CallRingGroup.cs#L193) activity. Notice that the **ParallelForEach** activity is initialized with a list (called `Extensions` in this example, which is a collection of strings configured by the user at design time, but could come from any other source such as a database table).

What the **ParallelForEach** activity will do is schedule the **Iterate** outcome for each item in the list, similar to what the **Fork** activity does. The big difference between these two activities is that **ParallelForEach** uses a single outcome (**Iterate**), while the **Fork** activity uses its `Branches` collection to schedule them as outcomes.

> CAUTION: there is a limitation with Elsa 2 preventing you to correctly use **blocking activities** in combination with **ParallelForEach** as outlined [here](https://github.com/elsa-workflows/elsa-core/issues/1025).
