### ISSUE TITLE
404 error when trying to execute Elsa Activity created a month ago 

### ISSUE THREAD

**Issue by viswajwalith-exceego** [elsa-workflows/elsa-core#2939]
We are trying to send a signal to Elsa from our web application we are getting the 404 error, I think this is because of some token or URL expiry,  can you please tell where can we check this and where exactly the activity URL and token is going to be stored. 

https://mysite.com/workflows/signal?token=CfDJ8OtNwatOCSRMqyGT9F0sG0A6yVL7hbWYaXImrnjlzXX1Oj13YOT410zn0apmGa6XB3Sc6TAcirsThplV4XEASB0J1bpdIXRx43AytUw0AsQgoayqq7t_oafa59VAGYVkDPxdJq7rC4vppv8roNDqq_c5ue6nxGbNba7qkJvrN3xs5Q9x8K7eGCAwsF0wpuLUWJzPNrLZBdtsTCnrMNDSLuY 

We found this issue with the work flow records which got created a month ago (approximately)

**Comment by viswajwalith-exceego** [comment]
@mohdali @sfmskywalker  @craigfowler or anyone in the group can you please provide some inputs, this is high priority issue for us. Thanks in advance

**Comment by sfmskywalker** [comment]
Based on the URL you're trying to invoke and the fact that you get a 404 (and not a 400), it looks like you're using Elsa 1.

The class responsible for creating protected tokens is [TokenService](https://github.com/elsa-workflows/elsa-core/blob/releases/elsa-1/src/activities/Elsa.Activities.Http/Services/TokenService.cs).

It uses `IDataProtectorProvider` to create an `IDataProtector` - which doesn't generate time-limited tokens, so I don't think the issue is that of expired tokens - but perhaps your server no longer has the original encryption keys. This happens when you're hosting in the cloud for example (Azure App Service, Container, Kubernetes etc) or simply when moving the application to a different machine.

Please read [this](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/introduction?view=aspnetcore-6.0) for more information on how data protection works.

Of course, this doesn't help you right now - if the keys are lost, there's no way to decrypt the token.
But going forward, it is advised to configure a persistent key store such as Redis, SQL Server, Azure Keyvault, Azure Blob storage, etc.

Your only hope seems to be being able to find the generated tokens in the database, but I fear this will not be the case.
If it were the case, then you could match the token with the proper workflow instance and possible signal name. In which case you could replace the `TokenService` implementation with a custom one that simply looks up the signal name.

**Comment by viswajwalith-exceego** [comment]
Thanks  @sfmskywalker , yes we are using Elsa 1 and also not able to find any stored tokens in database. so it seems for now we lost the execution of existing ones.

We will move to persistence DB soon, but for now we would like to turn off the token verification logic during signal execution.  do u think this will work ? if so what is the best way to do so?
