### ISSUE TITLE
elsa workflow version does not update well

### ISSUE THREAD

**Issue by diegocantero** [elsa-workflows/elsa-core#2954]
we have a docker container in kubernetes and persistence in mongo.
in the last update, we have a problem and it is that when the version of a flow is updated and it is initialized but sometimes it does not take the latest version but it stays in another version and the only solution is to restart the container. In local it works normally, the docker image in local also works well, do you have any idea why it happens?
![image](https://user-images.githubusercontent.com/90941579/164557664-4950301d-b38e-4cdd-a901-1485eec52983.png)
![image](https://user-images.githubusercontent.com/90941579/164557785-467544bc-3200-4ee3-a590-6c333a901f34.png)

**Comment by sfmskywalker** [comment]
How many containers are you running in your kubernetes cluster?
If more than 1, then the issue is that Elsa is caching workflow blueprints in local memory, and basically need to be refreshed.
Elsa takes care of this for you, but it needs to be configured with cache signaling.

Please checkout [this article about distributed hosting](https://elsa-workflows.github.io/elsa-core/docs/next/hosting/hosting-distributed-hosting) (if you haven't already).
