### ISSUE TITLE
Activity output

### ISSUE THREAD

**Issue by tsoG2000** [elsa-workflows/elsa-core#2967]
Is it possible to name output variable any other name than "Output" to work properly? I am expecting that output variable decorated with [ActivityOutput] annotation should be considered output variable regardless of the name.

Here is the example, where in "Case 1" I don't get the expected result, but "Case 2" and "Case 3" work.
```
[Activity(
        DisplayName = "FirstActivity",
        Description = "FirstActivity Desc")]
    public class FirstActivity : Activity
    {
        //[ActivityOutput] public string ActivityResult { get; set; }   // => Case 1
        //[ActivityOutput] public string Output { get; set; }           // => Case 2
        protected override IActivityExecutionResult OnExecute(ActivityExecutionContext context)
        {
            //ActivityResult = "Success";   // => Case 1
            //Output = "Success";           // => Case 2
            context.Output = "Success";     // => Case 3
            return Done();
        }
    }

 [Activity(
        DisplayName = "SecondActivity",
        Description = "SecondActivity Desc")]
    public class SecondActivity : Activity
    {
        protected override IActivityExecutionResult OnExecute(ActivityExecutionContext context)
        {
            string firstResult = context.GetInput<string>();
            // Case 1 => firstResult = null
            // Case 2 => firstResult = "Success"
            // Case 2 => firstResult = "Success"
            return Done();
        }
    }
```
Is this a feature or a bug, or something that is still in the works? :)

**Comment by sfmskywalker** [comment]
Yes, you can name your output properties anything you want.
However, there's a naming convention at play: when an output property is named `Output`, it will automatically be provided as input into the next activity.

If you use a different name, let's say `MyOutput`, then the only way to access this output is by using the activity name and its output property explicitly.

This is the preferred method, because input into a given activity might change if you have multiple inbound paths for example.

To explicitly get the output of an activity, you need to:

1. Give your activity a name (so that you can reference it later on)
2. Request the output value.

Your sample `SecondActivity` currently hardcodes access to its input, which is not recommended
Instead, it's recommended to accept input via input properties.

For example:

```csharp
[Activity(
        DisplayName = "SecondActivity",
        Description = "SecondActivity Desc")]
    public class SecondActivity : Activity
    {
       [ActivityInput] public string MyInput { get; set; }

        protected override IActivityExecutionResult OnExecute(ActivityExecutionContext context)
        {
            string firstResult = MyInput;
            // Case 1 => firstResult = null
            // Case 2 => firstResult = "Success"
            // Case 2 => firstResult = "Success"
            return Done();
        }
    }
```

From your workflow, when you now give your first activity a name of e.g. `FirstActivity1`, you can configure your second activity's `MyInput` property like this:

**Using a JS expression when using the designer**

```javascript
activities.FirstActivity1.ActivityResult()
```

**Using C# when defining your workflow via code**

```csharp
builder
.StartWith<FirstActivity>().WithName("FirstActivity1")
.Then<SecondActivity>(a => a.Set(x => x.MyInput, async context => await context.GetNamedActivityPropertyAsync<FirstActivity, string>("FirstActivity1", p => p.ActivityResult)))
;
```

The syntax is horrible, but that's being improved drastically with Elsa 3. 
With the designer, as you've seen, the expression is much better.
