### ISSUE TITLE
UI Dashboard does not work: Errors in Console

### ISSUE THREAD

**Issue by DanielTrefzer** [elsa-workflows/elsa-core#2995]
Hi, 
we us the Quickstart for "Dashboard + Server". 
This seems to have some issues in the JS part. 

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'filter')
    at d.loadWorkflowDefinitions (p-56b6bcf0.entry.js:1:3369)
    at async d.componentWillLoad (p-56b6bcf0.entry.js:1:2002)

**Comment by diegocantero** [comment]
Hi!
I have the same problem. 
in the dashboard with render a workflow instance

**Comment by sfmskywalker** [comment]
I just went through the quick start, and it works for me. However, I did have to change the appsettings.json to point to a different port number, because the app was started on port 7601 instead of 5001. 

So, perhaps this is what happened for yo as well?
Please check if the port used in the value of `Elsa:Server:BaseUrl` in your `appsettings.json` file matches the port number you see in your browser's address bar:

![image](https://user-images.githubusercontent.com/938393/167211146-47b3fe85-d983-4a0f-9de5-34b6f1dd30e2.png)

**Comment by DanielTrefzer** [comment]
Hi, 
sadly this does not work
![image](https://user-images.githubusercontent.com/72071505/167855350-4a75d01a-49ea-49bb-9fa3-d2b66411cd01.png)

**Comment by deathblade89** [comment]
Hi there,

We found that if this is not in then the filter undefined error appears:

![image](https://user-images.githubusercontent.com/16613924/174283056-10de80b0-f9e8-49cb-bbce-0bc79d84334a.png)

**Comment by DanielTrefzer** [comment]
HI there, 
thanks - but this was already in :-)
