### ISSUE TITLE
Automapper Issue after Elsa version 2.5.0

### ISSUE THREAD

**Issue by imwanghaiyang** [elsa-workflows/elsa-core#2997]
Hi,

I use Abp VNext  https://abp.io/  framework.

No AutoMapper mapping issues when I use Elsa version 2.5.0.
However, when I use Elsa 2.6.0 and 2.7.0 versions, there is an AutoMapper exception.

Exception Information:
ObjectMapper = "ObjectMapper" threw an exception of type "Autofac.Core.DependencyResolutionException"

**Comment by sfmskywalker** [comment]
Hi @imwanghaiyang ,

The issue is that both ABP and Elsa use AutoMapper, but a different version:

- ABP uses AutoMapper 10
- Elsa 2.5 uses AutoMapper 10
- Elsa 2.6 and up use AutoMapper 11

There seem to be ways around this: https://michaelscodingspot.com/how-to-resolve-net-reference-and-nuget-package-version-conflicts/

This comment sounds promising too: https://michaelscodingspot.com/how-to-resolve-net-reference-and-nuget-package-version-conflicts/#comment-1147

**Comment by akunzai** [comment]
Hi there,

ABP 5.3 is [migrating to AutoMapper 11](https://github.com/abpframework/abp/issues/12144).
