### ISSUE TITLE
Turn Code Workflow into JSON?

### ISSUE THREAD

**Issue by RingoKam** [elsa-workflows/elsa-core#301]
Is there a way to turn code workflow into JSON to persist in DB? 

if I register the workflow as code, it doesn't seem to persist until an instance is created. How is schema versioning handled for code based workflow???

**Comment by sfmskywalker** [comment]
There is a way, but it would be useless as soon as you start using C# lambdas to implement activities and/or property expressions because Elsa doesn't know how to serialize/deserialize that. Perhaps there's a way to actually serialize the C# expressions into JSON and then load it back in a meaningful way, but even if that's possible, its not currently supported (but I would totally accept a PR with that feature).

Schema versioning is handled by you, the author of a code based workflow, by specifying the version of the workflow as follows:

Elsa 1:

```csharp
public class HelloWorldWorkflow : IWorkflow
{
    public void Build(IWorkflowBuilder builder)
    {
        builder
            .WithVersion(1) // Specify version (defaults to 1).
            .StartWith<WriteLine>(activity => activity.TextExpression = new LiteralExpression("Hello World!"));
    }
}
```

Or in Elsa 2:

```csharp
public class HelloWorldWorkflow : IWorkflow
{
    public void Build(IWorkflowBuilder builder)
    {
        builder
            .WithVersion(1) // Specify version (defaults to 1).
            .WriteLine("Hello World!"); // Because of C# "code expression" support, we can't serialize this definition into JSON and deserialize back.
    }
}
```

Now if you make a change to the code based workflow definition, make sure to increment the version before deploying to production, e.g.:

 ```csharp
public class HelloWorldWorkflow : IWorkflow
{
    public void Build(IWorkflowBuilder builder)
    {
        builder
            .WithVersion(2) // Specify a newer version.
            .WriteLine("Hello World!")
            .WriteLine("Goodbye cruel world...");
    }
}
```

This way, any existing workflow instances will still work correctly, because a workflow instance holds information not only about its workflow definition, but also which version of tat definition.

**Comment by RingoKam** [comment]
thank you for the reply!
