### ISSUE TITLE
How to start workflow to run on a multinode environment

### ISSUE THREAD

**Issue by hakancunier** [elsa-workflows/elsa-core#3015]
Congrats and thanks for this really great library.

I have 3 servers, 2 servers (both)running "Hangfire Jobs + RabbitMQ Consumers", and 1 server for UI/Rest Interaction.
I want ELSA to work as multinode clustered on "Hangfire Jobs + RabbitMQ Consumers" nodes. That was easily configured according to the "Hosting Elsa on Multiple Nodes" guide, but;
i need to trigger a workflow on the single UI node and the workflow instance must run on available node of 2 "Hangfire Jobs + RabbitMQ Consumers" Nodes.

Is that possible? Do i need to configure UI/Rest Server's Startup like services..AddElsa(elsa=>elsa.UseHangfireDispatchers... and/or .UsePersistenceProvider) or what ....

I think the documentation needs some improvements about getting started on such use cases. 

Thank you in advance.

**Comment by hakancunier** [comment]
Any comments?

**Comment by sfmskywalker** [comment]
Hi @hakancunier 

This should work for you without any additional configuration. But whether or not the workflow executes on the 2 worker nodes, that depends on the kind of workflow you are triggering, and/or how you are triggering these workflows.

For example, if you trigger your workflows manually from an API controller using `IWorkflowDispatcher`, then you're good: the dispatcher will place a message in a queue, which then gets picked up by one of the two worker nodes.

But, if your workflow starts with e.g. the `HTTPEndpoint` activity, and the workflow finishes from start to end, then this workflow executes directly on your UI node.

**Comment by hakancunier** [comment]
Thanks for reply. You mean;
NodeUI should trigger a workflow by using `IWorkflowDispatcher`, then one of the other two nodes bounded to the queue will pick the message and start an instance.

Well, how will NodeUI know the host, args, options, vs.. I mean the "two nodes" startup sets all these according to the guide you mentioned. I am asking how to setup ELSA as ONLY CLIENT for the queue and just using `IWorkflowDispatcher`.

**Comment by hakancunier** [comment]
Hello @sfmskywalker. Unfortunately couldnt get it working. This library seems good but the lack of documentation and support is too weak. Nearly one month passed over my question and still no clear answer.

**Comment by sfmskywalker** [comment]
I 100% understand your frustration and I wish I had more time to work on all these things (documentation, troubleshoot, answer questions) on top of the day job and working towards new features. As I'm sure you understand, this is quite challenging. But, I'm attempting to work on a solution to make this better in the (hopefully near-term) future.

With regards to your question: although you can use `IWorkflowDispatcher` from your UI node, its implementations (there are 3 of them) rely on other Elsa-related services. So, effectively you would have to configure Elsa in your UI node as well. 

Which is not what you want. Instead, there are two alternatives you could do today from your UI node, where number 1 is the recommended approach:

1. Communicate with the Elsa API endpoints via HTTP, which internally leverage `IWorkflowDispatcher`. This is practical if your workers nodes are exposed via a load balancer. For example, if you're using Kubernetes, you would configure ingress and some load balancer.
2. Or, send messages to the queue directly (look at `QueuingWorkflowDispatcher` to understand the messages to send using Rebus)

Option 1 is the easiest and achieves what you want: having a "thin" UI node that tells the 2 worker nodes to do work. No additionally work necessary. Unless you're not using a load balancer, because then your Node UI has to randomly choose what worker to invoke.

Option 2 works too, but requires you to use Rebus from your UI node in order to send the right messages to the right queues. We might consider refactoring the current `QueueingWorkflowDispatcher` out to its own library, so that you can reuse it "as-is" from the UI node. I hadn't thought of using a queue client before outside of an Elsa workflow server, but it makes sense.


> Well, how will NodeUI know the host, args, options

If the UI node is going to send messages to the queues directly, then you would configure it with the same service bus connection strings used by the worker nodes.

Alternatively, if you use the HTTP API endpoints exposed from your worker nodes, then you could use the `Elsa.Client` library, which as an `ElsaClientOptions` object to configure with just one field: the `ServerUrl`.
This URL should point to whatever URL your workers are exposed from (via a load balancer so that there is a single public URL to invoke).
