### ISSUE TITLE
Workflow loops forever because of error in RunJavaScript

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#3020]
[error-loop.zip](https://github.com/elsa-workflows/elsa-core/files/8680534/error-loop.zip)

Following workflow loops forever because of the RunJavascript (that has error) inside While loop.
**It loops forever** instead of faulting. Workflow is attached.

It seems to be connected to RunJavascript because if I replace it with SetVariable with identical error, the workflow instance faults as expected.

**Comment by dgumbo** [comment]
I also have the same problem, but for me, the loop is causing my system to crash,

it was an error on my part thogh, because i set the loop variable wrong [activities.ActivityName], instead of [activities.ActivityName.Output()], what i would like is for the activity to error out rather than engage an infinite loop.

**Comment by dgumbo** [comment]
same as https://github.com/elsa-workflows/elsa-core/issues/3001
