### ISSUE TITLE
OData and WebAPI Controllers stop working after adding Elsa Dashboard

### ISSUE THREAD

**Issue by chris1411** [elsa-workflows/elsa-core#310]
I'm using the latest preview nuget package and followed the instructions to add the Elsa Dashboard to my project. I was able to get the dashboard up and running, however I have other controllers in the project that are derived from ControllerBase and ODataController that no longer work. I'm getting the following error:

Unable to cast object of type 'OData.Controller.Name' to type 'Microsoft.AspNetCore.Mvc.Controller'.

**Comment by sfmskywalker** [comment]
The issue is that the `NotifierFilter` of the dashboard application assumes that the current action being executed is that of a `Controller` derivative. Apparently this doesn't have to be the case.

I just pushed an update to `develop` that access the TempData dictionary directly using `ITempDataDictionaryFactory`.

The package is being built & deployed as I type this, so should be available on MyGet within the next few minutes.

Let me know if that works or not.

Thanks!

**Comment by chris1411** [comment]
yep that did the trick. Thanks for the quick fix!
