### ISSUE TITLE
How do you hide an activity from the designer?

### ISSUE THREAD

**Issue by dannyheard7** [elsa-workflows/elsa-core#315]
I cannot find any documentation on how to do this. I don't want the email activity to be shown or the console activities

**Comment by steve99** [comment]
Assuming you are using the source to embed the designer in your own app, just remove the Elsa.Activities.xxxx references from the Elsa project.  Equally if you want to extend it, create an extension project.

**Comment by dannyheard7** [comment]
Is there any way of doing it without modifying the source

**Comment by steve99** [comment]
Not at present I don't believe, but will let sfmskywalker pick up when he is online as I have only recently started using this.

**Comment by sfmskywalker** [comment]
There's no system in place where available activities are sourced from e.g. configuration or a database, but the APIs are there - you can choose which activities you want to make available from the Startup class in the Dashboard project. By default, it uses Scrutor to discover all activity types and register them with the Dashboard. But you could also register individual activities. Or even write code to read "enabled" activity types from a configuration file.

I'm intending to add this configurability to the new version of the Dashboard implementation using Orchard Core and possibly the SPA reference implementations (under construction), but it will take a while unfortunately, due to a change in priorities.

**Comment by hassanelsherbiny** [comment]
there is a function remove all core activities called "NoCoreActivities"
can be called while configuring elsa and it will remove all built in activities

**Comment by HishamAbonjim** [comment]
still i can see the timer activity with this method,

**Comment by HishamAbonjim** [comment]
still i can see the timer activity with this method,

**Comment by hassanelsherbiny** [comment]
@HishamAbonjim timer activity is not core activity it's Quartz Temporal Activity so if you don't want timer activity you just don't call "AddQuartzTemporalActivities" Method

**Comment by HishamAbonjim** [comment]
yes it worked thanks :)
