### ISSUE TITLE
getWorkflowDefinitionIdByName unreliable on multiple instances

### ISSUE THREAD

**Issue by GotBinGo** [elsa-workflows/elsa-core#3154]
We are trying to run the Elsa dashboard on multiple instances.
We seem to have a strange problem of getWorkflowDefinitionIdByName not finding a workflow that exists.
We have been able to produce this three separate times, always on Postgres with RabbitMq and Rebus.
We have not found a reliable way to reproduce the error.
Publishing a new version of either referenced and referencing workflow does not seem to help.
Exporting, deleting and importing the workflows again seems to reliably fix the problem.

I'm wondering if this could be a problem with the Entity Framework cache not being shared between the instances.
Do you have a suggestion as to what this problem could be?

**Comment by sfmskywalker** [comment]
When hosting Elsa on multiple server instances, make sure to go through the steps outlined [here](https://elsa-workflows.github.io/elsa-core/docs/next/hosting/hosting-distributed-hosting).

Each workflow definition will be stored in a local cache on the server. To invalidate this cache when a new workflow version is published, a signal needs to be distributed to all instances in the cluster. The article I linked to should help you to set this up.

**Comment by GotBinGo** [comment]
Yes this is the article we followed.
We are using the Rebus cache signal something like this.
```
services.AddElsa(elsa => elsa.UseRebusCacheSignal());
```
I'm thinking this takes care of what you mentioned.
I would say things work correctly 95% of the time, that's why we are in trouble.
I'm wondering how I could be checking if these signals are fired and received.
I'm considering trying the UseRedisCacheSignal.

I'm wondering why there is no  SubscribeToRebusCacheSignals I was only able to find SubscribeToRedisCacheSignals .
https://github.com/elsa-workflows/elsa-core/tree/master/src/providers/Elsa.Providers.Redis/StartupTasks

**Comment by vargaendre** [comment]
> When hosting Elsa on multiple server instances, make sure to go through the steps outlined [here](https://elsa-workflows.github.io/elsa-core/docs/next/hosting/hosting-distributed-hosting).
> 
> Each workflow definition will be stored in a local cache on the server. To invalidate this cache when a new workflow version is published, a signal needs to be distributed to all instances in the cluster. The article I linked to should help you to set this up.

Hi sfmskywalker,
Thank you for the answer. How can we make sure that our multinode setup is correct? We followed the article you mentioned, instances start, we don't see errors, still it would be great to have a checklist to go through which would ensure that our setup is all correct.

**Comment by vargaendre** [comment]
Actually, I can see the messages in RabbitMQ console. For example when I publish a new version of one of the workflows, I see the new messages in the chart on the RabbitMQ console. Shouldn't this mean that the multinode setup is OK?

**Comment by sfmskywalker** [comment]
> I would say things work correctly 95% of the time, that's why we are in trouble. I'm wondering how I could be checking if these signals are fired and received.

That seems odd. And tricky to troubleshoot because it sounds like it's not something easily reproduced consistently.
What you might try is clone the repo and reference the projects directly, rather than the NuGet packages, and add logging statements where signals are sent and are expected to be received, collect all of this information, and try to analyze. Not a small task.

> I'm wondering why there is no SubscribeToRebusCacheSignals I was only able to find SubscribeToRedisCacheSignals. https://github.com/elsa-workflows/elsa-core/tree/master/src/providers/Elsa.Providers.Redis/StartupTasks

`SubscribeToRedisCacheSignals` is a startup task that subscribes to a Redis bus. 

For Rebus, it needs to register a consumer that processes the `TriggerCacheSignal` message. To register this consumer, simply call `UseRebusCacheSignal` on the elsa options builder, for example:

```csharp
services.AddElsa(elsa => elsa.UseRebusCacheSignal());
```

**Comment by vargaendre** [comment]
One more data point. While testing the workflow, I saw this:
![image](https://user-images.githubusercontent.com/3177057/175954631-0e6536b6-f2a6-4a9a-8e94-ac59fa859917.png)
After a little time and a refresh, it changed to this:
![Untitled](https://user-images.githubusercontent.com/3177057/175956219-40e75c29-5e5c-49aa-8617-82db14d5986c.png)
So, whatever generated this UI, did not find the workflow definition. Then it did. Since then I refreshed the page many times, got the workflow definition. Could it be that the workflow definition could not be found only while it was ran (by another node)?
