### ISSUE TITLE
Timers

### ISSUE THREAD

**Issue by steve99** [elsa-workflows/elsa-core#319]
How is this supposed to operate?  It appears that it generates a new instance of a workflow based on the global sweep config item, so if set to 10ms, it generates shedloads of instances, which are blocked.  Ignoring the timer condition in its entirety.  

I thought that setting to a singleton workflow would resolve it, but whilst it doesn't spawn loads of instances at once, it does appear to work.    The code is quite complex so would be good to know what it actually does.

**Comment by sfmskywalker** [comment]
Hi Steve,

In Elsa 1, there are two modes of operation:

1. Transient workflows: they get instantiated every time a sweep occurs (as you observed)
1. Singleton workflows: they get instantiated only if there's no unfinished workflow instance (running or suspended)

Although the `Singleton` mode prevents instantiating workflow instances like a madman when using a high-frequency sweep, it poses yet another problem: it effectively prevents long-running workflows starting with a timer to execute multiple instances (e.g. one every 5 minutes if that's the interval on the `TimerEvent`).

In Elsa 2, I fixed this as follows:

1. Instead of using Singleton, the workflow scheduler (renamed from invoker to scheduler) simply checks if a workflow definition scheduled to be instantiated doesn't already have a pending instance that is about to start for that workflow definition.

For example, if you have a workflow starting with a `TimerEvent` set with an interval of 5 minutes, the scheduler will only create one instance of that workflow every 5 minutes (regardless of the sweep frequency). Contrast to the Singleton mode, this fix allows multiple instances of the workflow to execute, without going berserk with the number of workflow instances.

We should probably back-port this.

**Comment by steve99** [comment]
Thanks, that explains it.  Yes, the new approach is far better.  I thought I was going mad!!  Thought I must have screwed something up in my Cosmos code, so went back to the other persistence methods and say similar behaviour...  I am getting there with that, but keep hitting walls albeit this was an artificial one.  Now using the workflow definition as the partition key, status was working, but gave me a few headaches, so now using DefinitionId as that is a local grouping also.  I am hoping to avoid changing the Interface that way, as I can enumerate the definition document to get all known ID's.  

Should I be building against 2?

**Comment by sfmskywalker** [comment]
> I thought I was going mad!!
Sorry! 😂 

> Now using the workflow definition as the partition key, status was working, but gave me a few headaches, so now using DefinitionId as that is a local grouping also
Makes sense! I like it, because DefinitionId never changes.

> Should I be building against 2?
I have to recommend against it, because its availability is still quite far away - I basically broke everything there, which means there's currently no dashboard nor designer.

**Comment by steve99** [comment]
Thanks, I will continue against 1 and ignore the timers for the time being.  Now I know that, I can work with it.  I'm struggling to follow the code on that as it is TBH, so no hope of me porting that back for you.  

Good luck on Version 2!!!

**Comment by sfmskywalker** [comment]
Thanks!

I'll leave this ticket open as a cue for me to backport, because the Timers feature is rather useless without it (unless using it as a singleton, but has limited use cases in its own right).

**Comment by sfmskywalker** [comment]
Since Elsa 1 is no longer actively developed, I'm closing this issue. For robust timer activities, it is best to migrate to Elsa 2 or higher.
