### ISSUE TITLE
Send HTTP Request Response missing

### ISSUE THREAD

**Issue by pmaximino** [elsa-workflows/elsa-core#3229]
Hi guys, 

I only began to use Elsa about a week ago, but I'm having a problem that might be an issue (luckily I'm just missing something).
This is my workflow:
![image](https://user-images.githubusercontent.com/12159442/181256885-9ff66aee-a838-4fcd-8c70-e389e68d7c0b.png)
This is the Send HTTP request:
![image](https://user-images.githubusercontent.com/12159442/181257657-c335c604-cb6f-462a-a557-42f58110be32.png)
Here I'm trying to see if I can at least see the length of the response, but it returns 0. The request is indeed getting a 200 (OK answer), but I can't access the response (if it is brought at all). Thanks in advance!

Patricio

**Comment by tomy2105** [comment]
The main question is where are you trying to access the response.
If it is inside input parameters of the SendHTTPRequest activity (as your image suggests) then it is only natural that it returns 0 because they are evaluated **before** SendHTTPRequest activity is executed.

Can you try using expression `activities.DaleGato.Response.length` in some activitiy after SendHTTPRequest activity.
And yes, I suppose DaleGato is the name you've given to SendHTTPRequest activity  in the advanced tab? (just to make sure... :)).

In any case if what I've suggested doesn't work please paste your workflow json export here so we can help better.....

**Comment by pmaximino** [comment]
Hi Tomy. First of all thanks for your answer!
I'll try to be more clear. I'm trying to read the content of the response (body). In some cases, I'll need to add body content in the request, but not always. Let's leave that out for now. This is what I need to read and parse:
![image](https://user-images.githubusercontent.com/12159442/181565503-0a9c2daf-bf6a-4cfd-be92-aff31896f729.png)
The workflow looks like this:
![image](https://user-images.githubusercontent.com/12159442/181566080-4a323ad4-bb69-4112-ad62-c5d675a84499.png)
The activities look like [this:]([url](url))
![image](https://user-images.githubusercontent.com/12159442/181566301-2590859a-b6e8-4466-9c43-386f78a5f798.png)
![image](https://user-images.githubusercontent.com/12159442/181566427-412bee88-5d92-44c6-ad1c-f4f536806a6f.png)
![image](https://user-images.githubusercontent.com/12159442/181566569-1a1ac1c7-33c8-4a57-936a-0eb42a2907df.png)

I also attached the json as request. Thanks again for your [help!]([url](URL))

Patricio

[example.txt](https://github.com/elsa-workflows/elsa-core/files/9211722/example.txt)

**Comment by pmaximino** [comment]
Hi @tomy2105 ,

I've managed to get to the response using Liquid as done [here](https://github.com/elsa-workflows/elsa-core/discussions/1154) but I cannot parse the content as done there, I can only print out the response content
![image](https://user-images.githubusercontent.com/12159442/182209920-bef3768a-ecad-47e1-ac35-4c54cb84f75d.png)
![image](https://user-images.githubusercontent.com/12159442/182210007-f91a38cb-bf11-4b07-9d78-27c8f8c1f934.png)
![image](https://user-images.githubusercontent.com/12159442/182210038-74f271fe-6d63-499d-a0d0-790fedba64ec.png)
Any hint if there's a encoding issue or something like that? Thanks!

Patricio

**Comment by tomy2105** [comment]
Here is the working example I managed to get to work on current code [http_request_example.txt](https://github.com/elsa-workflows/elsa-core/files/9251383/http_request_example.txt).

I've made two changes to your example I've downloaded.
First is regarding fetching activity properties (results) in JavaScript expressions. You need `activities.HTTPRequestActivity.ResponseContent()` instead of `activities.HTTPRequestActivity.ResponseContent`. Note the function call parenthesis **()**!!!

Second is in HTTPRequest activity. I've set **Response Content Parser** to **Expando Object** (JToken and .NET Object also work).
Much to my (and yours) surprise, **JSON** doesn't do any parsing (I've checked code and `JsonRawHttpResponseContentReader` is same as `PlainTextHttpResponseContentReader`)

**Comment by tomy2105** [comment]
@sfmskywalker could you be so kind and explain (or document :) ) differences and when should each of  **Response Content Parser**'s do as well as check why **JSON** one doesn't seem any different from **Plain text**. 

Personally it seems to me there are two many to choose from and some of them could be "united". For example **.NET Object** and **Expando Object** - **.NET Object** falls back to `ExpandoObject` when no .NET target is given but doesn't seem to automatically handle arrays as **Expando Object** does, so there could be only one doing both. I'm not sure what JToken one is used for.

**Comment by pmaximino** [comment]
Hi @tomy2105. The ExpandoObject did the trick! Thanks a lot for you help. I'll keep an eye on your request to @sfmskywalker, but for now, I'm unblocked.

**Comment by sfmskywalker** [comment]
@tomy2105 

Absolutely spot-on observations. The ExpandoObject and .NET parsers should be merged, as well as the raw JSON + plain text formatter.

I don't recall why, but there is a scenario where one might want to parse JSON into a JToken rather than ExpandoObject. Serves me well; I should have added comments and/or documented it 😬
