### ISSUE TITLE
Questions on Custom Activity Life Cycle and Data Persistency

### ISSUE THREAD

**Issue by RingoKam** [elsa-workflows/elsa-core#336]
Hi, some questions on how to implement custom activity.

Is my following assumption correct on Activity Life Cycle correct?
1)  OnCanExecute is the first life cycle right? it determine if the activity can be triggered. if i resume an activity, would OnCanExecute  be triggered again? 
2) OnExecute, get trigger when the activity is triggered, happens after OnCanExecute, can determine if activity is halted or complete 
3) OnHalted,  get trigger when activityresult is halted.
4) OnResume, get trigger when activity is resume. 
5) If i call workflowinvoker.resumeasync, would it trigger OnCanExecute and OnExcute again?

For Data Persistency within the workflow, there seems to couple ways we can store data 
1) Variables: persisted in storage, they are available to all activity 
2) LastResult: persisted in storage, access the lastResult from previous activity, how is this different from output?? 
3) Input: transient in nature, data you pass in when you trigger an activity
4) Output:  transient in nature, result after triggering an activity 

Thanks Again 🙇‍♂️

**Comment by sfmskywalker** [comment]
Hi @RingoKam ,

Regarding your questions about Activity Life Cycle:

1. That is correct. `OnCanExecute` is invoked before `OnExecute` and before `OnResume`. If `OnCanExecute` returns `false`, then neityer `OnExecute` nor `OnResume` is invoked.
2. Yes, `OnExecute` is invoked after `OnCanExecute`. Indeed, the `OnExecute` method can return an instance of `IActivityExecutionResult`, which is implemented by `HaltResult`. If you want to return a `HaltResult`, the easiest way is to invoke the `Halt()` method from your `OnExecute` method.
3. Correct.
4. Correct.
5. Partially correct. When you call `ResumeAsync`, it will trigger `OnCanExecute` and if that returns `true`, it will trigger `OnResume`. `OnExecute` is only invoked the first time an activity is encountered.

Regarding Data Persistence:

1. Yes
2. Yes. Correct me if I'm wrong, but I think that Activity Output is being introduced with Elsa 2.0, not Elsa 1 (current release). In Elsa 2.0, I'm removing LastResult in favor of Activity Output.
3. Yes
4. Perhaps you meant "Outcome" instead of "Output"? If so, then yes. An activity Outcome is basically a label that allows the workflow invoker to determine what activity to execute next.

My pleasure! :)

**Comment by RingoKam** [comment]
Ah! thanks for clarifying. This is very helpful. 

I saw Input and Output in `WorkflowExecutionContext.Workflow`. I am using Elsa 1.2.2.29 from Nuget.
