### ISSUE TITLE
CleanupJob Not Using Retention Filter?

### ISSUE THREAD

**Issue by brantley-svt** [elsa-workflows/elsa-core#3387]
@jdevillard Added the awesome `IRetentionSpecificationFilter` for filtering workflow instances ready for cleaning up.

However, based on [this commit](https://github.com/elsa-workflows/elsa-core/commit/d01eb73ddbcb8ceca7ded5c72d08891cb24e5dfb#diff-85f02735bb9293de8de201170f9c128bec23ebc30ace6340c754f36a60eaa1a9) it looks like the `_retentionFilterPipeline.FilterAsync()` call was removed and the new filtering functionality was not added to `CeanupJob.cs`, meaning all workflow instances older than the threshold will be processed, regardless of filter settings.

[Currently the specification instantiation in `CleanUp.cs ` looks like this](https://github.com/elsa-workflows/elsa-core/blob/17ba58f0e406d2ec99782133e65258e92e97f78c/src/modules/retention/Elsa.Retention/Jobs/CleanupJob.cs#L46)
```csharp
var specification = new WorkflowCreatedBeforeSpecification(threshold);
```

Shouldn't it be like this?
```csharp
var specification = new WorkflowCreatedBeforeSpecification(threshold).And(_retentionFilterPipeline.GetSpecification());
```

Am I missing something?

**Comment by jdevillard** [comment]
Hello, 

Indeed, I tried to remember why I've done this and I thinks the reason is the following : 
- At the beginning of the work, I've create a new retentionSpecificationfilter to allow filtering on server side thinking that time was spent mostly in find
- Then I've done a v2 of the work to enhance the deletion AND the find.

I don't know why during my test I've remove the Specificationfilter, because, you're right without it we don't filter on the type of the workflow instance (or any filter passed in the configuraiton startup).

Thanks for pointing this. 
I'll try to review your commit asap.

**Comment by johnwc** [comment]
Is there an example of how to use the `IRetentionSpecificationFilter`?

**Comment by brantley-svt** [comment]
> Is there an example of how to use the IRetentionSpecificationFilter?

The sample server is in [src/samples/server/Elsa.Samples.Server.Host](https://github.com/elsa-workflows/elsa-core/tree/master/src/samples/server/Elsa.Samples.Server.Host).

You'll want to check out the [Startup.cs](https://github.com/elsa-workflows/elsa-core/blob/master/src/samples/server/Elsa.Samples.Server.Host/Startup.cs#L102-L111) and the [appsettings.json](https://github.com/elsa-workflows/elsa-core/blob/master/src/samples/server/Elsa.Samples.Server.Host/appsettings.json#L90-L94)
