### ISSUE TITLE
Proto Actor + Azure App Service (or perhaps better: AzureContainer Service)

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#3418]
Proto.Actor provides [cluster providers](https://proto.actor/docs/cluster/cluster-providers-net/) for the following platforms:

- Kubernetes
- Consul
- Amazon ECS

What's missing from this list is a provider that integrates with Azure App Service, which is necessary if we want to support Proto Actor hosted on this platform when scaling out into multiple nodes.

When there are multiple nodes, the cluster provider needs to be kept up to date about the available nodes in order to be able to spawn actors in the cluster.

A feature request to add this provider to Proto.Actor can be found here: https://github.com/asynkron/protoactor-dotnet/issues/1845

**Comment by sfmskywalker** [comment]
As discussed in https://github.com/asynkron/protoactor-dotnet/issues/1845, doing this for Azure app Service might be tricky - better would be to do it for Azure Container Services.

**Comment by gurkanguran** [comment]
Hi everyone,

I am currently implementing Azure Container Apps cluster provider by using the new sdk which is in preview. There is one issue I couldn't find a workaround yet. The issue is about registering the member as it is needed for Gossip Protocol. Please see this for the issue: https://github.com/microsoft/azure-container-apps/issues/521

I checked Orleans implementation but  I couldn't quite understand it. They were using azure table storage to integrate azure container apps somehow. So I could not get an idea from their implementation as I'm using Azure Container Apps SDK. I don't know what kind of design Orleans is using but it doesn't look like gossip protocol from Proto.Actor.

Can you please check the issue I'm having in the GitHub link I provided and suggest a solution if you can think of any? Thanks!
