### ISSUE TITLE
Is there a known way of adding a plugin to a preexisting activity?

### ISSUE THREAD

**Issue by DSPLX** [elsa-workflows/elsa-core#3433]
I want to slightly customize the display of an existing activity and add functionality to the textbox that is there. I see documentation on how to render my own control mechanism for custom inputs on custom activities, but what is the best practice for simply adjusting the display of an existing activity?

**Comment by tomy2105** [comment]
What I did, and I am not saying it is the only or the recommended way, is to remove builtin activity and make my own with same name and with builtin activity as its base class.
Then I've overridden the fields I wanted to change with my custom ones, and or added some functionality before/after the OnExecute of the base class.....

**Comment by tomy2105** [comment]
@DSPLX seems you edited your question "_Did you remove the built-in one by using NoCoreActivities or is there another way to remove an individual activity if needed?_". I guess you found your answer but adding my comment here for future....

It depends on the activity.
If the activity is NOT a "core" activity (core flow, primitives, workflows and signaling group if I recall correctly) then you can use `RemoveActivity` to remove activity already added by some other extension (like `AddHttpActivities`).

For example
```
            services
                .AddElsa(options => options
                    .AddHttpActivities(elsaSection.GetSection("Server").Bind)
                    .RemoveActivity<Elsa.Activities.Http.Redirect>()
                    .RemoveActivity<Elsa.Activities.Http.SendHttpRequest>() 
                );
```

However this doesn't work with "core" activities due to some internals (as far as I recall they are added after `RemoveActivity` is called.... see https://github.com/elsa-workflows/elsa-core/discussions/802 for details).
Hence `NoCoreActivities` was added so they (blame me :( ) are not added automatically but you add them yourself.
