### ISSUE TITLE
How to build workflows programmatically

### ISSUE THREAD

**Issue by pablotola** [elsa-workflows/elsa-core#3547]
Trying to build a workflow programmatically, but the lack of documentation is making this very hard.
How do I get a value from a previous activity output, I'm trying to use a javascript expression, but it is not working, is there a way to do it like if using the builder?
The reason I need to create the workflow programmatically is that we are using a custom build designer and I need to convert our definition to ELSA's.

Workflow definition (not working):
```
new ActivityDefinition
            {
                ActivityId = "activity-2",
                Type = nameof(Correlate),
                Properties = new List<ActivityDefinitionProperty>()
                {
                    ActivityDefinitionProperty.JavaScript(nameof(Correlate.Value), "activities.activity-1.Output().jobId")
                }
            },
```

Workflow builder:
```
builder
                .StartWith<HangfireJobActivity>(activity => activity
                    .Set(x => x.CompanyId, 1)
                    .Set(x => x.PartnerId, 1)
                    .Set(x => x.ObjectId, 1)
                    .Set(x => x.Database, "at-enterprise_dv")
                    .Set(x => x.JobName, "diJob")
                    .Set(x => x.Queue, "pablo")
                    .Set(x => x.ResumeSignalName, "continue"))
                .Correlate(context => context.GetInput<JobReturnResult>()?.jobId.ToString())
                .SignalReceived("continue")
                .WriteLine(context => context.CorrelationId)
                .Finish();
```

**Comment by sfmskywalker** [comment]
Sorry for the lack of documentation, we'll try to do better.

I've never modeled a workflow programmatically as in your first code snippet, but it should definitely be possible since that's what gets created internally when parsing a JSON document created by the designer.

You mentioned that your code isn't working - do you get any errors by any chance? Or the JS expression simply does not produce a value? Or it does produce a value, but it does not get assigned to the Correlate.Value property?

One thing I noticed about your JS expression is that it uses in invalid character for the `activity-1` name - when naming activities that you intend to reference from script, you should use valid JS identifiers (like how you would name variables).

Try renaming activity-1 to "activity1" so that the JS expression becomes: `"activities.activity1.Output().jobId"`

**Comment by pablotola** [comment]
Sorry for the late reply, renaming the activity name fixed the issue, also I am now using Liquid instead of javascript and creating the workflows programmatically using the "WorkflowDefinition" and "ActivityDefinition" classes.
