### ISSUE TITLE
Refactor Workflow Designer

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#362]
The v1 designer is too opiniated and has a hard-dependency on Bootstrap, making it hard to customize it for developers that want to reuse the designer in their own dashboard environments. Furthermore, it's proven difficult to package the component using React & Angular wrappers due to it having a dependency on Bootstrap StencilJS components.

To fix all of that, I propose that we refactor the designer to be a look-less component with default HTML templates that provides nothing but the following features:

* A canvas with panning/zooming support
* Rendering activity nodes and connections between them.
* Firing of events for the host to act upon, such as showing activity picker & activity editor.

I found that StencilJS is a great web component compiler to build HTML5 web components, but I am open to alternative suggestions. The important part is that it does not have any dependencies on frameworks like ReactJS, Angular, Vue et al. By keeping it clean, we make it possible to create wrappers around the designer for ReactJS, Angular Vue and others, including Blazor.

**Comment by jeremycook** [comment]
https://mithril.js.org/ may be worth considering. I realize mithril is a framework of sorts but it is light on ceremony and overhead. As a component author you write JavaScript/TypeScript/JSX, you choose. It is small enough that the mithril library could be privately bundled in the designer library and then the frameworkiness disappears. From there any kind of wrapper can be created for React, Vue, Blazor, etc. with the designer library being the only dependency.

**Comment by GeorgeS2019** [comment]
Please check this out! A [Blazor diagram](https://github.com/zHaytam/Blazor.Diagrams) framework with [clear separation of View and model ](https://github.com/zHaytam/Blazor.Diagrams/issues/41#issue-731349215)inspired by [React Diagram](https://github.com/projectstorm/react-diagrams). 

The custom Node and Link are HTML render fragments

Also see the [demo ](https://blazor-diagrams.zhaytam.com/demos/simple)and [a WIP database designer.](https://github.com/zHaytam/Blazor.DatabaseDesigner)

![image](https://user-images.githubusercontent.com/49812372/99247032-9cc4f380-2806-11eb-918f-712867510da2.png)

**Comment by sfmskywalker** [comment]
Blazor diagram looks very promising! Right now I crafted something myself by combining Blazor + JsPlumb (for drawing the connections), but I am thinking about making the designer experience pluggable, or at least configurable.

I have the following requirements for the Elsa designer:

* Free form drag & drop like [Flowy](https://alyssax.com/x/flowy/).
* Structured, automatic org tree layout like [HubSpot](https://www.hubspot.com/hs-fs/hubfs/Workflow%20Branch.png?width=3836&name=Workflow%20Branch.png).

Right now I'm working on the structured, automatic tree layout (check out [this gif recording](https://github.com/elsa-workflows/elsa-core/raw/feature/elsa-2.0/doc/elsa-2-dashboard-plus-designer.gif)).

Auto layout will be grand to also allow programmatic workflows (coded as .NET classes) to be displayed visually ❤️

**Comment by GeorgeS2019** [comment]
@sfmskywalker   The community needs a pluggable workflow designer.

Blazor Diagram recently implemented Drag & Drop. Please see [demo](https://blazor-diagrams.zhaytam.com/demos/simple).

**Comment by zHaytam** [comment]
Hello,

I'm glad you liked Blazor Diagrams! Concerning your requirements:

- The way I see it in Flowy, nodes automatically link to the others while dragging and the ports get colored when hovering too. This is, in theory, possible in Z.Blazor.Diagrams by removing the default `DragNodeSubManager` and creating your own. The library gives you a nice API with all the positions of nodes/ports, so you can know when the dragged node is close to a port and trigger events.
- Last week I created `Z.Blazor.Diagrams.Algorithms`, which is a separate project that will contain all the useful diagram algorithms. I do plan to integrate many structured layouts, especially the trees ones.

In order to stay in the same discussion, I will answer your other comment here too:

- Free links are a bit of a "problem". Either you can only do free links without arrows (you go from the center the nodes), or you already know the shape of your node (e.g. Rectangle), which then lets you know where/how you can create the link. Currently, my library doesn't handle this because I don't know which option to support. Nonetheless, I believe the API is mature enough to allow this kind of functionality to exist outside the library (e.g. custom `DragNewLinkSubManager`).

However, I do believe that if your designer uses an org tree layout, all your nodes will probably only have 4 ports (top, right, bottom & left), or at least that's what I see in most diagrams with this layout.

I hope this helps!

**Comment by GeorgeS2019** [comment]
@zHaytam  many of the issues deal with very useful feedback on how to improve the Workflow Designer [which I think could also make your Blazor Diagram more robust] e.g. [feedback1](https://github.com/elsa-workflows/elsa-core/issues/397#issue-716441655)

**Comment by tunechr** [comment]
Hi @sfmskywalker 

The Microsoft Bot Framework Composer is open source and allows for the visual construction of dialogue flows. 
The bot framework has similar concepts such as triggers and activities as part of a dialogue. 
It allows plugins etc. to add custom activities etc. 

https://github.com/microsoft/BotFramework-Composer

It might offer some ideas.

**Comment by sfmskywalker** [comment]
@tunechr this is great stuff. We'll release with an initial version that renders the workflow as an organizational tree & using jsPlumb to draw & create connections, but let's keep revisiting this. The MS Bot Framework Composer looks particularly awesome. Do you know if it's possible to reuse just the designer without any of the Bot specific things?

**Comment by sfmskywalker** [comment]
Closing this issue now that we already have a V2 designer for the V2 milestone.
