### ISSUE TITLE
How can I make a workflow by JSON

### ISSUE THREAD

**Issue by Assari87** [elsa-workflows/elsa-core#3653]
Hi everyone,

I want to make a workflow by JSON. I need a reference that explains how can I create all activities in JSON strings.
For example, how can I set condition expression in Json? I couldn't find a property for that.
It is a sample that I got from Elsa Designer:
activities:
{
      "$id": "20",
      "activityId": "activity-9",
      "type": "If",
      "persistWorkflow": false,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "properties": [],
      "propertyStorageProviders": {
        "$id": "21"
      }
}
...
connections:
 {
      "$id": "50",
      "sourceActivityId": "activity-9",
      "targetActivityId": "activity-10",
      "outcome": "True"
},
{
      "$id": "51",
      "sourceActivityId": "activity-9",
      "targetActivityId": "activity-12",
      "outcome": "False"
}
@sfmskywalker

**Comment by issacclee** [comment]
seems like the document regarding JSON workflows has been vacant for ages, is there any reason for that? maybe we as community can help out a bit, if the core contributors can illustrate out the necessary work that needs to be done for us to write the document of composing workflow via JSON.

**Comment by issacclee** [comment]
> Hi @issacclee, the primary reason is that the JSON produced by the designer is not at all user friendly and that I would rather design a user-friendly structure for those who want to define workflows manually using JSON syntax. This requires some design and implementation work, which we have to balance against other roadmap items within limited bandwidth.
> 
> To get that going, I suggest we first start designing the syntax. For example, let's say we have a workflow with two activities that are connected to one another. A simple format might look like this:
> 
> ```json
> {
>   "activities": [
>     {
>       "name": "WriteLine1",
>       "type": "WriteLine",
>       "text": "Hello world!"
>     },
>     {
>       "name": "WriteLine2",
>       "type": "WriteLine",
>       "text": "Goodbye cruel world..."
>     }
>   ],
>   "connections": [
>     {
>       "source": "WriteLine1",
>       "target": "WriteLine2"
>     }
>   ]
> }
> ```
> 
> We would have to try out all the different scenarios we can think of to try and capture as many cases as possible. When we think it looks good, then we start implementing a custom workflow provider that can source workflows from these JSON formatted files.

Thanks for the clarification, it make sense to design a more user-friendly syntax and structure before open source it to the public. There's a [project ](https://smithsonian.github.io/dpo-cook/docs/writing-recipes/)developed by folks at smithsonian, which is mainly used to compose workflow that would invoke extensive amount of third party executable to produce 3d digital assets for museum and education. They  have this concept called recipes, which is essentially a DSL made with json schema. Could serve us as a real world example of design workflow with JSON schema. Do you guys know any other workflow framework with similar function?

**Comment by issacclee** [comment]
workflow core has something like [this](https://workflow-core.readthedocs.io/en/latest/json-yaml/). which looks to be just JSON representation of composing workflow instance in C#.

**Comment by vikash-soc** [comment]
I think decision should be simple here. Match the json structure used by n8n. Its an open source mature product with large community and has many workflows available. It will also instantly add a lot of members to the community, will save developer efforts. 
ELSAs performance is much better than n8n and many people will be happy to migrate from as soon as they learn about this.

**Comment by vikash-soc** [comment]
**From Gemini**

While it's theoretically possible to create a *converter* that translates some elements between ELSA Workflow and n8n JSON structures, a **true one-to-one mapping is generally not feasible or practical due to fundamental architectural and philosophical differences between the two platforms.**

Here's why a direct one-to-one mapping is problematic and what a conversion process would entail:

### Why a One-to-One Mapping is Difficult:

1.  **Fundamental Design Paradigms:**
    * **ELSA (Strongly Typed, .NET-centric):** ELSA workflows are essentially state machines or flowcharts built upon strongly-typed .NET activities. Their JSON reflects this, with explicit `type` definitions mapping to .NET classes and `properties` having `typeName` and `expression` objects.
    * **n8n (Node-based, Integration-centric):** n8n workflows are directed acyclic graphs (DAGs) of nodes, primarily designed for integrations. Its nodes often encapsulate complex logic for interacting with external APIs, and their `parameters` are more loosely typed in the JSON, relying on the node's internal JavaScript implementation.

2.  **Activity/Node Granularity and Abstraction:**
    * **ELSA:** Activities can be very granular (e.g., `WriteLine`, `SetVariable`, `HttpEndpoint`) or high-level (e.g., `Flowchart`, `Sequence`). Many ELSA activities have direct counterparts in .NET framework logic.
    * **n8n:** Nodes often represent higher-level integrations (e.g., "Google Sheets Node," "Slack Node," "HTTP Request Node"). While there are basic control flow nodes, a single n8n node might perform multiple steps that would be separate activities in ELSA (e.g., an n8n "Google Sheets" node might handle authentication, reading, and writing, while in ELSA, these might be separate custom activities or calls).

3.  **Expression and Data Handling:**
    * **ELSA:** Uses various expression types (`JavaScript`, `Liquid`, `Variable`, `Output`) with explicit `typeName` for strong data typing and runtime evaluation within the .NET context.
    * **n8n:** Relies heavily on Handlebars-like expressions (`{{ $json.someProperty }}`) embedded directly in parameter values for data passing between nodes. The data is typically dynamic JSON. The type inference and coercion are handled by the node's internal logic.

4.  **Flow Control Mechanisms:**
    * **ELSA:** Explicit `connections` with `outcome` values, and structured flow control activities like `Flowchart`, `Sequence`, `Fork`, `Join`. This allows for complex branching and merging.
    * **n8n:** Often simpler sequential flow with `next` pointers. While it has branching (`IF` node) and loop constructs, the visual nature and data flow might be represented differently in JSON than ELSA's explicit graph structure.

5.  **State Management and Persistence:**
    * **ELSA:** Detailed `persistenceBehavior`, `workflowContext`, and variables define how the workflow state is managed and persisted. This is crucial for long-running workflows.
    * **n8n:** Node execution is typically atomic. While it has state, its persistence mechanisms are designed for efficient execution of short-lived automation tasks. Long-running processes in n8n might rely on external triggers or specific node types.

6.  **Extensibility and Customization:**
    * **ELSA:** Extensibility is primarily through writing C# code for custom activities, services, and extensions.
    * **n8n:** Extensibility is primarily through writing JavaScript for custom nodes or using "Code" nodes within the workflow.

### What a "Conversion" Would Entail (and its Limitations):

A conversion tool would essentially involve mapping common concepts and translating known patterns, but it would almost certainly require human intervention for complex workflows.

**ELSA to n8n (Potential Challenges):**

* **Mapping ELSA Activities to n8n Nodes:** A `WriteLine` in ELSA might map to a "Log" node in n8n or simply be omitted if its purpose is solely for internal logging. An `HttpEndpoint` would map to an n8n "Webhook" node. A custom ELSA activity would likely require a custom n8n node or a "Code" node.
* **Translating Expressions:** ELSA's Liquid/JavaScript expressions would need to be rewritten into n8n's expression syntax. This can be complex, especially with type conversions.
* **Handling ELSA's Strong Typing:** n8n is more flexible with data types, so explicit type conversions from ELSA might be lost or handled implicitly.
* **Complex Control Flow:** ELSA's `Flowchart` with intricate `connections` and `outcome` logic might be challenging to represent directly in n8n's more linear or branching structures without creating very verbose n8n workflows.
* **Persistence and Context:** ELSA's `workflowContext` and advanced persistence behaviors have no direct equivalent in n8n's JSON structure.

**n8n to ELSA (Potential Challenges):**

* **Mapping n8n Nodes to ELSA Activities:** An n8n "Google Sheets" node would likely need to be broken down into multiple ELSA activities (e.g., "Authenticate Google," "Read Google Sheet," "Write Google Sheet"), possibly requiring custom ELSA activities for each.
* **Data Flow to Explicit Properties:** n8n's implicit data flow via expressions (`{{ $json.body.message }}`) would need to be translated into ELSA's explicit `Input` properties for activities or `Variable` assignments.
* **UI Position Data:** n8n's `position` data is irrelevant for ELSA's execution logic.
* **Credential Abstraction:** n8n's credential management is external; ELSA might need more explicit configuration within the workflow or via external configuration for credentials.

### Conclusion:

While you *can* write code to parse one format and generate the other, don't expect a perfect, automated, one-to-one translation for complex workflows.

It's more accurate to say that you could create a **"transpiler" or "adapter"** that attempts to convert common patterns, but it would inevitably involve:
* **Loss of fidelity** for platform-specific features.
* **Simplifications** in the conversion process.
* **Manual re-engineering** or refinement for anything beyond basic linear flows.
* **Deep understanding** of both platforms' capabilities and limitations.

For practical purposes, if a workflow needs to move from one platform to another, it's often more efficient and reliable to **re-implement it manually** on the target platform, leveraging its native strengths and best practices.
A "one-to-one mapping" between ELSA and n8n JSON structures is **not generally possible in a straightforward, automated, or universally complete way.**

Here's why, and what kind of "mapping" *might* be achievable:

### Why a True One-to-One Mapping is Not Feasible

1.  **Fundamental Architectural Differences:**
    * **ELSA: .NET-centric Workflow Engine:** ELSA is a .NET library designed for embedding workflows within .NET applications. Its activities directly map to .NET classes, and its JSON structure reflects this strong typing, object-oriented approach, and focus on long-running business processes.
    * **n8n: Node-based Automation Platform:** n8n is a standalone application (though it can be self-hosted) built for connecting APIs and services with a strong emphasis on a visual, low-code/no-code experience. Its "nodes" are designed to encapsulate specific integration logic.

2.  **Activity/Node Parity:**
    * **ELSA Activities:** Focus on core workflow constructs (e.g., `Flowchart`, `Sequence`, `Fork`, `Join`, `WriteLine`, `HttpRequest`) and generic programming concepts (variables, expressions, custom C# activities).
    * **n8n Nodes:** Extensive library of pre-built integrations for specific services (e.g., "Google Sheets Node", "Slack Node", "Stripe Node"). While both have an "HTTP Request" equivalent, n8n often has dedicated nodes for specific API calls, whereas ELSA might require more manual configuration of a generic `HttpRequest` activity.
    * **Customization:** While both allow custom elements, ELSA's custom activities are typically written in C#, deeply integrated into the .NET project. n8n's custom nodes are often JavaScript-based and integrated via its own node system.

3.  **Expression Language Differences:**
    * **ELSA:** Uses various expression types like `Literal`, `JavaScript`, `Liquid`, `Variable`, `Output`. These are often more "programming language-like" and strongly typed.
    * **n8n:** Primarily uses its own expression syntax (e.g., `{{ $json.body.message }}`) which is designed for referencing data from previous nodes and is typically less focused on general-purpose programming logic within the JSON itself (though JavaScript can be used in "Code" nodes).

4.  **Data Flow vs. Control Flow Emphasis:**
    * **ELSA:** Strong emphasis on both control flow (sequences, flowcharts, branching, looping) and data flow (variables, activity outputs).
    * **n8n:** While it has control flow, its primary strength lies in seamless data passing between nodes, often with automatic data transformation.

5.  **Runtime and State Management:**
    * **ELSA:** JSON includes details about `persistenceBehavior`, `workflowContext`, which are critical for ELSA's durable workflow execution and state management. These concepts don't have direct, equivalent representations in n8n's exported JSON.

### What Kind of "Mapping" Might Be Achievable (and how)

Despite the lack of a direct one-to-one mapping, you could build a **conversion tool or process** that attempts to translate *some* workflows between the two, but it would always involve compromises and manual intervention.

Here's how such a mapping might work conceptually, and its limitations:

1.  **Activity/Node Lookup and Translation:**
    * **Identify Common Functionality:** For activities/nodes that perform similar high-level tasks (e.g., "Make an HTTP Request", "Send an Email", "Write to Console/Log"), you'd map them.
    * **Parameter Translation:** For each mapped activity/node, you'd need to translate its properties/parameters. This is where the biggest challenges lie:
        * **Type Mismatch:** An ELSA `String` property might map to an n8n text field, but an ELSA `ICollection<string>` might need a custom n8n JSON array input.
        * **Expression Conversion:** Converting ELSA's `JavaScript` or `Liquid` expressions to n8n's `{{ ... }}` syntax or vice-versa would be complex and often require writing custom parsing and generation logic.
        * **Missing Equivalent Functionality:** An ELSA `Fork` activity has a clear purpose. An n8n "Split In Batches" or "Merge" node might achieve *similar* results in certain scenarios, but their exact behavior and configuration will differ.
    * **Custom Activities/Nodes:** If a workflow uses custom activities in ELSA or custom nodes in n8n, there's *no automated way* to translate them. They would need to be re-implemented in the target platform.

2.  **Connection/Flow Translation:**
    * **ELSA's Explicit Connections:** ELSA's `sourceActivityId`, `targetActivityId`, `outcome` can generally be translated to n8n's `connections` or the implicit `next` pointers, but handling complex branching based on outcomes would require careful mapping to n8n's conditional nodes or "IF" logic.
    * **n8n's Visual Layout:** n8n's JSON includes `position` data. ELSA's JSON doesn't. A converter from ELSA to n8n would need to intelligently (or randomly) assign positions for visual layout.

3.  **Data Handling Translation:**
    * **Variables:** ELSA `variables` could potentially be mapped to n8n's workflow variables, but their scope and usage might need careful consideration.
    * **Outputs:** ELSA's activity outputs are explicitly referenced. n8n's data flow is more implicit (the output of one node becomes the input for the next, often accessed via `$json` or `$node` variables).

4.  **Workflow Metadata Translation:**
    * Basic metadata like `name`, `description` can be easily mapped.
    * ELSA-specific metadata like `isLatest`, `isPublished`, `persistenceBehavior`, `workflowContext` have no direct equivalents in n8n's export and would be lost or ignored.

**Practical Implications:**

* **Manual Effort:** Any significant conversion would involve a lot of manual re-creation and testing, especially for workflows with complex logic, custom components, or unique data transformations.
* **Best Effort:** A converter would likely be "best effort," translating what it can and flagging what it cannot (e.g., "This ELSA activity type has no direct n8n equivalent, manual intervention required").
* **Loss of Fidelity:** Some nuances, especially related to execution semantics, error handling, and state management, might be lost or behave differently in the translated workflow.
