### ISSUE TITLE
IfActivity not working after the retry Elsa 2.9.2.

### ISSUE THREAD

**Issue by tsoG2000** [elsa-workflows/elsa-core#3669]
Hi @sfmskywalker ,

We have serious bug (Elsa 2.9.2.) on production environment with If activity that changes workflow status to finish after the retry and skips execution logic (ignores input true/false).

Here is an example of this behaviour.

1. In first custom activity "SetOutputTrueOrFalse" we set Output to true/false regarding context variable "ContextOutput" value. In this case it is false because "ContextOutput" is empty in the first pass.
2. IfActivity checks Input, if true goes to "DoneActivity" if false goes to "ThrowExActivity". In this case we go to "ThrowExActivity" that we set to throw an exception in first pass, emulating some error like trying to access an unavailable web service.
3. After "ThrowExActivity" goes to faulted state we comment exception throwing line emulating web service that is now working, and then we hit retry of this workflow. "ThrowExActivity" executes (this time without error) and sets the context variable "ContextOutput" to true.
4. Subsequent activity is "SetOutputTrueOrFalse" again setting the Output from the value of "ContextOutput" variable in this case true.
5. IfActivity here should check Input and in this case because Input is true next activity should be "DoneActivity", but this flow never happens. Here is where wokflow finishes (workflow status is set to finish) and only this Ifactivity is executed, input is ignored.

Is there something we are doing wrong or is this expected IfActivity behaviour? Is there some fix or workaround?
We did try to use context variable instead of Input in IfActivity condition, but that did not help.

Workflow:
![image](https://user-images.githubusercontent.com/92223522/216558379-a869c205-de13-449e-9dcb-e9541d6b427c.png)

SetOutputTrueOrFalse activity:
![image](https://user-images.githubusercontent.com/92223522/216558637-010c13f9-89e4-446f-8167-566b33c59d4e.png)

ThrowExActivity activity:
![image](https://user-images.githubusercontent.com/92223522/216558875-1513ff10-3dce-477e-8a6f-387eba204eba.png)

DoneActivity activity:
![image](https://user-images.githubusercontent.com/92223522/216559094-8cc43f62-238c-4b44-9823-5fd4024a4986.png)

Dashboard view:

![image](https://user-images.githubusercontent.com/92223522/216559522-bf4a58bd-e879-4c9e-aac3-72b356125f79.png)

![image](https://user-images.githubusercontent.com/92223522/216559641-625851bf-cddd-4877-88ba-4977ca5290a0.png)

![image](https://user-images.githubusercontent.com/92223522/216559721-1aae4d99-4b26-48ea-b192-f3fad85855b1.png)

Thank you in advance for your time and attention to this pressing matter. I look forward to your response.

Kind regards,
tsoG

**Comment by sfmskywalker** [comment]
Hi @tsoG2000 , this certainly looks like a bug. I think you're right that the expected behavior is for the If activity to simply run again and schedule the True outcome when the flow executes  for the second time.

Fixing this requires some investigation and some time to allocate. Unfortunately, I am kinda swamped today.
What you could try in the meantime is making sure that the workflow starts with an extra activity, like a dummy WriteLine activity. I don't know if this is the issue, but usually you don't want an Elsa 2 workflow to have no clear root node. Because your workflow currently loops back to the start node (SetOutputTrueOrFalse), there's no clear starting point. The workflow will take the first activity in this case, but maybe it causes a problem down the line when repeating.

It's a wild guess and I don't think if it has to do with the issue, but it shouldn't hurt to give it a try.

If the issue persists, then the quickest way I might be able to troubleshoot this is to receive a project that reproduces this behavior (saves me some time to set it up myself).

**Comment by tsoG2000** [comment]
Hi @sfmskywalker , we tried with root activity, but it didn't help:

![image](https://user-images.githubusercontent.com/92223522/216597919-5a4f7e24-c2b9-47ae-a1ec-bde773390983.png)

![image](https://user-images.githubusercontent.com/92223522/216598010-d723bd4e-0276-42aa-9c0d-851abf0f2bad.png)

**Comment by tsoG2000** [comment]
> 
> If the issue persists, then the quickest way I might be able to troubleshoot this is to receive a project that reproduces this behavior (saves me some time to set it up myself).

@sfmskywalker here is example repo:

https://github.com/tsoG2000/Elsa_Bug

**Comment by sfmskywalker** [comment]
@tsoG2000 I found the issue and created a PR with a fix here: #3693
I'll merge it soon and make it part of the upcoming 2.11 release (tomorrow or during the weekend).

I realize you're on 2.9, but I am hesitant to including this behavioral change in that version, so hopefully you can upgrade to 2.11.

**Comment by tsoG2000** [comment]
Hi @sfmskywalker ,

Great news! We tried this fix from your commit on provided example and it works fine. Yeah, we can upgrade to 2.11 and we hope this release will happen on weekend, so we can test it on our project and deploy it on production as soon as possible.
Thank You!
