### ISSUE TITLE
IWorkflowInstancesApi.ListAsync Bug. PagedList vs IEnumerable

### ISSUE THREAD

**Issue by KeesSchoutenEasySystems** [elsa-workflows/elsa-core#3783]
The method "ListAsync" in interface "IWorkflowInstancesApi", returns an **PagedList<WorkflowBlueprintSummary>** but the actual API implementation returns an IEnumerable.

This results in a serialization exception.

**Comment by dammitjanet** [comment]
There is actually another issue with this call, the WorkflowBlueprintSummary needs to be updated also, it appears to be out date

specifically, the fields VersionId is missing, and the field isEnabled is no longer present and should be replaced with isDisabled

Q: should this call return a PagedList, or just a List given that its technically ListAll() I'd expect the latter but that might just be my unfamiliarity withe the codebase.  The ElsaClient interface IWorkflowRegistryApi has the paging values, but the Handler doesn't accept them

If the former (PagedList), then the Handle method on the call needs to be updated with the page properties, otherwise it should be a simple change to the definition

~ Elsa.Server.Api\Endpoints\WorkflowRegistry\ListAll.cs
`[ProducesResponseType(StatusCodes.Status200OK, Type = typeof(PagedList<WorkflowBlueprintSummaryModel>))]`
becomes
`[ProducesResponseType(StatusCodes.Status200OK, Type = typeof(List<WorkflowBlueprintSummaryModel>))]`

and
~ Elsa.Client\Services\IWorkflowRegistryApi.cs
```
        Task<PagedList<WorkflowBlueprintSummary>> ListAsync(int? page = default, int? pageSize = default, VersionOptions? versionOptions = default, CancellationToken cancellationToken = default);
```

becomes
```
        Task<List<WorkflowBlueprintSummary>> ListAsync(VersionOptions? versionOptions = default, CancellationToken cancellationToken = default);
```

If I can get some steer on what the expected process should be e.g. PagedList/List I can PR any changes

**Comment by sfmskywalker** [comment]
Hey there,

Just wanted to let you know that the API client has been updated to match the server-side models. This should address the discrepancies you pointed out with the `IWorkflowInstancesApi.ListAsync` method. Please pull the latest changes and let us know if you encounter any issues.

Thanks for bringing this to our attention!
