### ISSUE TITLE
Call Event Activity

### ISSUE THREAD

**Issue by sagargolu** [elsa-workflows/elsa-core#3809]
Hi @sfmskywalker,

I am looking for call of Event activity. But don't see any article to trigger it. On v2 version, we were able to call/trigger custom route it using following url "localhost/v1/custom-signals/{ActivityName}/Execute". But we are not able to call even inbuilt Event Activity. Would you please help me for this? Can you share us sample request for calling event for v3 version?

**Comment by sagargolu** [comment]
@sfmskywalker , It would be good if you can help on this as this is quite urgent for us. How can we call event activity using postman or browser? as mentioned in above comment we can call it using custom-signals url path.

**Comment by sfmskywalker** [comment]
Sure! One way to do it in V3 is to publish an event using the *Publish* activity. Another way is to use the underlying API `IEventPublisher` in the `Elsa.Workflows.Runtime.Contracts` namespace (bot to be confused with the one from `Elsa.Mediator.Contracts`).

The following REST API uses `IEventPublisher` internally:

```
POST /events/{eventName}/trigger
```

Make sure to include a bearer token. Elsa doesn't currently offer API keys (but it will), so for now, to generate an access token, simply invoke the following request:

```
curl --location 'https://localhost:5001/elsa/api/identity/login' \
--header 'Content-Type: application/json' \
--data '{
    "username": "admin",
    "password": "password"
}'
```

Here is a sample request that triggers an event called `order-processed`

```bash
curl --location 'https://localhost:5001/elsa/api/events/order-processed/trigger' \
--header 'Authorization: Bearer {access_token}' \
--header 'Content-Type: application/json' 
```

And here is what that workflow might look like:

<img width="883" alt="image" src="https://user-images.githubusercontent.com/938393/226324989-97719a80-2a32-48a1-a95d-806d4a408aac.png">

When using the REST API, right now it only supports "dispatch" mode, which means that the workflow will execute in a background thread, e.g. a message worker. I'll add "execute" mode as well, allowing you to e.g. respond with an HTTP Response activity. Until then, you can implement your own endpoint controller that uses `IEventPublisher` directly, and use its `PublishAsync` method to publish an event.

In the sample workflow above I demonstrated the Event activity as a trigger that starts the workflow, but you can also use it as a blocking activity.

For example, maybe you have a workflow that was started by your application, and then waits for an event to occur.
Maybe something like this:

<img width="755" alt="image" src="https://user-images.githubusercontent.com/938393/226326193-c146e019-3ee2-43cd-94c3-0f431c4c470c.png">


Here, your application might kick off this workflow using the `/workflow-definitions/{definitionId}/execute` endpoint, or even directly using the `IWorkflowRuntime` service.

As soon as workflow execution encounters the event activity, it will block further execution until you trigger the event, causing the workflow to continue.

It's also possible to send input to the event via the REST API, but while trying it out I realized that the endpoint doesn't currently support that. I will push a fix for that, so that you might do something like this to send input to your event:

```bash
curl --location 'https://localhost:5001/elsa/api/events/order-submitted/trigger' \
--header 'Authorization: Bearer {access_token}' \
--header 'Content-Type: application/json' \
--data '{
    "input": {
        "order": {
            "id": "1",
            "product": "pizza"
        }
    }
}'
```

The Event activity can then capture that input into a variable called `Order` - the name of the variable must match the name of the input key ("order", case insensitive).

<img width="1373" alt="image" src="https://user-images.githubusercontent.com/938393/226329877-f760df4d-96c6-4da4-a969-5217368404be.png">


You can then use the `Order` variable in subsequent activities, for example like this:

<img width="1365" alt="image" src="https://user-images.githubusercontent.com/938393/226330048-8d86e45f-8eb8-4fda-88c0-dcaae987ee5c.png">

The workflow will then print the following to the console:

<img width="959" alt="image" src="https://user-images.githubusercontent.com/938393/226330284-9c6da6e1-af0b-409b-b9ac-2919904c90be.png">

Note: this will work as soon as I pushed the update I mentioned earlier, which will happen today.

**Comment by sagargolu** [comment]
@sfmskywalker,
Thanks for the update, I am getting trying to use event as a blocking activity. but it is giving me 401 error. So do we need to login every time when we call the event? Also what to do if we have multiple instances running? What do we need to use to call the particular instance?
Also workflow is not storing CorrelationId as well in the database. So is there any configuration for that? For your reference I am attaching database screenshot. 
![image](https://user-images.githubusercontent.com/79979623/226339595-05b4ca71-a5fa-404a-a5f2-2ba656989f88.png)

**Comment by sfmskywalker** [comment]
Sure. To assign a correlation ID to the workflow, use the **correlate** activity (found in the **Primitives** category).
For example:

<img width="1812" alt="image" src="https://user-images.githubusercontent.com/938393/226473006-884b0dbe-bbcb-4abb-985d-ec09ac38a674.png">

Notice that I'm using the `getGuidString()` JS function to generate a new GUID in string format.
When I now execute this workflow, it will associate a random GUID as the correlation ID and block on the Event activity.

I can resume this particular workflow instance by sending the following request:

```bash
curl --location 'https://localhost:5001/elsa/api/events/order-submitted/trigger' \
--header 'Authorization: Bearer {access_token}' \
--header 'Content-Type: application/json' \
--data '{
    "correlationId": "{correlation_id}"
}'
```

Alternatively, based on your earlier feedback, you can now also provide the workflow instance directly:

```bash
curl --location 'https://localhost:5001/elsa/api/events/order-submitted/trigger' \
--header 'Authorization: Bearer {access_token}' \
--header 'Content-Type: application/json' \
--data '{
    "workflowInstanceId": "{workflow_instance_id}"
}'
```

This way, you don't have to use a correlation ID.

I attached the workflow I have tested with for reference. Make sure to reference the latest packages (186 or later).

[workflow-definition-56a1e58410f649fbab9de1f39490547f.json.zip](https://github.com/elsa-workflows/elsa-core/files/11023346/workflow-definition-56a1e58410f649fbab9de1f39490547f.json.zip)

**Comment by sagargolu** [comment]
@sfmskywalker ,
Thanks for the quick solution on this... now, we are able to run the workflow in v3 version. I wants to share some screenshot where actually, we are looking for the improvements in UI and workflow progress. Once you look into issue that I have created, [#3835](https://github.com/elsa-workflows/elsa-core/issues/3835).

**Comment by sagargolu** [comment]
@sfmskywalker , We are seeing one issue while storing output result in variable. We don't want to use exact same variable name for storing any payload send in "Input" parameter.

For example: 
"input": {
        "testData":{
            "loanType":"FHA",
            "FileNumber":"",
            "CaseNumber":"",
            "CaseStatus":"",
            "Attorney":"",
            "ReferralCode":"",
            "BarNumber":"",
            "PartyType":"Borrower"
        }
    } 

if we consider that to get the pay load, we have to declare "payLoad" variable and we can access it using getPayLoad(). But what if we don't want to use variable and want to access that payload directly based on activity. Because in V2, we were able to access it directly without storing it in variable like **activityName.Output**  .

If you give us work around on this than it will help us much more. Thanks

**Comment by sfmskywalker** [comment]
I see, you want to be able to use an activity's output directly from another activity, instead of first assigning the output to a variable.

That makes sense, but there's one caveat: the output of an activity is ephemeral, which means it won't exist as soon as the activity execution context goes out of scope. Which is why you need to capture it using a variable, whose lifetime can be configured.

That being said, I do think it can offer a more frictionless experience if we can access activity output directly.

One thing to consider, like in Elsa 2, is the persistence of outputs. For example, if an activity outputs a non-serializable value, or a value that is very large, like a 50MB file, we don't want that to be persisted as part of the workflow instance JSON itself.
So, by default, I think this output must remain ephemeral.

**Comment by RenX313** [comment]
I tried the exact same thing on the current version, but I get "Cannot read property of null" errors.
