### ISSUE TITLE
Elsa blocked if MongoDb persistence is unable to save due to dimensions

### ISSUE THREAD

**Issue by alkampfergit** [elsa-workflows/elsa-core#3849]
We have workflows that download emails and perform various operation on them. We received an email with html content really big (24 mb of HTML with embedded images in BASE64). Now I know that this is a real edge-case scenario, but since the Content of the email is used as debug variable and as input variable, MongoDb provider was unable to save due to dimension (max mongodb document size is 16 MB).

After the error everything seems to be stopped, because it continuously trying to resume the workflow, then save progress, then crash and back to square 1.

We fixed for now using a different variable serialzier that persist big data into a IBlobStorage engine, but I think that a better solution would be saving workflow instance differently in mongodb, maybe using GridFS. 

Anyone else here using MongoDb had similar problems?

**Comment by sfmskywalker** [comment]
For Elsa 3, this is fixed by letting input & output not be persisted as part of the workflow instance. Instead, if you want to persist e.g. files, you have to do it yourself (or at least, explicitly using some activity or setting).

Elsa 3 also adds an Elasticsearch implementation for storing workflow instances. However, I would still advise against storing files inside of a workflow instance, and instead store them in blob storage like you do now.

I fully realize you may not be ready to switch to Elsa 3 (Elsa 3 itself is not even ready for prime time), but I am mentioning this just to say that the issue is (will be) fixed.

We can still try to make this better in Elsa 2, but at the same time, this limitation is one of the reasons Elsa 3 has been rewritten from the ground up.

**Comment by alkampfergit** [comment]
Actually I have a workaround I'll try to do a pull request after some code polishing. (the workaround is storing serialized variables in a separate gridfs if size exceed a limit).
