### ISSUE TITLE
Main workflow's endpoint is getting override with subworkflow's endpoint in v3

### ISSUE THREAD

**Issue by sagargolu** [elsa-workflows/elsa-core#3850]
Hi @sfmskywalker ,

I am attaching some of the video references to see why main workflows httpendpoint's path value is getting override with the sub workflow's httpendpoint path value after publishing. I have given following thing in both the workflow,

**Title Workflow : (Child workflow)**
I have put httpendpoint with path value "/titlewf"

**Main Workflow :**
I have put httpendpoint with path value "/mainwf". Now, I am adding title workflow into main workflow and connecting with the another activity. After publishing the main workflow, I can see main workflow's httpendpoint value changed automatically. (Referencing video). So is it intentional or just a glitch?

[scrnli_3_29_2023_8-11-42 AM.zip](https://github.com/elsa-workflows/elsa-core/files/11095991/scrnli_3_29_2023_8-11-42.AM.zip)

**Comment by sfmskywalker** [comment]
Hi @sagargolu

Thank you for the great description and video to clarify your point. That is indeed intended behavior. Here's what is going on:

- The sub workflow has its HTTP Endpoint activity configured as "Can start workflow".
- The main workflow consumes this sub workflow **as an activity** - this is important, because it means that functionally, all activities of the sub workflow are visible to the main workflow, which also means that **any trigger in the sub workflow** will be discovered and registered.
- In effect, your main workflow now has two HTTP Endpoint triggers.

When using sub workflows as activities, it is important to realize they are not actually invoked as separate workflows, but merely as regular activities (even though they are composites).

There are two ways to go about this:

1. Simply uncheck the HTTP Endpoint in the sub workflow as "can start workflows", publish the sub workflow and make sure to upgrade the activity in the main workflow.
2. Invoke the sub workflow using Dispatch Workflow.
