### ISSUE TITLE
Elsa blocks hangfire startup in my case

### ISSUE THREAD

**Issue by hakancunier** [elsa-workflows/elsa-core#3861]
Hello,

My development node must be started with Hangfire and Elsa. So i tried this:

services.AddHangfire(configuration => configuration
                    .SetDataCompatibilityLevel(CompatibilityLevel.Version_170)
                    .UseSimpleAssemblyNameTypeSerializer()
                    .UseRecommendedSerializerSettings(settings => settings.ConfigureForNodaTime(DateTimeZoneProviders.Tzdb))
                    .UsePostgreSqlStorage(siteConn));
services.AddHangfireServer((sp, options) =>
{
    options.WorkerCount = 1;
});
services.AddElsa(elsa => {
    elsa.UseEntityFrameworkPersistence(ef => ef.UsePostgreSql(siteConn))
    .AddHangfireTemporalActivities()
    .AddActivity<RunJavaScript>()
    .AddActivity<MyUserTask>()
    .AddEmailActivities(opts =>
    {
        opts.DefaultSender....
    });
});

But unfortunately hangfire doesnt fire jobs. I realized it creates postgresql objects then gets no action. 
IF I REMOVE services.AddElsa..... OR REPLACE IT WITH services.AddElsaCore.... NO PROBLEM HANGFIRE WORKS.

Whats the problem?

**Comment by sfmskywalker** [comment]
It's hard to say, because from what I can tell, you are setting it up correctly. The `https://www.youtube.com/live/uragYmFhNIk?feature=share` should indeed be without providing any arguments to ensure it doesn't internally also add hangfire services.

Maybe you can clone the repo an try to debug with the full source code to see whats going on.

**Comment by hakancunier** [comment]
I believe the problem is with src/activities/Elsa.Activities.Temporal.Hangfire/Extensions/TimersOptionsExtensions.cs
