### ISSUE TITLE
Schema Name editable in V3

### ISSUE THREAD

**Issue by borjaferv** [elsa-workflows/elsa-core#3922]
In existing systems, especially databases like Oracle, it is sometimes impossible to get a fixed schema name for applications. It would be great to have some way to override the Schema Name in the contexts.

This would imply the need to manually generate the migrations initially as is currently done for Elsa 2

**Comment by borjaferv** [comment]
Hi @sfmskywalker  , I have thought about implementing the way to establish the name of the scheme based on the issue that I opened.
I have been looking at the code for elsa 3 and the truth is that I am a bit blocked. Could you guide me a bit on how you would propose a solution so that when you configure Elsa and add entity framework, pass this type of configuration as the schema name?

**Comment by sfmskywalker** [comment]
Sure!

I would probably do one, or all, of the following:

1. I would make the ElsaSchema property a public, static, mutable property, with a default value of "Elsa". This is the easiest approach, allowing applications to set a different value, or perhaps even nullify it.
2. I would try and see if it is possible to accept a custom options object in the constructor of the various DbContext types. This options object would carry the desired schema name (if any). This should be possible by leveraging an overload of the `AddDbContextFactory<T>` method, which accepts a second generic type argument: `AddDbContextFactory<T, TFactory>`. This should allow us to provide a custom db context factory implementation that can pass in the custom options object. The class constructor would inject IOptions<T> containing the custom options, which can be configured from the Program class (e.g. `services.Configure<ElsaDbContextOptions>(configuration.Get("ElsaDbContext"))`).
3. Although option 2 should work when using `AddDbContextFactory<T>()`, the `AddPooledDbContextFactory` method doesn't seem to allow you to provide a custom factory. There's probably a good reason for that, but I'm not sure what this might be. @craigfowler might probably explain this in greater detail. So perhaps, instead of option 2 (or in addition to), we might explore the option of implementing a custom `IDbContextOptionsExtension`, which is typically used by EF Core. providers, according to documentation. I suspect we might be able to (ab)use it for receiving a custom schema name too.

The above is all about getting a custom schema name into the DbContext classes. Once we have that, configuring the schema is easy (that code already exists), but we should update it to simply **not** set the schema if the configure value is null or empty.

**Comment by craigfowler** [comment]
It doesn't let you pass in a custom factory.  Wssentially that's because _it is the factory_ and conceptually has to be, in order to achieve pooling.

But - you might be able to get the effect you want by manipulating the `configure` parameter, with an action/delegate which sets up the state of the [DbContextOptionsBuilder](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontextoptionsbuilder?view=efcore-7.0) that the factory will use in order to create your contexts.

**Comment by Gambitier** [comment]
@sfmskywalker I tried using second approach of implementing a custom `IDbContextOptionsExtension`, which works. I need help understanding how to run migrations manually in Elsa-3. Also can you please review following implementation

Custom options

```csharp
public class ElsaDbContextOptions
{
    public string? SchemaName { get; set; }
    public string? MigrationsHistoryTableName { get; set; }
}
```

`IDbContextOptionsExtension` implementation and extension method `UseElsaDbContextOptions`

```csharp
public class ElsaDbContextOptionsExtension : IDbContextOptionsExtension
{
    private ElsaDbContextOptions _options;

    public ElsaDbContextOptionsExtension(ElsaDbContextOptions? options)
    {
        _options = options;
    }
}

public static class ElsaDbContextOptionsExtensions
{
    public static DbContextOptionsBuilder UseElsaDbContextOptions(this DbContextOptionsBuilder optionsBuilder, ElsaDbContextOptions? options)
    {
        ((IDbContextOptionsBuilderInfrastructure)optionsBuilder).AddOrUpdateExtension(
            new ElsaDbContextOptionsExtension(options));

        return optionsBuilder;
    }
}
```

to disable auto-migrations we need to set `RunMigrations` to false and pass `ElsaDbContextOptions` which allows to set `SchemaName`

```csharp
 .UseWorkflowManagement(management => 
		management.UseEntityFrameworkCore(ef => {
			ef.RunMigrations = false;
			ef.UsePostgreSql(connectionString, configuration.GetSection("ElsaDbContextOptions").Get<ElsaDbContextOptions>());
	}))
```

`UsePostgreSql` extension method will accept additional parameter of type `ElsaDbContextOptions`

```csharp
public static EFCoreWorkflowManagementPersistenceFeature UsePostgreSql(this EFCoreWorkflowManagementPersistenceFeature feature, string connectionString, ElsaDbContextOptions? options = default)
{
    feature.DbContextOptionsBuilder = (_, db) => db.UseElsaDbContextOptions(options).UseElsaPostgreSql(connectionString);
    return feature;
}
```

usage of these options in `ElsaDbContextBase` constructor

```csharp
protected ElsaDbContextBase(DbContextOptions options) : base(options)
{
    var elsaDbContextOptions = options.FindExtension<ElsaDbContextOptionsExtension>()?.Options;
    ElsaSchema = elsaDbContextOptions?.SchemaName ?? ElsaSchema;
    MigrationsHistoryTable = elsaDbContextOptions?.MigrationsHistoryTableName ?? MigrationsHistoryTable;
}
```

This way I am able to pass `SchemaName` to `ElsaDbContextBase`, but in order to generate migrations manually, what steps should I follow?

**Comment by sfmskywalker** [comment]
Generating migrations manually is easy, it's the same as you would do in any other .NET project using EF Core.
For example, if you're in the project folder of `Elsa.EntityFrameworkCore.Sqlite`, you can run this CLI command to generate migrations for the `ManagementElsaDbContext` context:

```bash
dotnet ef migrations add Initial -c ManagementElsaDbContext -o Migrations/Management
```

**Comment by sfmskywalker** [comment]
Done via #4072 - thanks again @Gambitier !
