### ISSUE TITLE
Suggestion: Provide implicit cast operators from primitives to literal expressions of the same type

### ISSUE THREAD

**Issue by craigfowler** [elsa-workflows/elsa-core#401]
The `WorkflowExpression` mechanism is very powerful and permits the use of complex/advanced expressions in many places where values would be specified.  As such it's desirable for activities to accept workflow expressions in their state, even when they would usually expect to see a plain primitive such as a string.  It permits later consumers of that activity to specify an expression without needing a code change.

## Current inconvenience
One inconvenience when doing this is that when setting primitive values into properties of type `WorkflowExpression` is the need to explicitly use literal expressions:
```csharp
// Property definition, get/set from State omitted for brevity
public WorkflowExpression<string> MyProperty { get; set; }

// Setting a value into that property
myActivity.MyProperty = new LiteralExpression<string>("I just wanted a string");
```

### Suggested improvement
It would be convenient if strings could be implicitly cast to literal expressions of string, allowing usage like this:
```csharp
myActivity.MyProperty = "I just wanted a string";
```

## How to go about this
Doing this would involve addition to `LiteralExpression<T>` along these lines:
```csharp
public static implicit operator LiteralExpression<string>(string val) => new LiteralExpression<string>(val);
```

In theory we could expand this to cover many primitives, using the same technique, applying to `Int32`, `Boolean` etc etc.

## For discussion: Any reason not to do this?
Implicit casting operators are one of those features of the C# language which should be used judiciously.  Over-use can create confusing code where it's hard to understand what's going on.  I know some developers/projects who would outright refuse to allow this, and I always hesitate before I add them to a project.

Is this seen as something useful or "more trouble than it's worth"?

**Comment by sfmskywalker** [comment]
I think the use of an implicit operator on the `LiteralExpression<T>` is a very appropriate solution, very nice.


**Sidebar**
What follows next is a little side bar on how things have changed in Elsa 2 (which is a big refactoring of Elsa 1), so it's a little bit off-topic (and yet relevant in a way):

I've wanted to take things a big step further by allowing programmatic workflows (workflows implemented as .NET types using C# syntax) to use lambda expressions. For instance:

```csharp
workflow.StartWith<WriteLine>(context => $"Hello, {context.Input}!");
```

The above lambda accepts an `ActivityExecutionContext` that provides access to workflow input, allowing the above workflow to e.g. output `"Hello, John!"` when running the workflow with an input value of `"John"`.
Initially I thought I could implement this by introducing a new type called `CodeExpression<T>` (accepting a lambda to execute). 

Although this totally works, it made me rethink the entire implementation of workflow expressions, and concluded that activity developers shouldn't even have to care if some value is provided by an expression or provided as a literal value.

So for Elsa 2, things have changed. Activity developers no longer specify `WorkflowExpression<T>` properties. They simply type their properties a `T`, such as `string` and `int` instead of `WorkflowExpression<string>` and `WorkflowExpression<int>`. This also means that you no longer have to evaluate the workflow expression from the activity's `OnExecuteAsync` method.

Instead, it is now the responsibility of the `WorkflowHost` to evaluate any associated activity property expressions and assign the result to the activity properties, before invoking the `ExecuteAsync` method on the activity.

**Comment by sfmskywalker** [comment]
Done in Elsa 2.
