### ISSUE TITLE
Retry Senario in Elsa Workflow

### ISSUE THREAD

**Issue by CalvinPangch** [elsa-workflows/elsa-core#403]
Please refer to the workflow image below, the problem occur in Activity D. This is a retry scenario which I am expecting A->B->C->A->B->C->D->A.
after D halt(), the workflow suddenly perform the activity E. 
does the Elsa workflow support such retry scenario ? or this is a bug ??

Expected Result:
A ->Done-> B ->NOTMatched->C->False->A->Done->B->NOTMatched->C->NotifyDutyOfficer->A->B
Actual Result :
A->Done->B -> NOTMatched-> C-> False-> A->Done->B->NOTMatched->C->NotifyDutyOfficer-> ?? **_B-->Matched-> E_** 

P/s:
A,B,C does not have Halt()
D will Halt() and wait for DutyOfficer to response.

i am using 
Elsa" Version="1.2.2.29" 
Elsa.Persistence.EntityFrameworkCore Version="1.2.2.29"

![Capture](https://user-images.githubusercontent.com/15224826/95953152-0464d900-0e2c-11eb-8179-06c1c213cf14.PNG)

**Comment by sfmskywalker** [comment]
Looking at the above screenshot, it shouldn't be possible for workflow execution to jump from D -> B without going through A. But if this is what you are seeing, I would need some repro steps in order to troubleshoot. I haven't seen anything like that happen before, so it's difficult for me to say what may be causing this.

**Comment by CalvinPangch** [comment]
i think the problem is come from the Fork and Join. The fork will do "A" and "B" and wait all in the Join then execute the ActivityE. Please refer to the below image, ActivityB only have the outcome "NOTMatched", but in the execute log , the "Matched" is green color and the ActivityE is executed. I expecting to Halt at the "Received Http response" Activity.

![image](https://user-images.githubusercontent.com/15224826/96074124-77c52400-0eda-11eb-8b60-7fc9e86af459.png)
This is the sample Output
![image](https://user-images.githubusercontent.com/15224826/96073629-64658900-0ed9-11eb-8c7c-6bbd831d7867.png)
![image](https://user-images.githubusercontent.com/15224826/96074223-bbb82900-0eda-11eb-949c-4d5beda831c1.png)
![image](https://user-images.githubusercontent.com/15224826/96074197-ae02a380-0eda-11eb-98ed-169360de4abe.png)



i had attached the sample step and project. Thanks. :) 
[ElsaTest.zip](https://github.com/elsa-workflows/elsa-core/files/5382268/ElsaTest.zip)
This is the sample workflow.json for your references
[workflow.zip](https://github.com/elsa-workflows/elsa-core/files/5382296/workflow.zip)

**Comment by sfmskywalker** [comment]
@CalvinPangch Sorry to get back to this so late. It turns out there is some buggy behavior with the Fork/Join activities in Elsa 1, which have been fixed in Elsa 2. We are trying to get V2 released end of this month, so given the limited bandwidth at the moment I think it's best if we close this issue. Not ideal, but I hope you understand.
