### ISSUE TITLE
Any way to know the workflow Id before calling GetWorkflowDefinitionAsync

### ISSUE THREAD

**Issue by Alexplose** [elsa-workflows/elsa-core#408]
I designed all my workflow in the designer, so I can't call GetWorkflowDefinition with the workflow class.
I call it using the Id I get in the store.
Is there any way to get this Id by Workflow name or something more friendly ?

**Comment by sfmskywalker** [comment]
Although workflow definitions have a `Name` property, actually intended to be used to query workflow definitions by their name, unfortunately the `IWorkflowDefinitionStore` abstraction does not expose any methods to allow for this.

It should be straightforward to add this method, but of course it will also have to be implemented by all interface implementations.

In Elsa 2, we're getting rid of the repository abstraction in favor of directly exposing YesSQL's `ISession` so that applications can perform any queries they want, while still using a vast array of data stores.
