### ISSUE TITLE
Sending array as input through the dispatch activity fails

### ISSUE THREAD

**Issue by MariusVuscanNx** [elsa-workflows/elsa-core#4135]
Reproduction:
Having a workflow that calls another workflow through the dispatch activity. Send an array as input.
Attached workflows for reproduction.
[workflow-called-through-dispatch.txt](https://github.com/elsa-workflows/elsa-core/files/11742784/workflow-called-through-dispatch.txt)
[workflow-calling-dispatch.txt](https://github.com/elsa-workflows/elsa-core/files/11742785/workflow-calling-dispatch.txt)

Error:
Workflow faulted with error: Failed to convert an object of type System.Object[] to System.Collections.Generic.IDictionary`2[System.String,System.Object]

Workaround:
Wrapping the array in an object works.

**Comment by sfmskywalker** [comment]
Hello,

Thank you for bringing this to our attention. I've looked into the issue and here's what I've found:

The behavior you're observing is by design. When sending input to a workflow through dispatch, it's expected to be a dictionary of key/value pairs. The key for each pair should match the name of the input as expected in the child workflow.

For instance, in the "Workflow called through dispatch" workflow you mentioned, it expects an input named "TestInput". To provide a value for this input, such as an array, you should structure your payload from the parent workflow as follows:

```javascript
return {
    "TestInput": [
    {
        "prop1": "val"
    }
]};
```

That said, I do recognize that the current design might not be as intuitive as it could be. We'll consider implementing more descriptive error messages to guide users in such scenarios. Additionally, enhancing the UI for the DispatchWorkflow activity to allow users to provide input per key (similar to how users can create cases for the Switch activity) would be a valuable improvement. We'll take this feedback into account for future updates.

Thank you for your contribution to Elsa Workflows. Your feedback helps us make the platform better for everyone!
