### ISSUE TITLE
ParallelForEach not running input list in parallel

### ISSUE THREAD

**Issue by johnwc** [elsa-workflows/elsa-core#4183]
We tried to use the `ParallelForEach` activity to run several activities at once, but they all ran sequentially. After looking into the `ParallelForEach` activity, we see that the activity uses the [`Combine(...)`](https://github.com/elsa-workflows/elsa-core/blob/master/src/core/Elsa.Core/Activities/ControlFlow/ParallelForEach/ParallelForEach.cs#L36) function. The [`CombinedResult`](https://github.com/elsa-workflows/elsa-core/blob/master/src/core/Elsa.Abstractions/ActivityResults/CombinedResult.cs#L27) uses a await, so not sure how it is supposed to run as parallel tasks.

**Comment by sfmskywalker** [comment]
You're right, the ParallelForEach activity doesn't truly execute activities in parallel. Where its `ForEach` counterpart will schedule one iteration after the other (waiting for the current iteration to complete), the `ParallelForEach` activity will schedule all iterations at once. However, the workflow runner will still process its stack one by one.

In order to truly execute activities in parallel, the scheduler would need to execute the activities in the background (and not doing 'await' on each one).

Elsa 3 has this capability where activities of kind `Job` and `Task` can be executed in the background. Although the workflow runner still schedules the activities one after another, they will each run in the background so that the scheduler doesn't have to wait for the activity to complete before scheduling the next one. This effectively gives you parallel activity execution.

ParalleForEach isn't implemented yet in Elsa 3, but it will be able to take advantage of this parallelism, as well as supporting blocking activities in each iteration (which isn't supported either in Elsa 2).

**Comment by johnwc** [comment]
What are the differences between the different kinds of activities?

**Comment by sfmskywalker** [comment]
Technically, there are no differences between these kinds of activities, but the `ActivityKind` is used as metadata by tooling and middleware to tweak the behavior.

For instance:

**Action**

This is the default kind, where the activity behaves regularly and no special treatment is applied from tooling or middleware.

**Trigger**

Tooling may add a "Can start workflow" setting when editing an activity in the designer (although currently, the Stencil implementation of the designer doesn't honor this setting; it always displays this setting).
The Blazor implementation on the other hand does implement this UI behavior.

**Job**

The workflow execution pipeline contains a middleware component that looks at activities of this kind, and schedules their execution onto a background worker, effectively achieving parallel execution of activity execution.

**Task**

Like with the `Job` activity kind, the wf exec pipeline looks at activities of this kind, but will only schedule them for background execution if the activity's *RunAsynchronously* flag is set to `true`.

Tooling also looks at this activity kind by providing UI to let the user control the flag.
This effectively allows users to control via the designer (and from code when defining workflows programmatically) whether a given activity should run in the background or not.

An example of this kind of activity is `SendHttpRequest`.

If you have a workflow with a fork that branches into two paths, where each path leads into a SendHttpRequest activity, and each activity would e.g. take 1 minute to complete, normally the workflow would take 2 minutes to complete.
But, when you configure these activities to "run asynchronously", the workflow will take at most 1 minute, since both HTTP request activities will now execute in parallel.

**Comment by johnwc** [comment]
Is this all only in v3? or does all that you described also function like that currently in v2?

**Comment by sfmskywalker** [comment]
That's right. However, you can still achieve parallel activity execution in Elsa 2 by moving work to a background job and have the activity suspend itself until the background work completes, as outlined [here](https://github.com/elsa-workflows/elsa-core/issues/4180#issuecomment-1619684631).

**Comment by sfmskywalker** [comment]
Done via https://github.com/elsa-workflows/elsa-core/pull/4306
