### ISSUE TITLE
Elsa 3 - v541 - workflow provider issues

### ISSUE THREAD

**Issue by MariusVuscanNx** [elsa-workflows/elsa-core#4224]
Prereq:
- have the blob workflow provider configured.
- have the sample workflows in the blob.

Sample workflows:
[test-dupli---leaf.txt](https://github.com/elsa-workflows/elsa-core/files/12024200/test-dupli---leaf.txt)
[test-dupli---main.txt](https://github.com/elsa-workflows/elsa-core/files/12024201/test-dupli---main.txt)
[test-dupli---intermediary.txt](https://github.com/elsa-workflows/elsa-core/files/12024202/test-dupli---intermediary.txt)

Issue 1:
Repro steps:
- Do a change to the main workflow, then generate a new id and increase the version number.
- Replace the workflow in the blob with the new one and restart the application.

Expected behavior:
There should be only one entry for the main workflow in the workflow definitions dialog.

Actual behavior:
A new entry appears for every new version of the main workflow.
Making a change to the intermediary workflow will result in the same behavior.
![image](https://github.com/elsa-workflows/elsa-core/assets/96233009/f26868a5-8145-442d-b2a8-52393b2043bb)

Issue 2:
Repro steps:
- Do a change to the leaf workflow, then generate a new id and increase the version number.
- Replace the workflow in the blob with the new one and restart the application.

Expected behavior:
- The leaf workflow should now have the version 2 and the version id that we generated.

Actual behavior:
- The leaf workflow still has version 1, the initial version id and the changes of the new version. This very confusing behavior.

**Comment by sfmskywalker** [comment]
The issue was that the workflow definition store populator didn't take into account existing records and them being latest and or published as well. 

The fix is to update the import logic in the populator as follows:

If the workflow being imported has IsLatest = true, any existing versions' IsLatest must be set to false.
Same for the IsPublished flag: if the workflow being imported has IsPublished = true, any existing versions must be set to false.

**Comment by MariusVuscanNx** [comment]
We tested and we confirm that the bug is fixed.
