### ISSUE TITLE
Composable Activities

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#440]
Composite activities are mini-workflows; they specify the activities to execute and how they are connected to one another. Being able to group activities this way allows you to build higher-level activities by encapsulating lower-level ones.

### Requirements

* Composite activities can be programmatically implemented (as a custom activity)
* Composite activities can be defined declaratively (allowing them to be designed from the workflow designer)

**Comment by sfmskywalker** [comment]
Done

**Comment by zbogdanov** [comment]
@sfmskywalker Can you please point me to the PR / commit id for implementing this? I want to see and understand can we use it.

Can you please take a minute and tell me if it will work as such?
* Our workflow has multiple processes in it (asset processing pipeline), like Ingestion, Encoding, QA, Metadata building etc...
* Most of these processes are manual and are governed by statuses (each activity can have a list of statuses which denote the current state of this higher-level process)
* When Encoding goes to completed -> QA activity should automatically go to "Ready" status, marking it available for assignment in a dedicated view...On this premise all other processes behave - they can affect each other
* Multiple events come in to mutate one or more of these activity statuses. E.g. event "Encoding_Started" sets the encoding activity to "Running"... When encoding activity goes to running "Encoding_QA" activity immediately goes to "Ready" etc...

Now, the problem I'm facing with elsa or rather 1.x branch is that workflows are very linear and they are blocking, so it is hard to have 2 separate events coming in and modifying the state of 2 separate activities in the workflow (without blocking anything).

These composable activites looks to me like it can be used to abstract away these processes into their own workflows (with multiple status changes) rather than encapsulating them in activities. That way the composable activity (mini-workflow) can communicate the mutation requests to it's parent (the parent macro workflow)... Now, judging by the short description you posted in this issue, I'm extrapolating and very much hoping that it works like that. Can you please give your 2 cents on this?

Very much appreciated, thank you!

**Comment by sfmskywalker** [comment]
Sure. Although you wouldn't need composite activities to implement the above, they do make things more manageable when using them.

Here's what I'd probably do:

1. Define a new custom composite activity called e.g. `Encode`. This activity acts as a mini-state machine where it basically does two things (has two child-activities): 1) start the encoding job, and 2) listen for the job to finish (blocking until then).
2. Do the same as step one, but for QA, Metadata building, etc.
3. Because multiple events come in, you don't want the workflow to be blocked on only one single custom activity. To allow each activity to listen for completed processes, use the `Fork` activity to branch execution into multiple parallel branches (e.g. "Encode", "QA" and "Metadata building". On each branch, add the appropriate custom activity, and connect each of them in turn to a single `Join` activity to merge workflow execution back into a single branch. Make sure to set the "mode" of this Join activity to "WaitAll" - this ensures that the main workflow blocks until each custom activity is done.

I probably did not understand the requirements completely, but I think the most important point is that you can have multiple blocking activities that can receive external stimulus (e.g. service bus events to signify that a process has completed).

To simplify implementing activities that kick off a process (aka "job"), I intend to introduce a third type of activity which is more or less a mix between Task and Trigger, called Job. Not useful information for now, but perhaps interesting to know.

You can find a simple example of how to write composite activities [here](https://github.com/elsa-workflows/elsa-core/blob/feature/elsa-2.0/src/samples/console/Elsa.Samples.ProgrammaticCompositeActivitiesConsole/Activities/NavigateActivity.cs).

I hope this helps, but let me know if you have any follow up questions.

**Comment by zbogdanov** [comment]
Thank you @sfmskywalker for the feedback. I will try your approach.

Hehe, ironically our current workflow (in-house) implementation is called the "job system", multiple jobs are housed in one job chain...

There are on average 10+ jobs on a chain (and there are 30 job types possible that you can put in a chain) that have the following possible states or statuses:
    public enum JobStatus
    {
        Unknown = 0,
        New = 1,
        Claimed = 2,
        Running = 3,
        RetryPending = 4,
        Cancelled = 5,
        Failed = 6,
        Completed = 7,
        Ready = 8,
        Skipped = 9,
        OnHold = 10,
        Overriden = 11
    }
    
    And the chain definition goes on like follows:
    
    When Encoding job & EncodingQA job are Completed or Failed -> Set VideoSync job & VideoSyncQA job to Ready. 
    When Logging1 job is Completed or Skipped -> Set publish job to completed
    
    etc...there are more complex conditioning and runtime evaluations but this is the gist of it.
    
    So I think our current workflow is more like a state machine encapsulated in workflow semantics while elsa is a workflow without (at least right now afaik) state machine semantics. There are multiple reasons why we are abandoning our in-house solution, one of them is a designer & mass parallel event processing capability (message brokering -> messages that mutate the workflow state).

At any rate, really appreciate your feedback, will continue experimenting with 2.0 branch and will forfeit designer support until it's ready
