### ISSUE TITLE
Error completing "runtask" activity from external API call

### ISSUE THREAD

**Issue by brunozampaglione** [elsa-workflows/elsa-core#4664]
I have a "runtask" activity in the workflow, and I've noticed that when a transaction reaches this activity, it creates a bookmark and changes the status to suspend. After that, I make a Postman call to this endpoint https://localhost:7117/elsa/api/tasks/8e97ecb6d8fc43b497112d7a5751482c/complete and receive a 200 OK response. However, nothing seems to happen with the transaction. Can someone help me understand what I might be doing wrong?

What I'm trying to achieve in this activity is to update a variable through an external app and move the transaction to the next step in the workflow. Any assistance or insights on what might be causing the issue would be greatly appreciated.

Fins sample code attached.... 
[Elsa.Samples.AspNet.RunTaskIntegration.zip](https://github.com/elsa-workflows/elsa-core/files/13491515/Elsa.Samples.AspNet.RunTaskIntegration.zip)

API Calls used to replicate this issue

> Execute workflow
curl --location --request POST 'https://localhost:7211/workflows/hungry

> Check Instance
curl --location 'https://localhost:7211/elsa/api/workflow-instances/dedfe0afa96b482995c562e28006e546' \
--header 'Authorization: ApiKey 00000000-0000-0000-0000-000000000000'

> Complete Task
curl --location 'https://localhost:7211/elsa/api/tasks/5091d20a3ba940e8a6c1496429ac1125/complete' \
--header 'Authorization: ApiKey 00000000-0000-0000-0000-000000000000' \
--header 'Content-Type: application/json' \
--data 'null'

**Comment by ErnestManukyanPlatAi** [comment]
@brunozampaglione did you solve the issue ? I have the same problem

**Comment by brunozampaglione** [comment]
> @brunozampaglione did you solve the issue ? I have the same problem

Unfortunately no....

**Comment by Icidis** [comment]
Good day,

To add to this I've got the following workflow and activities setup

![image](https://github.com/elsa-workflows/elsa-core/assets/1651587/85df1467-ab49-4d05-af12-f5df4dcced22)

**Variables:**

![image](https://github.com/elsa-workflows/elsa-core/assets/1651587/5cafa5a1-f465-4c86-93a2-0ca4801ff5f6)

**Activities:**

![image](https://github.com/elsa-workflows/elsa-core/assets/1651587/5bc6e280-3801-4ecf-95c8-58460ba6f1a1)

![image](https://github.com/elsa-workflows/elsa-core/assets/1651587/ef231b49-07d1-4a2c-ab97-d0f52fa50c11)

**Endpoint**:

 https://localhost:5001/elsa/api/workflow-definitions/user-task-example/execute

**Content**: 

```
{
    "input": {
        "Entity": {
            "Name": "Alice Smith",
            "Email": "alice.smith@acme.com"
        }
    }
}
```

When initiating the workflow, I get the following data posted to the webhook endpoint in the external application.

![image](https://github.com/elsa-workflows/elsa-core/assets/1651587/6dc6b2b2-1862-4699-bc99-2b4b39f7e7e0)

Now, after I call the complete endpoint (https://localhost:7007/elsa/api/tasks/c1c2dd25f7739a14/complete), then workflow feature is now trying to post again to the external application. This is causing a HTTP 400 Error because the data being posted does not have the payload data property is null. As I understand it my workflow definition should get the variable and pass it to the workflow endpoint again.

```
{
  "EventType": "UserTask",
  "Payload": {
    "WorkflowInstanceId": "d02621bfc80f4ff3",
    "WorkflowDefinitionId": "user-task-example",
    "WorkflowName": "Example: User Task Workflow",
    "CorrelationId": null,
    "TaskId": "8c9e218cad8420d8",
    "TaskName": "Create an LinkIn account for the new entity",
    "TaskPayload": { "data": null }
  },
  "Timestamp": "2023-12-14T15:37:12.033274+00:00"
}
``` 

Please find below the definition and instance.

**Definition**:
[example_-user-task-workflow-definition.json](https://github.com/elsa-workflows/elsa-core/files/13675219/example_-user-task-workflow-definition.json)

**Workflow Instance**
[d02621bfc80f4ff3.json](https://github.com/elsa-workflows/elsa-core/files/13675353/d02621bfc80f4ff3.json)

![image](https://github.com/elsa-workflows/elsa-core/assets/1651587/118e4d4b-a2f0-4879-996d-85d35071a136)

**Comment by sfmskywalker** [comment]
@brunozampaglione Thanks for providing the sample code. I had a look and when I try the sample as-is, it would not work (as expected). When I looked into it, I first updated the package references to the latest version (Elsa 3.0.0-preview.907 as of this writing). Then, I had to update the workflow like this:

Old:

```csharp
var deliveredFood = new Variable<string>();
```

New:

```csharp
var deliveredFood = builder.WithVariable<string>();
```

After that change, I was able to kick off the workflow using the following request:

```
curl --location --request POST 'https://localhost:7211/workflows/hungry
```

In your description, you also mention using another request to resume the workflow, but I failed to see how that would work given your sample code, since the workflow would be resumed already by the `OrderFoodTaskHandler` class.

**Comment by sfmskywalker** [comment]
@Icidis Thanks for the detailed description + attachments. I was able to reproduce the issue, which is due to the fact that both the workflow variable as well as the input name are of the same name, where the variable name takes precedence.
This is admittedly unintuitive behaviour, given that you're using the `getInput` JS function.
I pushed a change that  fixes this.
