### ISSUE TITLE
How to update workflow version for existing instance

### ISSUE THREAD

**Issue by telepnevandrey** [elsa-workflows/elsa-core#4669]
Is it possible to update workflow version on existing instance?

I have a large workflow and many instances on it, all suspended in various states of that workflow. I want to make some changes of logic and update their workflow version so that they remain in the same states. Any suggestions? Any workarounds?

Elsa version is 2.12.0
Thanks in advance :)

**Comment by sfmskywalker** [comment]
For Elsa 2, I think your best bet may be to simply execute an SQL query that updates the Version and DefinitionVersionId fields of the WorkflowInstances table for the specified range matching the workflow definition. But be careful to try it out on a local copy first, since it may not work out well in case the workflow instance relies on certain structures / activities not available in the newer workflow definition version.

In Elsa 3, we have an Alterations API that allow for programmatic migration of a set of workflow instances from one version to the next, but this doesn't help you for Elsa 2, unfortunately.
