### ISSUE TITLE
setVariable or getVariable function not working

### ISSUE THREAD

**Issue by nilesh-darji** [elsa-workflows/elsa-core#4789]
**Summary:**

I'm encountering a problem where the setVariable or getVariable functions are not working as expected within the Run JavaScript action in Elsa 3.0.2 This issue prevents me from effectively setting and retrieving variables within my workflows.

**Steps to Reproduce:**

1. Create a workflow in Elsa 3.0 that includes a Run JavaScript activity.
2. Within the JavaScript code, attempt to use setVariable to assign a value to a variable.
3. Subsequently, try to retrieve the value using getVariable.

**Please find workflow json**
[get_variable.json](https://github.com/elsa-workflows/elsa-core/files/13897642/get_variable.json)

**Comment by sfmskywalker** [comment]
The issue stems from the fact that the `setVariable` method attempts to find an existing scope for the specified variable name. When you define a workflow variable with this name, it will work. 

<img width="1521" alt="image" src="https://github.com/elsa-workflows/elsa-core/assets/938393/725d72f3-8285-4caa-8616-05bacc45cee2">

Without defining the variable first, it will fail.
Although that's why it doesn't work without first defining the variable, I think we should support defining variables on the fly as per your workflow.

For now, I attached an [updated workflow JSON file](https://github.com/elsa-workflows/elsa-core/files/13942651/event-test.json) that works for your scenario.

I will think about a way to allow for the dynamic creation of workflow variables.
