### ISSUE TITLE
Running the designer

### ISSUE THREAD

**Issue by Kinani** [elsa-workflows/elsa-core#48]
Any advise please on how to build and run the Elsa Workflows Dashboard? I followed the instructions on readme and no luck,  Is it supposed to run out of the box?

**Comment by sfmskywalker** [comment]
Sorry, the readme is outdated - I will update it soon.

I ripped out the dashboard for now to turn this library into its fundamental core: workflow execution.

However I will add a fully function dashboard back. It will be housed here: https://github.com/elsa-workflows/orchard-core-elsa-workflows

**Comment by sfmskywalker** [comment]
Turns out it was more practical to have the dashboard here in this repo during development, so I moved it back 😅 

If you get latest, you'll notice there's a new project called Elsa.Dashboard.Web that you can try out. It's not yet complete, but it does demonstrate displaying the designer and provides a list of workflow definitions that you can manage. Next on my list are managing custom activities and workflow instances.
