### ISSUE TITLE
Call is ambiguous and matches multiple workflows.

### ISSUE THREAD

**Issue by albourm** [elsa-workflows/elsa-core#4848]
I have created my custom activities so i have one endpoint at first then i will get the input from that endpoint and i will  pass it to the custom activity then i have fork and it's split into four sections so in each section i have endpoint and and input of that endpoint i am passing it to the custom activity to do something so when i'm creating more than one instance of the workflow and i want to approve the request using the second endpoint i am facing the below issue.

{
    "errorMessage": "The call is ambiguous and matches multiple workflows.",
    "workflows": [
        {
            "WorkflowInstanceId": "3fd896ab63a1420fab338fee44e1670d",
            "WorkflowInstance": null,
            "ActivityId": "4f140f52-4de4-4f84-8404-ce7d8b3af1e3"
        },
        {
            "WorkflowInstanceId": "b7b31d2f3a364f679489c43891afb0ba",
            "WorkflowInstance": null,
            "ActivityId": "4f140f52-4de4-4f84-8404-ce7d8b3af1e3"
        }
    ]
}

**Comment by sfmskywalker** [comment]
This is by design - the HTTP request needs to end up being handled by exactly one workflow and not multiple. This approach is similar to how requests are routed to a specific action on a controller. If you have multiple matching controller actions, you will get an error.

What you might do is somehow make your workflow instance routes unique, either by including a route param in the path, or perhaps through a correlation header that might be used to differentiate between workflows.

That being said, I don't know if anything like that is currently implemented, but it should certainly be feasible to add.

**Comment by albourm** [comment]
![WorkflowIssue](https://github.com/elsa-workflows/elsa-core/assets/152151110/d2c05efd-4692-4d52-b210-c9b5c4d42923)

in case of the attached workflow i have Resubmit request activity so i am get the request from the endpoint so i am facing The call is ambiguous and matches multiple workflows in case of more than one instance of workflow.

how i can implement your solution to add  the workflow instance id into the route and how to let the workflow engine to execute that instance like the signal received approach.
this is my re-submit request url : v1/workflow/re-submit-request

**Comment by sfmskywalker** [comment]
I haven't had the time to try it myself unfortunately, but typically you would use a JS or Liquid expression to provide a dynamic value. For example, let's say that you want to disambiguate the URL by workflow instance ID, you might be able to enter the following JS expression for the URL:

```javascript
`/v1/workflow/${workflowInstanceId}/re-submit-request`
```

Alternatively, instead of using HTTP Endpoint, you could consider using the Signal Received activity which can also be triggered by an HTTP request. You can generate the correct URL to invoke using the JS function called [signalUrl](https://v2.elsaworkflows.io/docs/expressions/javascript#signal-url).

**Comment by albourm** [comment]
I want to express gratitude for your suggestions. We've implemented the first approach to ensure the uniqueness of the endpoint URL, and is functioning smoothly for us.

**Comment by sfmskywalker** [comment]
I'm happy to hear that 😄

**Comment by albourm** [comment]
Great to hear! 😄 I appreciate your support!
