### ISSUE TITLE
Signaled Acitivity looses input

### ISSUE THREAD

**Issue by pdeki** [elsa-workflows/elsa-core#486]
When using TriggerSignal activity and publish the signal with the Input array of type Variables soon the message hits the Signaled activity Input collection is available (with the Signal element and additional input of list of variable) but after the Signaled input collection is empy.

Expectation: That after Signaled activity Input collection has content as on Signaled activity only without Signal.

**Comment by sfmskywalker** [comment]
This is by design: input is considered transient state, and flows automatically from source to target, and it is up to each target activity to return output. If you wish to capture an activity's output (or a workflow's input), you should store it in a Workflow Variable (using the `SetVariable` activity).

That being said, we might consider updating the `Signal` activity to always return its input as its output, so that your workflow can use it in the next activity, or even from any other activity by referencing the signal activity by name. Activity output, in contrast to activity input, is not transient, but stored with the activity state.

**Comment by pdeki** [comment]
I understand your point. But here is the one *"special"* case where **Signaled** activity is used to pass the control from some other activity (where is the **Trigger Signal**). Since some *other activity* wants to trigger execution and to pass the data (this is where **Input** is used in **Trigger Signal**) so that received activity (where is the **Signaled**) could take those data and process further. 

By not having data after **Signaled** activity (I'm not sure how workflow variable will help me in this scenario above) we are pretty stuck in implementing scenario as described above (or I'm wrong on something?).

I like idea updating Signaled activity.

**Comment by craigfowler** [comment]
I agree, I like this approach and it certainly seems sensible.

A signalled activity will always "pass its input on" so that the next activity receives the same data as **its** input.

If nobody else picks this up before me, this will be next on my list to implement.

**Comment by sfmskywalker** [comment]
@craigfowler Awesome. It's all yours.

**Comment by craigfowler** [comment]
Well, that was an easy fix.  _So easy I didn't have to do anything!_

@pdeki for reference, in Elsa 2, the activity which was named `Signaled` has changed name to become `SignalReceived`.  The desired behaviour: _"The input for triggering the signal is emitted as the output from the `SignalReceived` activity"_ was in fact already implemented and as far as I can tell would have worked in Elsa 2.

Elsa 2 is currently in development with [preview packages available via MyGet](https://www.myget.org/feed/elsa-2/package/nuget/Elsa), but it's not yet ready for a full release.

I've put in a PR for this issue anyway.  All it does is add some test coverage for this behaviour (it was that which told me it already worked).  If we're collectively satisfied that this is good then I think this issue could close.

**Comment by sfmskywalker** [comment]
Great stuff. This is good enough for me.
