### ISSUE TITLE
Getting the Activated Workflow Instance

### ISSUE THREAD

**Issue by comicon1234** [elsa-workflows/elsa-core#487]
Is there a way to see when a workflow has activated and get the workflow instance ID to use that somewhere else. I am trying to use elsa to do the heavy lifting of a Request approval workflow and I have a ton of data from the request in another table. I would like to create a relationship between the Elsa workflow table and the Request data table when a new request is submitted.

**Comment by comicon1234** [comment]
Would creating a custom activity be the way to go? I see that I can get the Workflow Execution context when creating a custom activity.

**Comment by sfmskywalker** [comment]
Not knowing the full details of your requirements, I would say that in general, the best way to go about this would be something along the following lines:

* When a new request is submitted, you fire some event (perhaps using Mediatr), unless you are already implementing some form of even handler for when a new request is submitted.
* Regardless of the above, use Elsa's Workflow Trigger API to either start new or resume existing workflows that are (to be) correlated with the request (usually by ID, but this is up to you).
* The workflow does its thing. It can interact with the request and implement logic based on the request's properties.

What I would do is indeed create a custom activity, e.g. `RequestSubmitted`, which is an activity that acts as a trigger (causing the workflow to be suspended unless it's the first activity in the workfow to execute).

** Elsa 1**
From your application code, as soon as you identified that a new request is submitted, you do these things:
1. Get all workflow definitions from `IWorkflowRegistry` that start with the custom `RequestSubmitted` activity.
1. Start each workflow using `IWorkflowInvoker.StartAsync`.
1. Get all workflow instances from `IWorkflowInstanceStore` that are blocked on the `RequestSubmitted` activity.
1. Resume each workflow using `IWorkflowInvoker.ResumeAsync`.

Look at `TriggerRequestHandler` in `Elsa.Activities.Http.RequestHandlers.Handlers` for an example of how workflows are started and resumed based on incoming HTTP requests.

** Elsa 2**
The following is subject to change, but right now you would do this:
1. Implement a `Trigger` and its `TriggerProvider` as a way to index workflows so that you can select them when it is time to trigger them (when a request is submitted). The trigger could be named e.g. `RequestSubmittedTrigger` and have a `RequestId` field.
1. Implement a `RequestSubmittedTriggerProvider` by inheriting from `TriggerProvider<RequestSubmittedTrigger, RequestSubmitted>`.
1. When a request is submitted, use the `IWorkflowRunner` service to `TriggerWorkflowsAsync<RequestSubmittedTrigger>(x => x.RequestId == null || x.RequestId == request.Id)`, which will either start a new workflow of none exists yet for the submited request, or resume existing ones that are blocked on the `RequestSubmitted` activity.

The above is the gist of it, and there are some details left out because the trigger API in Elsa 2 is still unstable, so details will change. Once everything is fleshed out there, all of this will be documented. Until that time, I would encourage you to check out the sample applications and existing activity implementations. And when you have specific questions, feel free to drop them here or by creating new issues or by asking questions on SO.

**Comment by comicon1234** [comment]
Thanks, you thoroughly answered my question.
