### ISSUE TITLE
Memory Leak in CodeActivity Post Workflow Execution

### ISSUE THREAD

**Issue by af-git-64** [elsa-workflows/elsa-core#4884]
I've noticed a potential issue where the `CodeActivity` seems to be leaking memory after the execution of a workflow. This behavior is consistent and can be reproduced with the following steps:

1. Execute a workflow that includes a `CodeActivity`.
2. Monitor the memory usage during the workflow execution.
3. Observe that even after the workflow has completed execution, the memory used by the `CodeActivity` is not released.

This issue is causing a significant increase in memory usage over time, especially in scenarios where workflows are frequently executed. It's impacting the performance and scalability of our application.

```
[Activity("MemoryLeakTest", Description = "Memory test")]
public class MemoryLeakActivity : CodeActivity<string>
{
    [Port]
    public IActivity? Error { get; set; }
    protected override async ValueTask ExecuteAsync(ActivityExecutionContext context)
    {
        context.Set(Result, Enumerable.Repeat("MemoryLeak", 1000000));
        await context.CompleteActivityAsync();
    }
}
```

![image](https://github.com/elsa-workflows/elsa-core/assets/159041713/533b560e-a9e7-44d7-a3dc-b78ff93297ff)
![image](https://github.com/elsa-workflows/elsa-core/assets/159041713/e054841c-8ec2-4d31-95c7-5f14d208f711)

Any help in addressing this issue would be greatly appreciated. Please let me know if you need any more information or specific details to investigate this further.

Edit: We are currently utilizing Version 3.0.5 of Elsa 3.

**Comment by af-git-64** [comment]
I've attempted to apply the fixes suggested by the Glime-AI bot, but unfortunately, these attempts have not yielded any success. It's important to note that our tests were conducted on the latest version of Elsa 3, specifically version 3.0.5. 

The problem appears to be rooted in the Elsa 3 core. Additionally, we were unable to find any similar issues reported on the GitHub issues page for Elsa 3.

**Comment by sfmskywalker** [comment]
@af-git-64 Thanks for reporting, we will take a look!

**Comment by sfmskywalker** [comment]
I can confirm that I see the same results as described in this issue. Investigating.

**Comment by sfmskywalker** [comment]
The core issue stemmed from the `BulkUpsertAsync` method extension we developed for the Entity Framework Core provider. More precisely, the problem arose because the method was dynamically generating a predicate that incorporated a **deferred enumerable** rather than a concrete list object. 

While I'm not entirely versed in the intricate details of its operation, this seemingly minor modification led to the allocation of memory that couldn't be freed. This behavior was consistently replicable by altering the code segment as follows:

Originally, the code explicitly converted the enumerable to a list, like so:

```csharp
var list = entities.Select(compiledKeySelector).ToList();
```

Modifying it to retain the deferred execution state of the enumerable:

```csharp
var list = entities.Select(compiledKeySelector);
```

resulted in the latter approach causing the memory profiler to highlight this specific enumerable object residing on the Large Object Heap (LOH), where it remained uncollected despite multiple attempts to force garbage collection with `GC.Collect`. Conversely, by utilizing the `.ToList()` method, it facilitated the memory's successful reclamation through garbage collection.
