### ISSUE TITLE
Elsa Dashboard not loading with latest docker container

### ISSUE THREAD

**Issue by nechcp** [elsa-workflows/elsa-core#5186]
Hi,

We are trying to run the elsa dashboard using the docker image and connect it to our elsa server. The dashboard stopped working recently.  Our server is at elsa version 2.14.1. 
 docker run -t -i -e ELSA__SERVER__BASEADDRESS='https://localhost:44364' -p 13000:80 elsaworkflows/elsa-dashboard:latest

![image](https://github.com/elsa-workflows/elsa-core/assets/84976384/4130448e-ef62-4f34-b439-694ae10ded00)
![image](https://github.com/elsa-workflows/elsa-core/assets/84976384/ec495928-d35a-4c3e-8d5d-7c6201ccf334)
![image](https://github.com/elsa-workflows/elsa-core/assets/84976384/30f7cee0-3332-46cc-bfff-216dacf7c218)

Can you please help to rectify this issue?

**Comment by tomy2105** [comment]
It seems to me that the problem is the port the .NET is listening on, it says based on log screenshot "Now listening on: http://[::]:8080".
Yet the docker command you used to start it uses mapping to port 80, not 8080.

Can you try starting docker with: "docker run -t -i -e ELSA__SERVER__BASEADDRESS='https://localhost:44364/' -p 13000:8080 elsaworkflows/elsa-dashboard:latest" and see if it helps?

**Comment by nechcp** [comment]
Ok. I didn't notice the port change from 80 to 8080. Thank you so much for spotting this.
