### ISSUE TITLE
Elsa 2.0: Lucene Indexing

### ISSUE THREAD

**Issue by Rafael94** [elsa-workflows/elsa-core#542]
I saw that Lucene Indexing is on the roadmap (Readme.md) and wanted to inquire what exactly is meant by it.

Should there be activities that index, update or delete documents from a search engine?

I use Elasticsearch as a search engine at work. Now that there is the `EntityChangedTrigger`, you could index via workflows.

If that's what is meant by Lucene Indexing, I could start laying the groundwork. I would then do it like I did with the timers (Hangfire, Quartz).

**Comment by sfmskywalker** [comment]
Good question. Here's what I meant:

There should be a background job that indexes workflow instances by invoking implementations of e.g. `IWorkflowInstanceIndexHandler`, which receive a workflow instance and an index builder context to add items to the index.
Each implementation can index one or more particular aspects of a workflow instance. For example, there could be a `FullTextWorkflowInstanceIndexHandler` that adds the JSON representation (perhaps minus curly braces) to the index, and another `WorkflowInstanceIndexCoordinator` that iterates over each activity, and fires off invocations for each activity using e.g. `IActivityIndexHandler`, allowing individual activity types to control what aspects to add to the index.

You are right that the API should be abstract, for which we can provide concrete implementations such as **Lucene** and indeed **ElasticSearch**.

The background job would probably be implemented as a hosted service by deriving from `BackgroundService`, which would be feeding off a queue of indexing tasks, allowing new indexing tasks to be added s workflow instances get created, updated and deleted.

I haven't figured out all of the details, but these are my initial thoughts.

**Comment by Rafael94** [comment]
Ok, I understand. It is something complicated after all. I'm not sure about the intended use yet either, but it's more because my workflows are context based. I rather need the contexttype and the contextId. Search engines are more for more complex searches. 

I don't think a background job is necessary. Indexing can be done directly. It should hardly cost any time.

It would be more interesting to start workflows in the background. For example with EntityChanged, so that the user does not have to wait so long. Depending on how many instances there are and how many activities are executed, the execution could take a long time and the user has to wait for a long time.



Translated with www.DeepL.com/Translator (free version)

**Comment by sfmskywalker** [comment]
The primary use case (for now at least) is to be able to search workflow instances from the dashboard interface.

Than you for the note about the background job probably being unnecessary. I have a lot to read up on regarding indexing best practices.

Regarding starting workflows from the background, I agree. Today we already have workflows running in the background, depending on what triggered them. Quartz & Hangfire driven timers are run from the background intrinsically.
Regarding EntityChanged, I can imagine that for some scenarios, you want the workflow to execute synchronously, while in other scenarios you want to execute them asynchronously in the background.

Perhaps what we need is a way to schedule workflow for execution asynchronously. Then perhaps workflow definitions could be configured to be executed in the background. The entity changed handler for example could then simply select what workflows to execute, hand them over to some `IWorkflowLauncher`, which in turn would figure out whether the workflow should execute synchronously (using `IWorkflowRunner`) or asynchronously (using some `IWorkflowQueue`).

Thanks for the food for thought :)

**Comment by Rafael94** [comment]
I've been thinking about this for the last couple of days. The data is saved as documents. So each handler would have to map the data (instance, activity) to a document or there are different documents. But if a search engine is better than a simple SQL search I still can't judge.

What do you think about my idea with an activity for indexing the workflow context? I would then program it so that you could use the basics for your indexing.

**Comment by sfmskywalker** [comment]
The issue with a SQL search is that it can't just look into workflow instance documents (AFAIK). With MongoDB and CosmosDB this is not an issue, since CosmosDB automatically indexes all fields of all documents, and with MongoDB one can specify what fields to index. But Elsa's persistence APIs are provider-agnostic, and would have to provide another abstraction to allow for arbitrary document querying that would then have to be implemented by each persistence provider. 

In contrast, introducing an indexing abstraction allows a Lucene or Elastic Search implementation to handle the indexing of each workflow instance document. Developers can now write indexing handlers to control what fields they want to be able to search on from the dashboard (Elsa's or their own custom one) for example.

One such handler could be provided by the Elsa implementer that takes care of indexing the workflow context.
These handlers would be triggered by the Elsa workflow runner, for example right after a workflow becomes suspended or completed.

Having an activity that performs the indexing might be useful too, although I wonder if necessary given that indexing would be performed automatically. I could be missing something of course, so please do let me know what you think.

**Comment by Rafael94** [comment]
Now I know what you mean. With your method, the search is always the same, regardless of the database provider. But it should still be optional, in case someone doesn't want to install a search database.

What I mean is an activity to index the context. Let's take again my example with the ticket. I currently have my own event bus with which I get changes. In this bus I index the corresponding ticket. But you could also do it via an activity. But I just noticed that it doesn't make that much sense.

You could also do it via WorkflowContextRefresher<Document>. So whenever a document is saved, it is indexed. So only deleting the index would be missing.
