### ISSUE TITLE
To avoid confusion, developers should not consume temporal (time-based) activities without an appropriate back-end

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#564]
Right now Quartz is available as a separate package, but without either Quartz or Hangfire, the Timer activities are useless. One option could be to implement a simplistic in-memory scheduler, but Quartz already provides this, so we might use that as the default instead. We will keep the current abstractions so that Hangfire or other schedulers can be used instead of Quartz.

**Comment by Rafael94** [comment]
I think it's better the way it is. With your variant, you have dependencies in the program that you may not need.

The developer also only needs to add E`lsa.Activities.Timers.Hangfire` or `Elsa.Activities.Timers.Quartz` as a package. This should not be much work. It is best to remove `Elsa.Activities.Timers` from `/src/core/Elsa` so that the developer has to actively decide if the timer wants to have activities and with which library.

**Comment by craigfowler** [comment]
Presuming I've understood it, I actually agree with @Rafael94 on this one.

If I've understood correctly what we have is this:
* One or more "temporal activities" such as `Timer`, which require a "temporal backend" in order to be useful
  * The activity doesn't care which because it uses an abstraction
* Two different "temporal backend" providers available, one Quartz and one Hangfire
  * Presumably these depend upon the abstraction above

It's probably not a good idea to leave the temporal activities in the core package if they're useless without (what in JS/NPM world would be called) a peer dependency.  That's what one of my colleagues would call "a support-call-generator" because people are just as likely to do it wrong as they are to do it right 😄 

The temporal activities could totally be in a separate NuGet package/project, with a name something like `Elsa.TemporalActivities.Common` (just making a name up, there's probably already precedent for a good name).  This avoids duplication, because both the Hangfire and Quartz impl packages would take a dependency upon the abstractions in the common package.  Then we direct devs to install either the Hangfire or Quartz package and they get all of the stuff which requires it.  We wouldn't really even need tell anybody that the common package exists.  We don't want people to consume it directly, only as a component of using Hangfire/Quartz.

_We could go one step further_, in fact, and throw an exception if any attempt is used to make use of the temporal activities and there is no temporal backend impl present.  That exception could state very clearly that you must first go get & install one of those two other packages.  That would protect us from the minority who go out of their way to manually install a package which doesn't contain everything they need.

IMO that last part probably isn't worth the effort at this point though.

**Comment by sfmskywalker** [comment]
`Temporal`, I like it. Right now we have this:

- Elsa.Activities.Timers (the "common" package)
- Elsa.Activities.Timers.Quartz
- Elsa.Activities.Timers.Hangfire

So structurally speaking, we almost already got what @Rafael94 and @craigfowler are proposing.

The common package isn't in the core package (Elsa.Core), but it is referenced by the `Elsa` package itself. If you wanted to use Elsa without taking a reference to the common temporal package, you would have to reference Elsa.Core instead, and do some things manually that is otherwise taken care of for you. But as correctly observed, this is not ideal.

Devs today already need to at least reference the Quartz or Hangfire package in order for the temporal activities to work. Without it, application startup will fail because no concrete temporal (really liking the term 😄 ) services will have been registered otherwise.

Everything considered, here's what I propose we do:

- [ ] Remove the reference from **Elsa.csproj** to **Elsa.Activities.Timers.csproj**.
- [ ] Move the `AddTimerActivities` extension method out of **Elsa.Activities.Timers** and instead rename & add it to both **Elsa.Activities.Quartz** and **Elsa.Activities.Hangfire** (rename to e.g. `AddQuartzActivities` and `AddHangfireActivities`).
- [ ] Rename **Elsa.Activities.Timers.csproj** to **Elsa.Activities.Temporal.Common.csproj**
- [ ] Rename **Elsa.Activities.Timers.Quartz.csproj** to **Elsa.Activities.Temporal.Quartz.csproj**
- [ ] Rename **Elsa.Activities.Timers.Hangfire.csproj** to **Elsa.Activities.Temporal.Hangfire.csproj**

With that, devs now need to explitly reference the Hangifre or Quartz package in order to install temporal activities.

**Comment by craigfowler** [comment]
It we're all in agreement, I can grab & implement this one next.

**Comment by sfmskywalker** [comment]
Sounds great!

**Comment by Rafael94** [comment]
@craigfowler Exactly how I imagined it
