### ISSUE TITLE
[BUG] Unable to use more than one Masstransit activity 

### ISSUE THREAD

**Issue by ilcorvo** [elsa-workflows/elsa-core#5776]
## Description
I tested, in version 3.2.0, the usage of the Masstransit activities as described in the example project Elsa.Samples.AspNet.MassTransitActivities, but in works only for the OrderCreated activity and not for OrderCompleted.

## Steps to Reproduce
The server solution for test in this repository: [ElsaMasstransitActivities](https://github.com/ilcorvo/ElsaMasstransitActivities). There you can find workflow-definitions.zip containing all the test I done to try to trigger OrderCompleted activity.

The simplest is to run the Publish workflow which contains 2 activities: first publish OrderCreated and then publish OrderCompleted. This should trigger the Receive workflow which contains 2 activities: first receive OrderCreated and then receive OrderCompleted.
The Receive workflow is effectively started but OrderCompleted does not receive the OrderCompleted message: it contains still OrderCreated (attached you will find images demostrating this).
![image](https://github.com/user-attachments/assets/b1c43b0d-f5d1-449f-95d8-db912c6f27cf)
![image](https://github.com/user-attachments/assets/2f9c7417-d8ad-43b3-816a-9f384bd51da7)
![image](https://github.com/user-attachments/assets/0163ef4f-7e27-4a3d-a03e-9403d4337353)
![Elsa OrderCompleted](https://github.com/user-attachments/assets/da9e66ec-592b-4155-95f7-f0301c5e4c44)

I also tried to start other workflows by order OrderCompleted but no way.

**Comment by sfmskywalker** [comment]
First of all, thank you for the detailed description and sample project!
I have cloned your repo and tried to reproduce the issue. The reason the **Order Completed** workflow doesn;t get executed is because its `Order Completed` activity was not activated.

Here's your version of that workflow:

<img width="1233" alt="image" src="https://github.com/user-attachments/assets/3ae8661e-959f-49aa-a0f2-845d362e8897">

Here's my version:

<img width="1249" alt="image" src="https://github.com/user-attachments/assets/7cadc262-13e0-491f-9c6d-0562b5f57947">

With that small change, everything works:

Main workflow sending the messages:

<img width="2552" alt="image" src="https://github.com/user-attachments/assets/0fea3aaf-0976-484d-b55a-4b896fd51a05">


Order Created workflow:

<img width="2552" alt="image" src="https://github.com/user-attachments/assets/9691e71d-5c1f-4d99-80d1-73bf81ae94b4">


Order Completed workflow:

<img width="2552" alt="image" src="https://github.com/user-attachments/assets/f05e3050-fd8c-4848-b9c3-28257e0cb8c8">
