### ISSUE TITLE
Call the activity if another activity throw an exception

### ISSUE THREAD

**Issue by SoftwareDesign-Solution** [elsa-workflows/elsa-core#580]
Can I define an activity in a workflow that is called in the event of an error? Activity 1 or Activity 2 causes an error and then error activity is called

**Comment by sfmskywalker** [comment]
Not right now, we still have to work on the error handling & compensation stories.
Until then, when designing your own custom activities, it is advised to try/catch any work you do yourself, and in case of an error, return an `"Error"` outcome. We might end up doing the same for the existing activities that can potentially fault, such as for the `SendHttpRequest` activity.

Any suggestions are welcome.

**Comment by craigfowler** [comment]
This looks like a good feature request but it probably needs quite a bit of refinement before it's actually implemented.  It's not clear yet as to exactly what the requirements are and how people would expect to use this functionality.  It goes without saying that it's also unclear as to how it should be coded too, in order to be actually useful.

Seeing as v2 is slated for a month's time, could I suggest deferring out of the v2 milestone?  That would take the pressure off a little and allow it to get the thought & attention it deserves.

**Comment by craigfowler** [comment]
I've just had a read-through of #200 and [left some thoughts there].  The more I think about it, much of that applies to this issue as well.

[left some thoughts there]: https://github.com/elsa-workflows/elsa-core/issues/200#issuecomment-785337232

**Comment by sfmskywalker** [comment]
I agree, it's unlikely we'll be able to design & implement this before the 2.0 release.

**Comment by sfmskywalker** [comment]
We have an issue to track handling activity error outcomes here: #1115
