### ISSUE TITLE
Timers not firing

### ISSUE THREAD

**Issue by adsgreen** [elsa-workflows/elsa-core#656]
New to Elsa and so far impressed.
I've been working through the example at https://sipkeschoorstra.medium.com/building-workflow-driven-net-core-applications-with-elsa-139523aa4c50
I've used 
- the https://github.com/elsa-workflows/elsa-samples/tree/master/src/Elsa.Samples.UserRegistration sample code
- the sample workflow json https://github.com/elsa-workflows/elsa-samples/blob/master/src/Elsa.Samples.UserRegistration/user-registration-workflow.json

Everything works fine with the exception of the timers event (2 after the fork).
The approve user process completes ok (can see the workflow instance complete and the record in the DB) however the "wait for 2.5 minutes" timer after fork never signals so unless the activity completes it stays "executing".
Tried on Core 3.1 and Net5

Not sure what I am missing? 
Thanks,

**Comment by sfmskywalker** [comment]
Sounds like this might be a bug. The timers thing has been completely re-implemented in Elsa 2 (due to timer activity flakiness in Elsa 1). The plan is to release Elsa 2 end of March, provided that we finish the designer part in time (the engine itself is pretty much ready for release). If you can do without the designer for now, I recommend trying out the Elsa 2 preview 6 bits (from MyGet, not NuGet which is outdated at the moment). You'll find many samples already in the [samples folder of the feature/elsa-2.0 branch](https://github.com/elsa-workflows/elsa-core/tree/feature/elsa-2.0/src/samples). Here's a simple example: https://github.com/elsa-workflows/elsa-core/blob/feature/elsa-2.0/src/samples/worker/Elsa.Samples.Timers.Quartz/Workflows/TimerWorkflow.cs
