### ISSUE TITLE
Central Webhook URL Management

### ISSUE THREAD

**Issue by jwillmer** [elsa-workflows/elsa-core#667]
As a power user I like to use existing webhook URLs in different workflows and be able to manage the endpoint centrally.

- Option to define webhook URLs outside of a workflow under a specific name
- Option to select the predefined webhook URL by name from a drop-down in the webhook activity

![image](https://user-images.githubusercontent.com/1503577/109169278-eca94400-777f-11eb-8b73-5ddbb0068784.png)

![image](https://user-images.githubusercontent.com/1503577/109169508-2a0dd180-7780-11eb-932e-e78fee7bdb82.png)

**Comment by sfmskywalker** [comment]
I can see two ways of going about this.

**Option 1**
We introduce a new activity called *Webhook* that has the option to select a predefined webhook definition.

**Option 2**
Instead of introducing a new activity, we use the already existing *HttpRequestReceived* activity which has the necessary capabilities, but implement a new `IActivityProvider` that *dynamically yields activity type based on the defined webhook definitions*.

The user has then access to a new category of webhook activities, where they can simply add a webhook definition in the form of an activity without even having to select the webhook definition from a dropdown list.

For example:

1. User creates a new Webhook Definition called "Stripe Payment Received" from the Webhooks management area in the dashboard app.
2. User navigates to workflow editor and now suddenly has a new activity available called "Stripe Payment Received"

Option 2 would have my preference, because it reuses everything offered by the HttpRequestReceived trigger, and I think it offers a nicer experience to the user in terms of picking activities reflecting the webhook 1:1.

What I would like to do as well is take this opportunity to rename the HttpRequestReceived activity to `HttpEndpoint` - I think it's a better name.

From the dashboard's point of view, we add a new section to the main navigation called e.g. "Webhooks", from where the user can manage webhook definitions and list workflows by webhook (one webhook definition can be used by many workflow definitions).

**Comment by jwillmer** [comment]
Option 2 sounds great! While reading I had some ideas I wanted to point out but at the end of your text we came to the same conclusion - rename endpoint and group webhooks 😄

**Comment by sfmskywalker** [comment]
Great! Then we agree and we'll make those changes. This is going to be a very exciting feature.

**Comment by sfmskywalker** [comment]
To implement this, we basically need four things:

1. A class library that contains the **models, domain services and activity providers** that yield **webhook activities** based on webhook definitions.
2. A set of class libraries that implement **concrete persistence providers** for accessing webhook definitions from storage.
3. A REST API that enables programmatic control over webhook definitions. Specifically, the dashboard application will rely on this API to manage webhook definitions.
4. A **dashboard module** for the Blazor dashboard application that allows the user to manage webhook definitions.

Since the dashboard application currently has no notion of modules, we might skip that part for now and add the necessary pages and components directly into the **ElsaDashboard.Application** project for now. Later on, we can extract everything into a separate class library.

### The Class Library

The webhooks functionality is to be created as part of a _module_ for Elsa, which in reality is just a .NET Standard 2.1 class library.
This library would contain the following:

* The `Webhook` model
* An `IWebhookStore` interface representing a repository of webhook definitions.
* An implementation of `IActivityTypeProvider` that yields `ActivityType` objects based on `Webhook` objects stored in the repository.

**Webhook**

The `Webhook` class represents a webhook definition with the following attributes:

* Id: string
* Name: string
* Path: PathString
* Description: string?
* PayloadTypeName: string? // A .NET type name to automatically deserialize the received HTTP request body into.

The class should derive from `Entity` to take advantage of common store operations (finding entity by ID) and implement `ITenantScope` in order to support webhook associated per tenant.

**Webhook Store**

The webhook store represents an abstraction of the underlying persistence provider. It could be as simple as the following:

```csharp
public interface IWebhookStore : IStore<Webhook>
{
}
```

The `IStore<T>` interface provides basic CRUD operations, for which an implementation exists for the currently supported persistence providers.

**Activity Type Provider**

The `TypeBasedActivityProvider` is currently the only example of an implementation that yields activity types based on the existence of .NET types that implement `IActivity`.

But instead of yielding Activity Types based on .NET types, here we would simply inject `IWebhookStore` to get a list of ALL webhook definitions, and yield activity types based on information for each webhook. However, since an Activity Type also needs to contain delegates for `CanExecuteAsync`, `ExecuteAsync` and `ResumeAsync`, we should reuse methods from the `HttpRequestReceived` activity (which itself is to be renamed to simply `HttpEndpoint`).

Pseudo code to construct an `ActivityType` from a `Webhook` instances:

```csharp

constructor(IWebhookStore store, IActivityActivator activityActivator);

// For each webhook in the store)

// Descriptors are used in the activity editor. Since the activity provider will set the majority of the properties on the `HttpEndpoint` activity instance, we only need to provide the user with an option to specify which request method the webhook should handle.

var descriptor = new ActivityDescriptor
{
   Type = webhook.Name,
   DisplayName = webhook.Name,
   Category = "Webhooks",
   Outcomes = new[] { OutcomeNames.Done },
   Properties = new[] { new ActivityPropertyDescriptor("RequestMethod", "select", "Request Method", "Specify what request method this webhook should handle. Leave empty to handle both GET and POST requests", JObject.FromObject( new { Options = new[] { "", "GET", "POST" } } )) }
};

// A private  local method to instantiate an `HttpEndpoint` activity, initialized with properties from the webhook definition.
async Task<IActivity> ActivateActivityAsync(ActivityExecutionContext context, Webhook webhook)
{
   var httpEndpointActivity = await activityActivator.ActivateActivityAsync(context, typeof(HttpEndpoint));
    
   httpEndpointActivity.Path = webhook.Path;
   httpEndpointActivity.ReadContent = true;
   httpEndpointActivity.TargetType= webhook.PayloadTypeName is not null and not "" ? Type.GetType(webhook.PayloadTypeName) : default;
}

return new ActivityType
{
   TypeName = webhook.Name,
   Type = typeof(HttpEndpoint), // A .NET type that represents this activity. Notice that the activity type name is not the same thing.
   Description = webhook.Description is not null and not "" ? webhook.Description : $"A webhook at {webhook.Url}",
   DisplayName = webhook.Name,
   ActivateAsync = context => ActivateActivityAsync(context, webhook),
   Describe = () => 
};
```

### Persistence Providers

Because we introduced a new store, we also need to provide implementations for these:

- Elsa.Webhooks.Persistence.EntityFramework
- Elsa.Webhooks.Persistence.MongoDb
- Elsa.Webhooks.Persistence.YesSql

Since we would implement IStore<T>, each concrete provider can inherit from the abstract `Store<T>` base class. Look at existing provider implementations for details.

In addition to the aforementioned providers, we always need to provide an in-memory implementation as part of the core library itself (Elsa.Webhooks), following the same pattern used in Elsa Core itself.

### API

In addition to the models and services provided by the Webhooks module, we also need to expose API endpoints to allow the user to create, update and delete webhook definitions via the dashboard, which itself will consume the API endpoints.

Although endpoints will be implemented using API Controllers, we will follow the API Endpoint pattern as described [here](https://github.com/ardalis/ApiEndpoints) (without actually using the ardalis.ApiEndpoints library; we're just copying the pattern).

We'll need the following endpoints:

/Endpoints
   /Webhooks
      /List
      /Get
      /Post

### Dashboard

Finally, we need to add a new menu item to the dashboard called **Webhooks**. Clicking that item would take the user to a list view showing all webhook definitions defined, and a **Create** button to create new ones. The page would look similar to the Workflow Definitions list view.

One caveat we have to deal with right now is that the Dashboard application does not consume the API endpoints directly; instead, it goes through an gRPC endpoint, which in turn accesses the REST API endpoints. This is a choice that was made initially, but I think we might want to reconsider that choice and invoke the REST API directly to simplify things. Ultimately. the REST API needs to be designed such that third-party dashboards can consume the API easily in order to manage workflows anyway. 

**API Client**
So as part of this work, I suggest to add another class library called `Elsa.Webhooks.Client` that depends on `Elsa.Client` to reuse certain useful aspects for an API client such as the `ElsaClientOptions` model and serialiation settings.

The `Elsa.Webhooks.Client` itself would expose an interface called `IElsaWebhooksClient` interface that invoke the API endpoints (using Refit to auto-generate an actual implementation at runtime).

The dashboard can then use this API client to CRUD webhooks.

**Comment by craigfowler** [comment]
This all looks & sounds very good but I wonder if there's another aspect where we have capacity for reuse. Activity execution (without any new interface) already has a capacity to return a complex object result/outcome. We also have precedent already for running predicates over those returned outputs.

Could this not be done within the existing Framework for an activity? Essentially return an object (from our generalised "http endpoint") which models the request it received. Then, treat it a little like a UserTask. When the outcome matches this, then to do this next, when it matches that, do that next.

This might allow us to reduce the amount of "new infrastructure" that this feature requires.

This isn't really a fully-formed suggestion though, more just a musing. After a full-on day at my 9-5 job, I've run out of brain for today 🤪. If any of this is nonsense, feel free to ignore.

**Comment by craigfowler** [comment]
The other side of this is to beware [the inner-platform effect](https://en.wikipedia.org/wiki/Inner-platform_effect?wprov=sfla1). In a way, what we're talking about here kind of reinvents ASP.NET API controllers.

Whilst there's a justification that "sure, a power user might want this", how useful would it be in the real world? Particularly in a scenario where the user has sufficient skill to understand the subtleties of http but is unable to write an API controller. If the intention is to use a workflow to provide a set of APIs, then ASP.NET might have been a better tool.

Not saying I'm specifically against doing it or think it's a bag idea, but playing devil's advocate to provide some food for thought 🤔

**Comment by jwillmer** [comment]
> Whilst there's a justification that "sure, a power user might want this", how useful would it be in the real world? 

I know from experience that the (power) users are very bad in organizing the workflows. Mostly because they haven't learned to think like developers. So every bit of structure we can provide will help them stay organized. 

In that regards the webhook manager can help users to give an overview of existing webhooks - and help them to centrally manage them. And we will be able to add more insights in the future. 

Main benefits I see:

- central overview of (all?) existing webhooks
- overview of workflows that get triggered by a specific webhook
- easy update of a webhook url that translates to all workflows that are using it

**Comment by sfmskywalker** [comment]
@craigfowler Yep, one only needs the `HttpEndpoint` (formerly known as `HttpRequestReceived`) activity to implement workflows that execute when an HTTP request is received (e.g. an external service that executes a webhook configured to point to the workflow's URL).

But because webhooks are such a powerful notion when automating and connecting systems, there are scenarios where you want to associate multiple workflows with a single webhook. Having this webhooks "extension" helps managing these webhooks. In addition, it allows the user to list workflows by webhook.

This is all very specific to webhooks of course, and not so much to Elsa itself. Which is why **we are not changing Elsa** itself to have a notion of "webhooks" - no new infrastructure required other than what I had already envisioned: a modular Blazor Dashboard Application.

So instead, this is to be seen as an add-on to Elsa and Elsa Dashboard. I hadn't heard before of the inner-platform effect, but I actually envision having a library of add-on packages that folks can use to add more functionality to the Elsa Dashboard application to build workflow-driven software.

We'll have webhooks first, but e.g. forms might follow later, allowing users to design forms and have them trigger workflows (workflows acting like "code-behinds"). Both will end up in their own repos (as is the case for most of the activity libraries we have now as part of the main repo).

I do realize there are existing modular application frameworks out there, and in fact I also intend on providing Elsa modules to integrate with them as well (like Orchard Core, ABP, and perhaps even Oqtane).

You are absolutely correct when saying that all of this could be done with a controller and your own application. But you could also write your own dashboard application specific to your needs, and only use the workflow designer.
But Elsa is more than that: it provides a set of layers: at the core we have workflow primitives, then an API, then a reusable (set of) designers, then (a set) of dashboards, then a SaaS, and then the moon ;)

As always, I do appreciate the feedback, so please keep that coming!

**Comment by craigfowler** [comment]
As this is marked up for Elsa 2.0 I've moved to **do soon**.

**Comment by jwillmer** [comment]
It has already been started. Dev will be assigned tomorrow.

**Comment by skivsoft** [comment]
WIll start working on it.

**Comment by Axeleron007** [comment]
Hi, I will start working on it.

**Comment by sfmskywalker** [comment]
This work is done. Thanks everyone!
