### ISSUE TITLE
Manual workflow trigger in the designer

### ISSUE THREAD

**Issue by jwillmer** [elsa-workflows/elsa-core#671]
As a user I like to have a button in the designer that starts my workflow (temporarily enables the workflow to receive webhook calls). 

- [x] Add "Execute Workflow" button in UI. Clicking on it will rename it to: "Stop Execution"
- [x] Temporarily enable the workflow version when "Execute Workflow" was clicked. 
- [ ] Disable workflow version when "Stop Execution" was clicked or after a 5 min timeout. (User might have closed the browser)
- [x] Display successful node execution with a green mark and unsuccessful with a red mark
- [x] Store context of each step for #1321
- [x] Disable workflow after first execution

![image](https://user-images.githubusercontent.com/1503577/109173724-75c27a00-7784-11eb-8193-d81918a21ca0.png)

**Comment by sfmskywalker** [comment]
Neat. A couple of points:

1. Instead of temporarily publishing the workflow, we might use some other flag, i.e. "IsTesting" (in addition to the IsPublished flag). The workflow engine would treat these workflows as if they were published, but simplifying the process of removing the "Preview" flag. Because if we temporarily publish a workflow draft (which might already have a published version older than the current latest draft), we now need to "remember" to publish the previously published version. It's not impossible of course, but maybe a little bit awkward. In contrast, having a clear "preview" mode might model the system more closely to what the user is doing, which is previewing/testing their workflow changes without affecting existing published workflow definitions.
2. We need to consider also workflows that don't start with a webhook, or any other trigger for that matter. For instance, some workflows might start with a simple SendMessage activity, where this workflow is invoked explicitly by the hosting application (i.e. from a controller). We should be able to test these workflows as well, allowing the user to provide input to the workflow, when necessary. A good way to deal with this might be to allow for the user to configure the workflow with default input, used automatically when previewing the workflow execution.
3. This settings section described in point 2 might also allow the user to control whether or not the workflow should run automatically. In the case of testing a workflow that uses a webhook as its trigger, the user might not want to automatically run the workflow, but trigger the webhook from the external system. At the same time, it might be convenient to allow the user to simulate a webhook request by letting Elsa perform a configured HTTP request.

The above points are not intended to be implemented as part of this issue immediately, but as something to keep in mind as we design this initial version.

**Comment by jwillmer** [comment]
Some addition to your 3. point:
- If the user can set debug input values for triggering the workflow I think it should be in the same format as we [reference previous activity data](https://github.com/elsa-workflows/elsa-core/issues/675). That would allow the user to override (mock) the input of the first activity (for example a webhook). So he doesn't even need to send anything to the system to test it.

**Comment by sfmskywalker** [comment]
Yes, good.

**Comment by jwillmer** [comment]
Might be added as a menu option: https://github.com/elsa-workflows/elsa-core/issues/1080

**Comment by jwillmer** [comment]
@sfmskywalker as discussed the follow up tasks I see would be #1321 and #1322

**Comment by sfmskywalker** [comment]
1. We need a JSON schema field for HTTP Endpoint activity.
2. We need a typescript definition provider that uses the JSON schema and generate a typescript definition type of it.
3. User needs to be able to test a workflow.
	- Create a workflow instance.
	- As workflow executes, needs a SignalR connection that sends info from server to designer.
	- When e.g. a webhook HTTP request comes in, display posted JSON as activity input.
	- When user views this HTTP input, display a button called e.g. "Use as Schema".
	- When clicking this button, convert the JSON into a JSON schema and store it in the HTTP Endpoint's JSON schema field.

**Comment by jwillmer** [comment]
After the demo today we came up with the following point that need attention:

JSON schema in activity
- [ ] add a link to an online converter
- [ ] validate the json (invalid json is currently allowed but will break intellisense)

Sidemenu aka fly out
- [ ] add padding to start button
- [ ] move execution details (payload) to associated activity menu

Execution
-  [ ] Add a direct link to the url that triggers the workflow (copy&paste correlation id is painfull)
-  [ ] `use as schema` button should use the request payload to generate schema. not the whole request
-  [ ] when clicking on execute the first activity should display a spinner instead of an orange icon while it waits for a request
-  [ ] replace colored status ring with icons representing (pause, success and error) and move it to the right

**Comment by jwillmer** [comment]
As discussed in the last meeting:

- [ ] separate the workflow status from the activity status by moving activity status to the activity pop up and rename state "suspended" to "waiting"

- [ ] create an orange border around the workflow when switching to test tab to indicate the ui change: 
![image](https://user-images.githubusercontent.com/1503577/134668207-25bd0c9d-0796-45bd-a479-fe3e6c1eea61.png)

**Comment by jwillmer** [comment]
- [ ] test with timers
- [ ] fix `orange test border` so that it is not over the scroll bar

**Comment by jwillmer** [comment]
Closed since related pull request got merged: https://github.com/elsa-workflows/elsa-core/pull/1542

**Comment by sfmskywalker** [comment]
1. Reference `Elsa.WorkflowTesting.Api`
2. Add `services.AddWorkflowTestingServices();` to your startup code.
