### ISSUE TITLE
Allow Composite Activities to become a Trigger

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#738]
Currently, composite activities staring with a trigger activity that are the starting activity of a given workflow will not cause the workflow to be triggered.

This should be changed so that users can create a composite activity and use them as triggers.

To allow for this, all we would have to do is update `TriggerIndexer` to consider not only starting activities that are blocking, but also activities that are composite activities that start with blocking activities.

**Comment by craigfowler** [comment]
_@sfmskywalker and I have had had a chat about this issue in Discord, and here are the highlights of that (for the record)._

## Possible refactoring opportunity: "Triggers are bookmarks"
We discussed the possibility to refactor so that `WorkflowTrigger` is a subclass of `Bookmark` instead of containing a bookmark.  This seems reasonable since a trigger is 'a model object' and not a service.  The benefit would be that we can treat triggers and bookmarks polymorphically.

## This issue requires a quite deep rework
When using a trigger to start a workflow with a composite activity then the correct process is:
1. The bookmark/trigger must schedule the composite activity
2. The scheduled composite activity must then be told _which of its own contained start activities_ to schedule
3. This could theoretically be recursive because a composite activity could contain further composite activities

At present, the logic for step 1 (above) does not pass the whole bookmark/trigger object as a parameter.  Thus it's impossible to get sufficient information through the API, to reach the scheduled activity.

_For this reason, we have agreed to **remove this issue from the 2.0 milestone**.  It would have a very wide scope (regression impact, risk of overrun, breadth of changes etc).  Given that 2.0 is already going to miss its original deadline, it's not a good idea to dive into major work at this stage.  Because this work will require a **breaking** API change, the earliest we will be able to address it is 3.0._

## Possible dev approach
The dev approach for this issue is not yet agreed 100%, but we have spoken about the following:

### Bookmarks can have a child bookmark
Alter the `IBookmark` interface and add the following:

```csharp
/// <summary>
/// Gets an optional contained bookmark.  This is used when the bookmark is used to schedule a
/// composite activity.  The inner bookmark is used by that composite to perform internal scheduling.
/// </summary>
IBookmark? InnerBookmark { get; }
```

### When that bookmark is used
Going back to the 'deep rework' which would be required to implement this, what we have already means that the trigger or bookmark will be used to provide parameters to another service, in order to schedule an activity.

What we would like to do instead is to refactor those services so that _the whole bookmark/trigger object_ may be passed as a parameter to those service(s).  This will mean that we can refactor/rework so that - when this leads to the scheduling of an activity, if **both** of the following are true:

* The scheduled activity is a composite activity
* The bookmark's inner bookmark is not null

Then the inner bookmark will be used with the composite activity, in order to schedule one of its own child activities.

### Desire for polymorphism
It's interesting that both "scheduling an activity within a workflow" and "scheduling a child activity from a composite activity" are very conceptually similar procedures.  It would be great if we could find a way to treat these two polymorphically so that they can firstly share a process of logic, but also so that the passing-forward & usage of bookmarks does not need to introduce a great deal of code change.

**Comment by sfmskywalker** [comment]
This has been implemented in Elsa 3, so I wil go ahead and close it. Thanks for the deep thinking, @craigfowler !
