### ISSUE TITLE
Migrations Failed during Testing Elsa 2.0.0-preview7.1545

### ISSUE THREAD

**Issue by buzzlu** [elsa-workflows/elsa-core#755]
I am try to move elsa 1.0 to 2.0.

when I use command dotnet ef database update --context Elsa.Persistence.EntityFramework.Core.ElsaContext for migration. No tables are created. 

Below are the packages used:
    <PackageReference Include="Elsa.Persistence.EntityFramework.Core" Version="2.0.0-preview7.1545" />
    <PackageReference Include="Elsa.Persistence.EntityFramework.SqlServer" Version="2.0.0-preview7.1545" />

Here is my code:
           var elsaSection = Configuration.GetSection("Elsa");

            services
                .AddElsaCore(elsa => elsa
                    .UseEntityFrameworkPersistence(ef =>
                    {
                        ef.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"));
                    }, autoRunMigrations: true)
                    .AddHttpActivities(elsaSection.GetSection("Http").Bind)
                    .AddEmailActivities(elsaSection.GetSection("Smtp").Bind)
                    //.AddTimerActivities()
                    .AddWorkflowsFrom<Startup>()
                );

            services
                .AddElsaApiEndpoints()
                .AddElsaSwagger();

Does something Missed?

Thanks.

**Comment by craigfowler** [comment]
Hi @buzzlu I think you have missed the second parameter to `UseSqlServer` where you tell EF where to find those migrations.  Because you didn't tell it, it didn't know where to look, so it didn't find any migrations to run.  I would have expected to see something like the following.  I only including the call to `UseEntityFrameworkPersistence`, the rest is not relevant:

```csharp
.UseEntityFrameworkPersistence(ef =>
{
    var migrationsAssembly = typeof(Elsa.Persistence.EntityFramework.SqlServer.SqlServerElsaContextFactory).Assembly;

    ef.UseSqlServer(
        Configuration.GetConnectionString("DefaultConnection"),
        opts => opts.MigrationsAssembly(migrationsAssembly.GetName().Name)
    );
}, autoRunMigrations: true)
```

@sfmskywalker For the future, shouldn't we provide an extension method to make this more convenient, [like we do in the Sqlite provider]?  If so, even though I think I've answered the original question I could turn this issue into an enhancement to add that extension method.

[like we do in the Sqlite provider]: https://github.com/elsa-workflows/elsa-core/blob/feature/elsa-2.0/src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Sqlite/DbContextOptionsBuilderExtensions.cs

**Comment by buzzlu** [comment]
@craigfowler : Thanks for your correction.
