### ISSUE TITLE
Using JSON.stringify in a Javascript expression can throw StackOverflowException (infinite loop in Jint JSON serialization)

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#761]
Hi everyone,
Since this is my first issue with Elsa and I have started experimenting with it only recently, I apologize if this is an error on my part.

I've downloaded Elsa (1.5 from github head) sources and compiled Sample 19.
Activated it for testing with "dotnet run" in its folder.
Then I did a little workflow of my own whose JSON export can be found here: [https://www.dropbox.com/s/34hd7vbksmvdk25/stack_overflow.json?dl=0]().

In short it has:
1. Receive HTTP request
2. Set var Body = JSON.parse("{\\"foo\\":\\"bar\\"}")
3. Write HTTP response with 200 and body set to: JSON.stringify(Body)
All expressions both in 2 and 3 are JavaScript.

And this seems to produce stack overflow exception when evaluating body for HTTP Response.
Part of stack trace follows (top two lines repeat indefenitly): 
   at Jint.Native.Json.JsonSerializer.Str(Jint.Native.JsValue, Jint.Native.Object.ObjectInstance)
   at Jint.Native.Json.JsonSerializer.SerializeObject(Jint.Native.Object.ObjectInstance)
   at Jint.Native.Json.JsonSerializer.Str(Jint.Native.JsValue, Jint.Native.Object.ObjectInstance)
   at Jint.Native.Json.JsonSerializer.SerializeObject(Jint.Native.Object.ObjectInstance)
   at Jint.Native.Json.JsonSerializer.Str(Jint.Native.JsValue, Jint.Native.Object.ObjectInstance)
   at Jint.Native.Json.JsonSerializer.Serialize(Jint.Native.JsValue, Jint.Native.JsValue, Jint.Native.JsValue)
   at Jint.Native.Json.JsonInstance.Stringify(Jint.Native.JsValue, Jint.Native.JsValue[])
   at Jint.Runtime.Interop.ClrFunctionInstance.Call(Jint.Native.JsValue, Jint.Native.JsValue[])
   at Jint.Runtime.Interpreter.Expressions.JintCallExpression.EvaluateInternal()
   at Jint.Runtime.Interpreter.Expressions.JintExpression.Evaluate()
   at Jint.Runtime.Interpreter.Expressions.JintExpression.GetValue()
   at Jint.Runtime.Interpreter.Statements.JintExpressionStatement.ExecuteInternal()
   at Jint.Runtime.Interpreter.JintStatementList.Execute()
   at Jint.Engine.Execute(Esprima.Ast.Script)
   at Jint.Engine.Execute(System.String, Esprima.ParserOptions)
   at Jint.Engine.Execute(System.String)
   at Elsa.Scripting.JavaScript.Services.JavaScriptExpressionEvaluator+<EvaluateAsync>d__8.MoveNext()
   .....

If I put Body.foo as response body it works ok.
However if I put stringify (even if it is just JSON.stringify(Body.foo)) it breaks.

Am I doing something wrong? If yes could someone explain me what.
If not, what can I do to help you solve this? 

Thanks in advance.

**Comment by sfmskywalker** [comment]
We'll have to look into this, but should you have the need to parse JSON strings in workflow expressions right now, you can install custom JS functions into the evaluator that then gets executed with C#. See [DateTimeScriptEngineConfigurator](https://github.com/elsa-workflows/elsa-core/blob/feature/elsa-2.0/src/scripting/Elsa.Scripting.JavaScript/Handlers/DateTimeScriptEngineConfigurator.cs) for an example of adding custom JS functions that get executed in .NET.

**Comment by tomy2105** [comment]
Yes, I kind of guessed that Set var block (and some other variables) are treated different than others in Javascript expressions. My guess is that one are "native" Javascript variables and others are actually .NET and use Jints .NET interoperability layer to fetch them (or something like that). 

Maybe I did something wrong, but in short they seem to behave differently and this could be confusing for workflow developer.

Maybe you should pick only "native" JS behavior to have consistent behavior? (yes I know it probably requires a lot of work :()

**Comment by tomy2105** [comment]
Just a quick comment, I compiled Elsa 2.0 from code and it has same problem.

**Comment by craigfowler** [comment]
@sfmskywalker What are your thoughts on priority for this?  Thanks

**Comment by sfmskywalker** [comment]
Regarding the SO issue, that is something we should fix as part of the 2.0 milestone.

Regarding @tomy2105 's suggestion to pick only native JS behavior, I am not sure what that means, but I do agree that things should work consistently. This is a reiterative process. The specific example of `lastResult` is not applicable for Elsa 2 since it has been removed. When new JS/Liquid issues are identified, we look at them on a case by cases basis.

**Comment by craigfowler** [comment]
@tomy2105 - StackOverflowException reproduced exactly as reported.  Thanks.

**Comment by craigfowler** [comment]
Right!  I have done some work on this and improved the handling of expression results.  Certainly the repro case reported in this issue is fixed (enough to close this issue) but I want to make it clear that I think there's still a lot of work to be done, and actually I'm not 100% convinced that this work should be done by us.

## Jint can't round trip it's own objects via stringify
Quite simply, if you use Jint to _create_ a plain old JS object like `{ foo: 5, bar: 'A string'}` then when you get that object back into the .NET world it will be a `System.Dynamic.ExpandoObject`.  I don't see any other way to sensibly do that actually, since in JS you can just creates objects without needing to instantiate classes.

However, if you then put that object back into Jint using `engine.SetValue` with a variable name, you will find that you can't stringify that object.  Well, you can, but you'll get the string result `"{}"` and not what you wanted.

## How we used to try and work around that
Elsa tried to work around that by converting the ExpandoObject into a Newtonsoft/JSON.NET `JToken` object.  That worked as far as accessing values from the object was concerned, but if you try to `JSON.stringify` that object from Jint, _this is what causes the stack overflow_.

## How this is fixed now
Rather than converting `ExpandoObject` to a `JToken`, instead we now convert to `System.Collections.Generic.Dictionary<string,object>`.  That works with JS property access, it can be stringified (with the expected result) and it's still a sane data-type in .NET land.

## What I actually want to do
What I'd like to do is actually to create a small repo case for Jint and send it to them as an issue.  I think that if ExpandoObject would natively stringify (with the correct results) then _it would put us in a much better place_.  We could remove a lot of complex code from Elsa because it would no longer be required.  It would also give us a more sane overall result.

I'll update this issue once I've got that repro together and the issue reported to Jint.

**Comment by craigfowler** [comment]
That Jint issue is https://github.com/sebastienros/jint/issues/855.  It _might get closed as a dupe_ in which case it will probably duplicate https://github.com/sebastienros/jint/issues/347.

I created [a repo for the repro case](https://github.com/craigfowler/jint-stringify-expandoobject) (in case you care to see for yourself).
