### ISSUE TITLE
As a developer, to support a multi-tenant app, I must be able to instantiate different implementations of a workflow definition, via DI

### ISSUE THREAD

**Issue by kassemdarwish** [elsa-workflows/elsa-core#762]
Following up on issue #748, in addition to connecting to different database by changing the connection string by tenant, you might actually want to register a different implementation of a given workflow as per the requirements of the different tenants. Some of the scenarios that I think should be supported by the `AddWorkflow()` ([link](https://github.com/elsa-workflows/elsa-core/blob/master/src/core/Elsa.Core/Extensions/ElsaServiceCollectionExtensions.cs)) method are the following:

- Generic method with a factory method which resolves the instance at runtime.
- A non-generic method which allows locating the type at runtime (maybe from an assembly configured by tenant) and then instantiates the workflow implementation which implements a given interface.

What do you think?

**Comment by craigfowler** [comment]
I think that this is actually _kind of possible_ right now, although for the sake of your sanity I don't think I'd actually recommend doing it this way.

## How you _technically_ could it right now
When registering workflow definitions, really you're just adding the implementer of `IWorkflow` to dependency injection.  The actual workflow definition which gets created is a result of that workflow object's `void Build(IWorkflowBuilder builder)` method.  Of course, you can execute that logic (at runtime) however you want.  So you could constructor-inject whatever tenant-specific services you want into the workflow class and run the logic in that `Build` method any way you want.

But - when you're using workflows defined in code - is "having the same workflow with the same name & class, behaving differently under different tenants" a good idea?  _I personally think not (and that it would just create a lot of confusion)._

## But why vary coded workflows per-tenant?
One of the things about multi-tenancy (at least in our use case) is that every tenant uses the same C# logic, they just vary by the data.  When you start varying the code which executes per-tenant then things begin to get quite confusing.  Would it not be better (in your use case) to store the workflow definitions in the database rather than have them written in code?  That way you're actually leveraging your existing multi-tenancy and not adding further complexity to the logic.

## Adding workflows to DI is a once-only thing
The `AddWorkflow` method - as you've identified - just registers it into DI.  We only get one stab at doing that, during application startup.  We can't add further workflows into DI, based on runtime logic, because we already built the DI container (and we don't depend on any particular container impl, which might allow us to add extra services in later).

Perhaps better might be to add all of the possible workflow classes for every single tenant into DI, and then use tenant-specific logic to pick between those workflow classes.  In other words, pick between fundamentally-different workflows based on tenant, rather than trying to have multiple same-named workflows that have different behaviours per-tenant.  But they all get registered all the same when the app starts up.

**Comment by craigfowler** [comment]
Also invite @sfmskywalker to comment.

**Comment by sfmskywalker** [comment]
I think it all comes down to what model of multitenancy we think Elsa should implement. Initially, I wanted to try and keep the concept of multi-tenancy _outside_ of the scope of Elsa, and if someone can offer any insights as how we could make this possible, then I think we should take that into consideration. Barring such insights at the moment, it seems to me that the most flexible & straight-forward implementation is the "complete multi-tenant" model, allowing implementers of Elsa to share the same database tables but discriminated by tenant ID.

Should the implementer desire more isolation, one could take advantage of @craigfowler's modifications to the EF Core provider's service registration extensions that allows you to select a db context from your own context factory.

And if you wanted the ability to resolve certain service implementations per tenant, then you can take the same approach that Orchard Core does, which is instantiating a **service container per tenant**. This is something that could be done external to Elsa. You could even use Orchard Core's framework libraries to implement this together with Elsa in your own app today.

But if all you want is to associate a certain set of workflows per tenant, then you can do so today with Elsa since workflow definitions have a `TenantId` field, as does `IWorkflowBuilder` (which allows you to set a tenant ID when using the workflow builder API). Which means that you totally could implement two different workflows that only execute for a given tenant.
Just keep in mind that the multi-tenant story in this area is far from complete as of this writing. For example, if you were to implement a workflow that starts with an `HttpEndpoint` trigger activity, it doesn't currently know what tenant ID to select for.

**Comment by kassemdarwish** [comment]
@craigfowler to answer your question as to why we would vary coded workflows per tenant, take the following example of managing a university program:
- Tenant A: Program starts out as a Draft > it is set to ready after all of its requirements are available > the institution manager sets it as Active to allow students to register > it can be closed if the institution manager chooses to do so
- Tenant B: Program starts out as a Draft > it is set to ready after all of its requirements are available > the institution manager sets it as Active to allow students to register **which results in it being escalated to University Program Coordinator for approval > once approved, status changes to Active** > it can be closed if the institution manager chooses to do so
As you can see, it's basically the same feature (Managing a program), but every tenant might have slight differences in how it manages its programs.

**Comment by craigfowler** [comment]
Thanks for that use-case @kassemdarwish .

I also agree with @sfmskywalker though, that right now we just don't completely understand what we want with regard to Elsa & the larger meaning of multi-tenancy.  The EF Core enhancements I did were a single very specific enhancement for a single very specific use-case, and I knew I could make that work just by "tinkering on the fringes".

I'd be tempted to open a new issue as a "Multi-tenancy epic", which gathers together all of the smaller multi-tenancy stories/use-cases which are requested, so that after Elsa 2.0 is released, we can go through and start making those kinds of decisions about exactly what we want to support.  Perhaps not even immediately after Elsa 2.0 either.

**Comment by kassemdarwish** [comment]
@sfmskywalker this is what I have in mind for implementing multi-tenancy in our project in terms of what is relevant to Elsa:

As explain in my reply to @craigfowler, every university might have slightly different workflows describing what the same features should do. So the plan is to break down those features into domain-specific custom activities that will be used as the building blocks of implementing those features as per the requirements of each tenant. Accordingly, we are currently evaluating two approaches:
**Approach 1: Different docker container per tenant**
- Implement required interfaces in a tenant-specific class library
- Package that class library with the microservice docker container
- Deploy the container into Kubernetes
- On application startup, load all dependencies from the DLL (this would require registering dynamically loaded types, ex: `services.AddWorkflow<IProgramManagementWorkflow>(programManagementWorkflowType)`)
- Route inbound traffic to the correct container (pod) using Ingress rules.

**Approach 2: Different DLL per tenant**
- Each tenant will implement the required interfaces in a tenant-specific library
- All DLLs will be placed in a configurable location and will be packaged into the microservice's container
- Deploy the microservice container into Kubernetes
- A tenant provider will resolve the tenant from the HTTP request's host.
- Based on the resolved tenant, register named instances of the dependencies (ex: `services.AddWorkflow<IProgramManagementWorkflow>(programManagementWorkflowType, myTenantName)`)

**Comment by kassemdarwish** [comment]
> Thanks for that use-case @kassemdarwish .
> 
> I also agree with @sfmskywalker though, that right now we just don't completely understand what we want with regard to Elsa & the larger meaning of multi-tenancy. The EF Core enhancements I did were a single very specific enhancement for a single very specific use-case, and I knew I could make that work just by "tinkering on the fringes".
> 
> I'd be tempted to open a new issue as a "Multi-tenancy epic", which gathers together all of the smaller multi-tenancy stories/use-cases which are requested, so that after Elsa 2.0 is released, we can go through and start making those kinds of decisions about exactly what we want to support. Perhaps not even immediately after Elsa 2.0 either.

I think that would be great, as I strongly believe a workflow engine like Elsa would have excellent use-cases in multi-tenant systems.

**Comment by sfmskywalker** [comment]
Multitenancy is being tracked as a feature in #242.

**Comment by douglasg14b** [comment]
This issue is tracked in the parent issue and is closed as completed in that tracking parent. Indicating this feature works and is usable. But it does not appear to be the case.

Can this issue be re-opened?
