### ISSUE TITLE
Missing functionality in designer

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#782]
Here is a short list of what I, sorely, miss in designer after toying with it for couple of days:
1. Double click to edit
2. Delete multiple activities
3. Cut/Copy/Paste activitiy(ies)
4. Zoom in/out
5. Undo/Redo
6. Better difference in colors (maybe should be called contrast) between background and activity(ies)

Can you comment if those could be added or are impossible to do in near future.
Thanks.

**Comment by craigfowler** [comment]
This looks like a really good list of feature suggestions @tomy2105 - I even noticed that [you've sent a PR for double-click-to-edit], which I knew we already had as #670, so thankyou for that!

What I'm going to do is break the remaining suggestions into issues of their own, so that they can be prioritised/developed independently.  A "big ball of assorted improvements" issue is more likely to be lost in the background noise than a few narrowly-focussed/specific issues.

[you've sent a PR for double-click-to-edit]: https://github.com/elsa-workflows/elsa-core/pull/790

**Comment by craigfowler** [comment]
@tomy2105 I'm going to close those issue in favour of the five separate ones I've created from it.  We can deal with those independently now.
