### ISSUE TITLE
Use of an HTTP request QueryString in a Javascript expression can raise InvalidCastException unless toString() is used

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#785]
I stumbled upon a problem, better to say I'm confused......
I have HTTP endpoint immediately followed by HTTP response.

If I place: **"" +input.QueryString["foo"]** for content I get correct response (text/plain) used.
However if I place: **input.QueryString["foo"]** nothing is displayed and console reports warning:
warn: Elsa.Expressions.ExpressionEvaluator[0]
      Failed to evaluate expression input.QueryString["foo"] using syntax JavaScript
      System.InvalidCastException: Object must implement IConvertible.

Can you please explain why one works and other not and if is there any bit more verbose documentation which could solve my confusion. Thanks.

**Comment by craigfowler** [comment]
Yes, I think I see what's happened.  [In the `ReceiveHttpRequest` activity] the `QueryString` property of the model object (which is what eventually becomes `input` in the subsequent activity) is a `Dictionary<string, StringValuesModel>` and not a `Dictionary<string, string>`.  If you go take [a look at the `StringValuesModel` class] you'll notice that it doesn't implement `IConvertible`.

In your JS, when you use the `"" +` prefix, you're forcing JavaScript coercion to string, and I'm going to assume that Jint (the behind-the-scenes JS engine Elsa uses) takes that as a cue to execute the `ToString()` function on the expression value.  What `StringValuesModel` _does have_ is a `ToString()` method, which returns a sensible result.

I haven't tried it myself but I suspect that `input.QueryString["foo"].toString()` would also give you the result you want (and might look less ugly).

As a follow-up, @sfmskywalker - do you think it would be reasonable for `StringValuesModel` to implement `IConvertible`?  Most of the time it's going to be directly convertible to string, and perhaps we can convert it to other types if the input is appropriately formatted.  This issue could become an enhancement-request to do just that?  Then @tomy2105 (and others) wouldn't have this kind of issue.  I would suggest that most developers expect a query string value to be treatable directly as a string and not to require conversion (even if that isn't strictly true in .NET).

[In the `ReceiveHttpRequest` activity]: https://github.com/elsa-workflows/elsa-core/blob/master/src/activities/Elsa.Activities.Http/Activities/ReceiveHttpRequest.cs#L100
[a look at the `StringValuesModel` class]: https://github.com/elsa-workflows/elsa-core/blob/76ce99db9425b58e9fa8337511edda5889b77783/src/activities/Elsa.Activities.Http/Models/StringValuesModel.cs#L5

**Comment by tomy2105** [comment]
One thing more about StringValuesModel....
It is kind of cumbersome (at least for me) to write a code which accepts both single and multiple values. (checking for null and all).
I would always fill both (Value containing the first value of Values).
So you could you use both Value and Values[0] to fetch first. At the moment you need Value if it is single and Values[0] if there are more.
But this is just my personal preference.

**Comment by tomy2105** [comment]
One more note.

My HTTP endpoint variables were just an example.
I'm worried about mixing JavaScript and C# inside single expression might bring confusion to less programmer savy users.
Is there a way to make it simpler (or more blended)?
Or even make full support for C# only expressions so there wouldn't be any mixing?

**Comment by craigfowler** [comment]
@tomy2105 having done [some work with C# expressions in a project of my own], I eventually decided that [most of the time they are a bad idea].  The reason is that to make them usable, they need to leverage the `dynamic` type, which has all sorts of limitations of its own.  Combined with their performance penalty, I sort-of-wish I had never supported them.

I do agree that the JavaScript expression syntax could certainly be improved though, so that it's easier to use.  I notice you've opened a few issues on this repo and I hope you continue to add valuable suggestions like this 😄 

[some work with C# expressions in a project of my own]: https://github.com/csf-dev/ZPT-Sharp/tree/master/Evaluators/ZptSharp.CSharpExpressions
[most of the time they are a bad idea]: https://csf-dev.github.io/ZPT-Sharp/articles/ZptReference/Tales/CSharpExpressionLimitations.html

**Comment by tomy2105** [comment]
> I haven't tried it myself but I suspect that `input.QueryString["foo"].toString()` would also give you the result you want (and might look less ugly).

Yes, the `input.QueryString["foo"].toString()` works, and so does `input.QueryString["foo"].ToString()` :) which in sense call same code (C# implementation of `ToString()` on the `StringValuesModel`) but using two different approaches :). 
You see how confusion can start :).

**Comment by craigfowler** [comment]
I mostly-agree.  To some extents though this is just the nature of what we are doing.

## I don't think it's a great idea to try and "be more like JavaScript"
Jint allows us to refer-to & manipulate objects from JavaScript language & syntax.  But - Elsa is still fundamentally a .NET application, so a lot of the objects we are using came "from the .NET world".  _JavaScript is the foreigner here and .NET objects are the natives_.  I know that it's nit-picking but C# and .NET are not quite exactly the same thing.  Jint is giving us 100% JavaScript language (no C# at all) but the object we're working with is still the .NET one.

Now we could in theory duplicate the API and map some .NET objects over to "special JavaScript friendly objects" (I suppose [they would technically be adapters](https://en.wikipedia.org/wiki/Adapter_pattern)) which we give to Jint but:
* That's a lot of work
* It will never be finished (because what about your own app's models & objects?)
* It would have to be maintained (make future changes twice)
* They wouldn't really bring that much benefit, compared to the cost

All-in, it would probably end up at the back of the priority queue and to be honest I wouldn't recommend doing it at all.

## I do think it's a good idea to generally improve the API
Changes such as:
* Making `StringValuesModel` implement `IConvertible` so that it plays nicely with Jint and "does what you would expect".
  * I appreciate that in a JS expression editor in the workflow designer, no matter how many UX/QoL improvements Elsa makes, we're still not giving you a full IDE
  * It would also be quite difficult to syntax-check those expressions ahead-of-time to check that they are correct/don't have errors
* Generally improving the (.NET) API for objects, so that they are easier to use
  * This helps us regardless of whether we are using C# or JS expressions or anything
* Improving the Elsa documentation with both examples and reference material

Those kinds of things are comparatively cheaper to do, I think give us more "bang for the buck", and leave us in an overall better place.

## I'm on this
I'm picking up this issue to work on.  What I'll be doing is:
* Make `StringValuesModel` implement `IConvertible` (fixes that one specific crash issue you reported)
* Take a look into the history of those `Value` & `Values` properties to see if I can find a reason why they are written that way (@sfmskywalker if you have any hints/guidance that'd be great!)
* If there's no good reason perhaps simplify it to just one collection property and assume that anyone who wants a single value would use `.FirstOrDefault()` or `ToString()` (or in JS world, just the object alone which will be implicitly convertible to string via `IConvertible`).

**Comment by sfmskywalker** [comment]
@craigfowler Excellent. Regarding the Value vs Values, there’s no historical reason for that I don’t think. I think it’s just there to mirror .NET’s version of StringValues, which has those two properties as well. I’m not sure I see why it’s a disadvantage to having both. Isn’t it convenient to be able to access a parsed list of values in case there are multiple values for a given query string parameter? And if you don’t care about possible multiple values, you simplify stick with Value.

**Comment by craigfowler** [comment]
Cool. There was an oddity in the ctor which meant that one of `Value` or `Values` would always be null. Probably just an oversight.

Amongst other improvements I've made `Value` read-only and just always returns first or default from the collection now. That should make the behaviour more sane.
