### ISSUE TITLE
Activity properties ordering

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#884]
Current ordering is compile dependent (order of stuff in C# file).
However if you have base activity for your other activities the properties from base are placed after the properties from derived.
Is there any way to make it reverse (base first, then derived)?
If not than could we have another property in `ActivityProperty` class that would determine ordering?

**Comment by sfmskywalker** [comment]
Doable, but might be a little bit tricky, since it looks like it would require knowledge of to which property owner the attribute belongs, and then grouping by these owners (e.g. base type and derived type), and then also checking what the hierarchy is of these owners.

We could have the above, but I've been wanting to add support for manual control over the order anyways. So if we have that, then we could simply provide e.g. high (or low, depending on the sort logic) numbers to the base type so that they would appear before the properties of a derived type.

**Comment by tomy2105** [comment]
Yes, manual ordering control (in form of another property in `ActivityProperty` class) would meet my need completely :)!
