### ISSUE TITLE
Instant Event not working with new Date().toISOString()

### ISSUE THREAD

**Issue by joevermonceda** [elsa-workflows/elsa-core#891]
I have an instant event , and it will trigger once a day or every midnight but the expression is not working using new Date().toISOString(). for Literal, JS and Liquid.

![image](https://user-images.githubusercontent.com/66237997/115513968-d5816100-a2ad-11eb-80d9-c0c3d29107c1.png)

Error:
![image](https://user-images.githubusercontent.com/66237997/115514071-ee8a1200-a2ad-11eb-81c5-b0a0854074aa.png)

How could I set date time on Instant Expression? Even DateTimeZone.AtStartOfDay is also not working.

**Comment by sfmskywalker** [comment]
The `InstantExpression` property requires a value of type `Instant`, but your expression returns a `string` instead. To set the property to an instant that represents today, you could use the following expression: `currentInstant`

You can also convert `DateTime` to `Instant` using the `instantFromDateTimeUtc` function. E.g.: `instantFromDateTimeUtc(DateTime.UtcNow)`.

However, I'm afraid that none of the above will actually help you achieve your goal because the `InstantEvent` activity doesn't reliably work in Elsa 1. The only way I could make it work was by completely rewriting it as part of Elsa 2 (where it does work reliably by taking advantage of Quartz or Hangfire, whichever you'd want to use).

**Comment by Ethan0007** [comment]
The workaround for this is to create new activity that will return the preferred datetime format and use in the instant event. 😄
