### ISSUE TITLE
[elsa-2][feature-request] Possibility to flag variables and activity outcomes as volatile / not stored to handle big data

### ISSUE THREAD

**Issue by ckeller81** [elsa-workflows/elsa-core#898]
Imagine the following situation:
A workflow is created to import data into the system. The input data is a large (50MB+) JSON File posted to a HttpEndpoint activity.
The workflow is used to process the data and store it immediately in a processed form in a DB. The input data is no more needed in memory nor in any log or instance storage of the workflow, as when the workflow is finished, all necessary data is already processed.

Currently the HttpEndpoint activity, when using _.WithTargetType<>()_ or _.WithReadContent()_, is parsing the input and returns it as an outcome. This results in storing the outcome data in the WorkflowInstance table of the used workflow-database.

With a large amount of data stored this way, this fills up the WorkflowInstances table with data which is no more used and extremely slows down the workflow-finish.

**A possible approach would be the following:**
- flag an activity with Volatile() to inform the workflow system to only store the outcome of a activity in memory
- flag a Variable (SetVariable activity I think) with Volatile() to inform the workflow system to only store this variable in memory

**Workaround:**
In the above example, a possible workaround would be:
- add _IHttpContextAccessor_ to the workflow constructor
- use the _HttpEndpoint()_ activity without _.WithTargetType<>()_ and without _.WithReadContent()_
- use the _IHttpContextAccessor_ inside a activity to read the Request.Body by yourself and store it anywhere in the memory
- access the data from memory and remove it at the end of the WorkflowInstance run

**Important:** by-design, all volatile stored variables would **not** work after the workflow is suspended and resumed, so this can only be used with a non-blocking workflow. Also pay attention for concurrency-issues, as the workflow can be started multiple times, having different values stored. So always tie the variables together with the WorkflowInstanceId.

**Comment by jdevillard** [comment]
What about allowing the usage of a Cold Storage? 

I'm dealing with the same kind of flow in my application and I've some worker that are present to deals with large message.

The idea here could be to : 
- allow large data (with size specification ) to be dropped in a second storage (if defined) or removed
- allow suppression of data based on time trigger to clean db (or archive data) 

this could be useful to clean db, but also to respect specific need of supervision (GDPR as well as tracking specific data during a specific duration).

Also, if secondary storage is specify for large data (because it can handle large data without restriction like for example Azure Blob Storage), data can be retrieve after suspended/resumed flow. It's could eventually impact a little the performance but it's a user choice with backend process so without heavy load on Workflow runtime.

and finally, this could also allow the user to "download" the data when looking in the Workflow Viewer without the need to display/download all the data on the UI side.

**Comment by sfmskywalker** [comment]
@jdevillard That's a great idea. It could work similar to the way Workflow Context is loaded & persisted. The primary difference being that for workflow input & output, we provide out-of-box implementations for underlying "cold storage" providers (no need to implement a custom workflow context provider, since workflow context is application-specific).
