### ISSUE TITLE
Implement State activity

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#92]
The `State` activity is a simple activity that enables implementing state machines with the following features:

* Exposes a property called `Name` representing the name of the state.
* Exposes a property called `Transitions` representing a list of possible transitions that yield activity outcomes.
* Sets a workflow variable called `CurrentState` to the name of the `State` activity.

The way it works is that as soon as the State activity executes, it will set the `CurrentState` workflow variable to the value of the state's `Name` property. It will then return multiple `Outcome` results, one for each defined transition.

The idea is that each transition will be connected to a halting activity that represents an event. When such an event is triggered, the state machine will transition into the next State (assuming the connected activity is another State activity). All blocking activities connected to the previous State will be cleared. This works similar to the way the `Fork` and `Join` activities work together to branch out and merge back.

**Comment by craigfowler** [comment]
I've been looking into implementing this myself, as it's going to be needed for our usage of Elsa.  I think that perhaps some of the design above is no longer required, because it's already been superseded by other development (to be expected, it's about a year old).

I've got some design ideas for this feature and I'd like to run them by for review.  If this seems reasonable (and we go ahead with Elsa) then expect a PR soon enough with this feature, coded this way.

* The `ActivityBase` class already includes a `Name` property and so any any activity based upon it (almost all are) already has this.
* Setting a `CurrentState` workflow variable to a specified value is already possible via the `SetVariable` activity
* Blocking a waiting for a user action (for example, the choice of a named transition) is already possible via the `UserTask` activity
    * Usage of `UserTask` already returns (as an outcome) the name of the chosen transition, allowing resumption along a specific branch
    * This approach also does not require the clean-up of multiple halting activities, since `UserTask` is the only one which blocked

## An activity to "goto" another activity, including a previously-executed one
Ignoring that [goto is evil], state machines could make use of this functionality in order to design workflows which may re-enter certain states.  Taking a telephone with a hold button for example.  The line is "active", then pressing hold puts it into an "on hold" state, then pressing hold again puts it back to "active".  It's not a new active state we want here, it's the same active state (with all the same outgoing connections) as the original state before pressing hold.

Reading the syntax implied by `IWorkflowBuilder`, `IActivityBuilder` & `IOutcomeBuilder` it seems that the architecture is geared-up so that each time `.Then<TActivity>()` is used, it will result in the creation of a new activity instance and not the re-use of an old one.  A new kind of activity which implements a "Goto" looks like it will be desirable for this.  This can actually be implemented with the `ScheduleActivityResult` and so all that the "Goto" activity need do is to find the desired "next activity" in the workflow and hand it off with a schedule result.

Is there anything to be concerned-about when re-entering an activity which has already been used?  We're halting and so we aren't worried about infinitely spinning loops, chewing up the CPU.  But I wonder about transient values which will have already been initialised once.  I see that the Variables system has a concept of scope with capacity to begin/end scopes, to allow shadowing of existing variables without actually overwriting them.  I actually don't think that this will be relevant for a state machine, because when re-entering a state we are not "in a new scope", we're back to where we were previously and want to behave in a consistent manner no matter how many times we return.

[goto is evil]: https://xkcd.com/292/

## Perhaps: A new kind of expression for getting activity values
The only slight inconvenience with the use of `SetVariable` activity for setting the current workflow state is that the state name would need to be duplicates in both the `Name` and the `ValueExpression` properties of the action.

However, I notice that the workflow context is passed into the expression evaluator, and from the workflow context we can get the current activity.  Assuming that the workflow context is available and may be referenced from a JS expression (I'm not too familiar with Jint, but it looks like that's the case), then actually we could get the Name of the current activity from a JS expression.  That means no duplication and no need for a new activity type (which sets the variable a specific way).

So, is the workflow context and its properties actually accessible from a JS expression?  I don't see that explicitly stated either way in the docs.

## Overall design
Here's a sketch of the overall design I had in mind.  Where possible, I have tried to re-use existing functionality/actions.  Also, I've tried to keep to SRP when thinking about actions.  Submit, Refer internal & Cancel happen to be three sample state-transitions we might use.

![State machine in Elsa](https://user-images.githubusercontent.com/982047/95768315-03a63880-0cae-11eb-9b41-9e2ea0d960dc.png)

The above would certainly meet all of our needs for a state machine, and is probably a bit less work than was originally planned.

**Comment by sfmskywalker** [comment]
We can close this issue since we now have a `State` activity to model state machines. The transitions are simply the outcomes one specifies on the State activity, and to actually transition into the next state, we use a trigger activity like Timer, Message Received, etc.

@craigfowler Let me know if this covers your needs or not.

**Comment by craigfowler** [comment]
It doesn't _on its own_, but actually what we have discovered in our implementation of workflow is that our needs are pretty specific.  They all got tied together with other requirements like user-permissions of which users are allowed to transition a workflow through which states/connections and who can see what.

I think that this is a totally legit implementation for the baseline of the library though, and everything we've needed & subsequently written shouldn't be part of the basic functionality.

**Comment by sfmskywalker** [comment]
So perhaps the library might expose hooks or events during transitioning between two states, allowing application-specific code to control whether or not the transition is allowed.

**Comment by craigfowler** [comment]
That might help.  That said it's kind of complex in our case but I wonder how much Elsa should be modified in order to accommodate one specific usage.  Also as noted toward the end - we're not 100% sure what we want to do with this architecturally in the long term.  Right now we are concentrated on just swapping what we have with a new backend, but making as few architectural changes as possible.

What we have right now is essentially:
1. Halt the workflow
2. Enumerate a list of possible-actions which could resume the workflow (a bit like `UserTask` except that each of those actions has a small model of metadata attached, not just a string)
3. A service (alongside the workflow) which reads the current state of the workflow and also gets a list of the permitted actions which may resume it
    * It is in this service logic that we have all of our permissions logic
    * What we do is get the complete list of every possible action from the workflow, but then filter-out actions which the current claims principal wouldn't be allowed to select
    * Some actions are also not allowed to be interactively selected and are selected by the app framework based on specific circumstances
    * The remaining actions that are allowed to happen next are displayed to the end user as buttons in the UI
4. We may then resume the workflow using one of those actions if it is either selected in the UI or auto-selected via a non-interactive process

An example of a non-interactive action is a "merge conflict" of sorts.  We're using Elsa for "Approval of draft data that is ultimately destined for the app domain database".  We also have validation alongside that.  A creator/author of draft data can't submit successfully if their data is invalid.  Additionally (for accountability purposes) approvers are not permitted to _edit_ the draft data upon approval.  If they disagree then they may only reject & leave feedback messages suggesting fixes (the creator/author may then take another try at submitting).

Now, imagine the creator submits something that is valid for approval.  But, by the time someone opens the draft data for approval it has somehow become invalid.  There's quite a few scenarios that could lead to this, but one of the most common is that a different user made a conflicting change to that same underlying data, much like a source control merge conflict.

In that scenario we automatically-select a "failed and not worth showing to the approver because they aren't allowed to fix it" action and send it straight back to the creator/author with appropriate feedback so that they can fix it.

All of that logic we have implemented alongside Elsa right now (albeit still "behind" our workflow abstraction).  We might be able to integrate some of that more closely with Elsa later down the line, but right now we are trying to keep those scope on the work down by doing a like-for-like replacement with our old workflow.  Architectural improvements will come in a later release.
