### ISSUE TITLE
XSS Security Threat in textboxes in Workflow Designer 1.0

### ISSUE THREAD

**Issue by jgquiroga** [elsa-workflows/elsa-core#924]
The Workflow Designer 1.0 has a problem of Cross Site Scripting in many text editors.

Security Threat: you can execute malicious code inside one of this textbox.

Steps to reproduce:

## In a Title:

1. Create a new Workflow
2. Edit the name of the workflow
3. insert this code:
`
"></wf-text-field><a href="javascript:alert('XSS')">Hacked</a><wf-text-field name="a
`

3. Click on "update"

## In a WriteLine activity
1. Create a new Workflow
2. Add a WriteLine activity
3. Edit the name of the activity
4. Insert this code:
`
"></wf-text-field><a href="javascript:alert('XSS')">Hacked</a><wf-text-field name="a
`

In both cases, we will see HTML injected.
In the image, i can run a javascript code.

![Elsa_designer_xss_00](https://user-images.githubusercontent.com/3643834/116766518-530d4580-aa01-11eb-9be3-f7543293aa04.JPG)

![Elsa_designer_xss_01](https://user-images.githubusercontent.com/3643834/116766475-1a6d6c00-aa01-11eb-91b4-c72a97167e4e.JPG)

![Elsa_designer_xss_02](https://user-images.githubusercontent.com/3643834/116766479-1f322000-aa01-11eb-9e70-99892cb9dfe5.JPG)

![Elsa_designer_xss_03](https://user-images.githubusercontent.com/3643834/116766523-586a9000-aa01-11eb-8550-0aab5745235d.JPG)

**Comment by sfmskywalker** [comment]
Maybe it's good to fix this (at least in Elsa 2's designer), but I'm not sure it's a real problem since only users who are supposed to have access to their workflows backend will be able to do so, and it would not be in their best interest to sabotage their own workflows. Even if this XSS security threat were solved, there are many other ways to break the application.

Unless I'm missing something?

**Comment by jgquiroga** [comment]
Hi. In my case, if I have to add this application into a production environment, first we have to pass a Vulnerability test so some Owasp top 10 threats will appear as critical.

On the other hand, I found that even if I don't have the intentions to sabotage the workflow I'll get errors trying to put "xml" texts or ">" in the textbox:

For example, if I Insert a WriteLine with this description:

`
this is my "description" -> "Hi"
`

![Elsa_designer_xss_04](https://user-images.githubusercontent.com/3643834/116825834-5589af80-ab67-11eb-876e-7a0a1c2fbac8.JPG)

I will see that maybe there are no errors:

![Elsa_designer_xss_05](https://user-images.githubusercontent.com/3643834/116825836-5ae6fa00-ab67-11eb-9d5f-373d429b6109.JPG)

But If I open the Activity, some texts were replaced:

![Elsa_designer_xss_06](https://user-images.githubusercontent.com/3643834/116825864-8833a800-ab67-11eb-9f88-fb35d35f7303.JPG)

If I have some Xml configurations that I want to send to a service in a custom activity then I will lose my configurations.

At first sight, it seems to be a problem with textbox that are not "Expressions".

**Comment by sfmskywalker** [comment]
Fair enough. Regardless of the vulnerability, the designer should definitely not break the way it does as per your screenshots, so that's something to double-check with Elsa 2 and, if needed, be fixed there.

**Comment by sfmskywalker** [comment]
I just tested this in the Elsa 2.0 dashboard, and the issue seems to be gone:

![image](https://user-images.githubusercontent.com/938393/117965338-f07e4880-b322-11eb-8c3b-88ea3e091e50.png)

![image](https://user-images.githubusercontent.com/938393/117965261-d5133d80-b322-11eb-82e3-4f535909afcd.png)

![image](https://user-images.githubusercontent.com/938393/117965291-e0666900-b322-11eb-9a87-8daa592d5394.png)

Please let me know if you do still find these sort of issues with the new dashboard, it is much appreciated.

**Comment by sfmskywalker** [comment]
A related issue was reported where entering an<iframe> element gets executed.

**Comment by sfmskywalker** [comment]
Fixed with f8936564c3ef8cd55866340a46cba512f4f884f3
