### ISSUE TITLE
Recycling application pool invalidates all Signal Url

### ISSUE THREAD

**Issue by andy-22** [elsa-workflows/elsa-core#931]
Hi,
I am using Elsa 1.5.4.1816 which seems to be the latest to date and I seem to have very fundamental issue.
I have .Net standard 5.0 project which runs Elsa flows.

I am using blocking activity as singlaed and generating my signal using the following:

 ```
private async Task<string> GetSignalUrl(WorkflowExecutionContext context, string signalName)
        {
            try
            {
                WorkflowExpression<string> urlExpression =
                    new JavaScriptExpression<string>("`${signalUrl('" + signalName + "')}`");
                string signalUrl = await context.EvaluateAsync(urlExpression, CancellationToken.None);
                return signalUrl;
            }
            catch (Exception e)
            {
                _logger.LogError(e.ToString());
                throw;
            }
        }
```

I am then dispatching email and display it on UI for the next activity to signal. 
Everything is working fine and our complex flow finishes fine as long as we don't recycle application pool OR restart the website.

Since these are long running flows, it is almost with certainty that we have to deploy a code with bug fixes and/or new features and at that time we will have to stop and start the application pool.

Once application pool recycles, all the urls generated using the above code is not valid anymore and I get 404 for all the workflows.

I don't know whether it is a bug or if I am doing something which is not correct.

I will appreciate if someone can promptly respond with their experience and/or solution. 
We are already in UA and ready to go live next week and I discovered this huge issue.

Thanks.

**Comment by sfmskywalker** [comment]
Sounds like it might have something to do with the data protection of the signal payload. Elsa uses ASP.NET’s data protection API for that, which can be configured with a fixed encryption key. I’m currently out of town for a couple of days and can’t look into it myself, but if you checkout Microsoft’s docs on the API you will find guidance on how to configure this for multi node environments.

**Comment by andy-22** [comment]
Thanks for your prompt response. Can you just tell me what part of elsa core I need to look into? I will dig into code and see if I can find something.
My very first assumption is that when we recycle the app pool, I think  WorkflowContext gets lost for all the active workflows.

**Comment by sfmskywalker** [comment]
> I think WorkflowContext gets lost for all the active workflows

Yes, and this is normal. `WorkflowContext` is an in-memory object that keeps track of workflow execution during _a burst of execution_. As soon as a blocking activity is encountered, such as `Signaled`, the burst of execution ends and the workflow gets persisted. 

If the container gets killed before execution reaches a blocking activity, then the workflow will not have gotten a chance to get persisted. This can be handled by configuring the persistence strategy to be more aggressive, e.g. by persisting the workflow after every step, or perhaps on a per-activity level. At least this is possible in Elsa 2.

But it doesn't sound like the issue is that of containers suddenly being killed while the workflow is actively executing, but rather that suspended (persisted) workflows no longer resume after containers have been killed.

Which is likely due to the fact that encrypted signals can no longer be decrypted after a container restart, since the machine encryption key will have been renewed as well.

Here are some links to more information about configuring Data Protection:

- https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-5.0
- https://stackoverflow.com/questions/61452280/how-to-store-data-protection-keys-outside-of-the-docker-container

I don't think there's anything in Elsa that needs to be configured. Configuring data protection can be done from your Startup class.

**Comment by craigfowler** [comment]
> I don't think there's anything in Elsa that needs to be configured. Configuring data protection can be done from your Startup class.

Does that mean _"not a bug, and not currently earmarked for doing any code change in Elsa 2.0"_ ?  I'm not suggesting immediately closing this, since it doesn't seem like we are all _100% certain_ about the root cause, but it seems we think it's a deployment/environment-specific config that needs making and not part of Elsa.

**Comment by andy-22** [comment]
As mentioned by @sfmskywalker we have take care of this from startup itself.. 
For people like me looking for a solution, here is what I did:

services.AddDataProtection()
                .PersistKeysToFileSystem(new DirectoryInfo(Configuration.GetSection("DataProtectionConfiguration:DataProtectionKeyPath").Value.ToString()))
                .ProtectKeysWithCertificate(new X509Certificate2(Configuration.GetSection("DataProtectionConfiguration:SigningCertificatePfxFilePath").Value.ToString(), Configuration.GetSection("DataProtectionConfiguration:SigningCertificatePfxFilePassword").Value.ToString()))
                .SetDefaultKeyLifetime(TimeSpan.FromDays(Convert.ToInt32(Configuration.GetSection("DataProtectionConfiguration:DataProtectionKeyExpiry").Value)))
                .SetApplicationName("APPLICATION_NAME")


I can confirm that, after this changes, it survives my app pool restarts, new deployment, etc. Flow still can continue just fine.

This issue Now can be closed.
