### ISSUE TITLE
Elsa 2 - Join activity not joining

### ISSUE THREAD

**Issue by riatdyl** [elsa-workflows/elsa-core#952]
Hello,

I have a fork activity and I want to join them.

The join activity doesn't join them.
![image](https://user-images.githubusercontent.com/43779018/117624455-3ac1c700-b175-11eb-8199-60e8f4d2028c.png)

**Comment by sfmskywalker** [comment]
The Join activity will not automatically connect other branches - you need to do this manually because there's no way the Join activity can know what branches you wish to connect.

To connect an outcome to an existing activity, simply press and hold the SHIFT button while clicking the outcome. Release the SHIFT button and left-click on the target activity:

![image](https://user-images.githubusercontent.com/938393/117631882-f89c8380-b17c-11eb-94bd-f835b129ac4d.png)

See also: https://elsa-workflows.github.io/elsa-core/docs/next/guides/guides-document-approval#join

**Comment by riatdyl** [comment]
Oh thank you !

It could be interesting to have a legend showing the keys we can use (it's just a suggestion).

**Comment by sfmskywalker** [comment]
That's a good idea actually. We are planning on improving the designer over time. Showing a small legend should be an easy & helpful addition 👍🏻.
