### ISSUE TITLE
OrchardCore workflows migration ?

### ISSUE THREAD

**Issue by giannik** [elsa-workflows/elsa-core#97]
Firstly, this is really cool.
I am using orchard core workflows but I really miss things like versioning that you have built here.
Would it be  possible to replace the existing orchardcore workflow module with this , and still use the orchard core content events (Created, Published etc.),
I would be happy to work on this , since I really would like to use it within orchard core.
Thanks.

**Comment by sfmskywalker** [comment]
Thanks 😄 

There's a number of objectives I have in mind with Elsa in relation to Orchard Core:

1. Create a module (e.g OrchardCore.Elsa.Workflows) that provides the back-end services and controllers that integrate with Orchard Core. This module would provide Orchard Core specific activities, such as the content event activities you mentioned.
2. Turn the Elsa Dashboard MVC area into an Orchard Core front-end theme. This enables Elsa users to manage workflows in a more streamlined fashion, and at the same time allowing them to extend the dashboard using Orchard Core technology.

If you want to take care of creating the module, then that would be absolutely brilliant. I'll assist in any way I can. How about this: I'll create a new repository with an empty ASP.NET Core 3.0 project and turn it in a Orchard CMS host, and scaffold one module and one theme.

Let me know if that works, or if you have another suggestion.

Cheers

**Comment by giannik** [comment]
That sounds like a good starting point. I can work on that and we collaborate on the common project. Let me know the you have the repo ready.

**Comment by sfmskywalker** [comment]
Here you go: https://github.com/elsa-workflows/elsa-orchard-core

In order to create the workflow editor, see how to integrate with the designer etc, you might want to take a look at the [Elsa Dashboard](https://github.com/elsa-workflows/elsa-core/tree/develop/src/dashboard/Elsa.Dashboard) project. It also uses an MVC View Component called [Elsa.WorkflowDesigner](https://github.com/elsa-workflows/elsa-core/tree/develop/src/dashboard/Elsa.WorkflowDesigner), which is designed for reuse.

So if all checks out, you should be able to just use that view component, and look to Elsa Dashboard to see how to use it.

Needless to say, I'm here to help in case you run into any issues.

**Comment by giannik** [comment]
thanks, will get to it.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by sfmskywalker** [comment]
Closing this issue, as a new repo has been created for the Orchard Core integration projects which we'll use to track issues.
