### ISSUE TITLE
Elsa 2 - Dashboard - Where is Email activity?

### ISSUE THREAD

**Issue by atorres16** [elsa-workflows/elsa-core#978]
Can't find it now..

![image](https://user-images.githubusercontent.com/19210281/118194391-ea659600-b40e-11eb-8a8b-150f16a4eac5.png)

**Comment by sfmskywalker** [comment]
Might have been removed accidentally from the dashboard sample project. Will add it back next chance I get. Keep in mind however that this is a sample application. In real world projects you will likely create and maintain your own project since you might want a completely different set of activities and domain services.

**Comment by atorres16** [comment]
I'm trying to tun everything from source, but I'm getting errors (#984 )

**Comment by atorres16** [comment]
Cloned the latest version and it's showing now, thanks!
